package com.huateng.framework.db.ibatis.model;

public class CaclInfKey {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TBL_CACL_INF.DISC_CD
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	private String discCd;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TBL_CACL_INF.STEP_NO
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	private Short stepNo;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TBL_CACL_INF.DISC_CD
	 * 
	 * @return the value of TBL_CACL_INF.DISC_CD
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	public String getDiscCd() {
		return discCd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TBL_CACL_INF.DISC_CD
	 * 
	 * @param discCd
	 *            the value for TBL_CACL_INF.DISC_CD
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	public void setDiscCd(String discCd) {
		this.discCd = discCd;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TBL_CACL_INF.STEP_NO
	 * 
	 * @return the value of TBL_CACL_INF.STEP_NO
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	public Short getStepNo() {
		return stepNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TBL_CACL_INF.STEP_NO
	 * 
	 * @param stepNo
	 *            the value for TBL_CACL_INF.STEP_NO
	 * 
	 * @abatorgenerated Tue Mar 29 16:01:12 CST 2011
	 */
	public void setStepNo(Short stepNo) {
		this.stepNo = stepNo;
	}
}