package com.huateng.framework.db.ibatis.model;

public class LoyaltyContract {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.LOYALTY_CONTRACT_ID
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String loyaltyContractId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.RULE_NO
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String ruleNo;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CONTRACT_BUYER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String contractBuyer;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.DELIVERY_FEE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String deliveryFee;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CONTRACT_SELLER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String contractSeller;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String smsSvcStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String emailSvcStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.MONSTMT_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String monstmtSvcStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.WEB_PAY_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String webPayStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.WEB_SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String webSmsSvcStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.WEB_EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String webEmailSvcStat;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CONTRACT_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String contractState;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.EXPIRY_DATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String expiryDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CREATE_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String createUser;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CREATE_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String createTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.MODIFY_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String modifyUser;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.MODIFY_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String modifyTime;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.DATA_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String dataState;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_LOYALTY_CONTRACT.CLEAR_TP
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	private String clearTp;

	public String getClearTp() {
		return clearTp;
	}

	public void setClearTp(String clearTp) {
		this.clearTp = clearTp;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.LOYALTY_CONTRACT_ID
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.LOYALTY_CONTRACT_ID
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getLoyaltyContractId() {
		return loyaltyContractId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.LOYALTY_CONTRACT_ID
	 * 
	 * @param loyaltyContractId
	 *            the value for TB_LOYALTY_CONTRACT.LOYALTY_CONTRACT_ID
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setLoyaltyContractId(String loyaltyContractId) {
		this.loyaltyContractId = loyaltyContractId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.RULE_NO
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.RULE_NO
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getRuleNo() {
		return ruleNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.RULE_NO
	 * 
	 * @param ruleNo
	 *            the value for TB_LOYALTY_CONTRACT.RULE_NO
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setRuleNo(String ruleNo) {
		this.ruleNo = ruleNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_BUYER
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.CONTRACT_BUYER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getContractBuyer() {
		return contractBuyer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_BUYER
	 * 
	 * @param contractBuyer
	 *            the value for TB_LOYALTY_CONTRACT.CONTRACT_BUYER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setContractBuyer(String contractBuyer) {
		this.contractBuyer = contractBuyer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.DELIVERY_FEE
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.DELIVERY_FEE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getDeliveryFee() {
		return deliveryFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.DELIVERY_FEE
	 * 
	 * @param deliveryFee
	 *            the value for TB_LOYALTY_CONTRACT.DELIVERY_FEE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setDeliveryFee(String deliveryFee) {
		this.deliveryFee = deliveryFee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_SELLER
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.CONTRACT_SELLER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getContractSeller() {
		return contractSeller;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_SELLER
	 * 
	 * @param contractSeller
	 *            the value for TB_LOYALTY_CONTRACT.CONTRACT_SELLER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setContractSeller(String contractSeller) {
		this.contractSeller = contractSeller;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.SMS_SVC_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getSmsSvcStat() {
		return smsSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.SMS_SVC_STAT
	 * 
	 * @param smsSvcStat
	 *            the value for TB_LOYALTY_CONTRACT.SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setSmsSvcStat(String smsSvcStat) {
		this.smsSvcStat = smsSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.EMAIL_SVC_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getEmailSvcStat() {
		return emailSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.EMAIL_SVC_STAT
	 * 
	 * @param emailSvcStat
	 *            the value for TB_LOYALTY_CONTRACT.EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setEmailSvcStat(String emailSvcStat) {
		this.emailSvcStat = emailSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.MONSTMT_SVC_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.MONSTMT_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getMonstmtSvcStat() {
		return monstmtSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.MONSTMT_SVC_STAT
	 * 
	 * @param monstmtSvcStat
	 *            the value for TB_LOYALTY_CONTRACT.MONSTMT_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setMonstmtSvcStat(String monstmtSvcStat) {
		this.monstmtSvcStat = monstmtSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_PAY_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.WEB_PAY_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getWebPayStat() {
		return webPayStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_PAY_STAT
	 * 
	 * @param webPayStat
	 *            the value for TB_LOYALTY_CONTRACT.WEB_PAY_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setWebPayStat(String webPayStat) {
		this.webPayStat = webPayStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_SMS_SVC_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.WEB_SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getWebSmsSvcStat() {
		return webSmsSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_SMS_SVC_STAT
	 * 
	 * @param webSmsSvcStat
	 *            the value for TB_LOYALTY_CONTRACT.WEB_SMS_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setWebSmsSvcStat(String webSmsSvcStat) {
		this.webSmsSvcStat = webSmsSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_EMAIL_SVC_STAT
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.WEB_EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getWebEmailSvcStat() {
		return webEmailSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.WEB_EMAIL_SVC_STAT
	 * 
	 * @param webEmailSvcStat
	 *            the value for TB_LOYALTY_CONTRACT.WEB_EMAIL_SVC_STAT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setWebEmailSvcStat(String webEmailSvcStat) {
		this.webEmailSvcStat = webEmailSvcStat;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_STATE
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.CONTRACT_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getContractState() {
		return contractState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.CONTRACT_STATE
	 * 
	 * @param contractState
	 *            the value for TB_LOYALTY_CONTRACT.CONTRACT_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setContractState(String contractState) {
		this.contractState = contractState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.EXPIRY_DATE
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.EXPIRY_DATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getExpiryDate() {
		return expiryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.EXPIRY_DATE
	 * 
	 * @param expiryDate
	 *            the value for TB_LOYALTY_CONTRACT.EXPIRY_DATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.CREATE_USER
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.CREATE_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.CREATE_USER
	 * 
	 * @param createUser
	 *            the value for TB_LOYALTY_CONTRACT.CREATE_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.CREATE_TIME
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.CREATE_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.CREATE_TIME
	 * 
	 * @param createTime
	 *            the value for TB_LOYALTY_CONTRACT.CREATE_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.MODIFY_USER
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.MODIFY_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getModifyUser() {
		return modifyUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.MODIFY_USER
	 * 
	 * @param modifyUser
	 *            the value for TB_LOYALTY_CONTRACT.MODIFY_USER
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.MODIFY_TIME
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.MODIFY_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.MODIFY_TIME
	 * 
	 * @param modifyTime
	 *            the value for TB_LOYALTY_CONTRACT.MODIFY_TIME
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setModifyTime(String modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_LOYALTY_CONTRACT.DATA_STATE
	 * 
	 * @return the value of TB_LOYALTY_CONTRACT.DATA_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getDataState() {
		return dataState;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_LOYALTY_CONTRACT.DATA_STATE
	 * 
	 * @param dataState
	 *            the value for TB_LOYALTY_CONTRACT.DATA_STATE
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setDataState(String dataState) {
		this.dataState = dataState;
	}
}