package com.huateng.framework.ibatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class CardRouteExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public CardRouteExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	protected CardRouteExample(CardRouteExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TBL_CARD_ROUTE
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;

		protected List<Map<String, Object>> criteriaWithSingleValue;

		protected List<Map<String, Object>> criteriaWithListValue;

		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andMaxBinIsNull() {
			addCriterion("MAX_BIN is null");
			return this;
		}

		public Criteria andMaxBinIsNotNull() {
			addCriterion("MAX_BIN is not null");
			return this;
		}

		public Criteria andMaxBinEqualTo(String value) {
			addCriterion("MAX_BIN =", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinNotEqualTo(String value) {
			addCriterion("MAX_BIN <>", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinGreaterThan(String value) {
			addCriterion("MAX_BIN >", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinGreaterThanOrEqualTo(String value) {
			addCriterion("MAX_BIN >=", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinLessThan(String value) {
			addCriterion("MAX_BIN <", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinLessThanOrEqualTo(String value) {
			addCriterion("MAX_BIN <=", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinLike(String value) {
			addCriterion("MAX_BIN like", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinNotLike(String value) {
			addCriterion("MAX_BIN not like", value, "maxBin");
			return this;
		}

		public Criteria andMaxBinIn(List<String> values) {
			addCriterion("MAX_BIN in", values, "maxBin");
			return this;
		}

		public Criteria andMaxBinNotIn(List<String> values) {
			addCriterion("MAX_BIN not in", values, "maxBin");
			return this;
		}

		public Criteria andMaxBinBetween(String value1, String value2) {
			addCriterion("MAX_BIN between", value1, value2, "maxBin");
			return this;
		}

		public Criteria andMaxBinNotBetween(String value1, String value2) {
			addCriterion("MAX_BIN not between", value1, value2, "maxBin");
			return this;
		}

		public Criteria andMinBinIsNull() {
			addCriterion("MIN_BIN is null");
			return this;
		}

		public Criteria andMinBinIsNotNull() {
			addCriterion("MIN_BIN is not null");
			return this;
		}

		public Criteria andMinBinEqualTo(String value) {
			addCriterion("MIN_BIN =", value, "minBin");
			return this;
		}

		public Criteria andMinBinNotEqualTo(String value) {
			addCriterion("MIN_BIN <>", value, "minBin");
			return this;
		}

		public Criteria andMinBinGreaterThan(String value) {
			addCriterion("MIN_BIN >", value, "minBin");
			return this;
		}

		public Criteria andMinBinGreaterThanOrEqualTo(String value) {
			addCriterion("MIN_BIN >=", value, "minBin");
			return this;
		}

		public Criteria andMinBinLessThan(String value) {
			addCriterion("MIN_BIN <", value, "minBin");
			return this;
		}

		public Criteria andMinBinLessThanOrEqualTo(String value) {
			addCriterion("MIN_BIN <=", value, "minBin");
			return this;
		}

		public Criteria andMinBinLike(String value) {
			addCriterion("MIN_BIN like", value, "minBin");
			return this;
		}

		public Criteria andMinBinNotLike(String value) {
			addCriterion("MIN_BIN not like", value, "minBin");
			return this;
		}

		public Criteria andMinBinIn(List<String> values) {
			addCriterion("MIN_BIN in", values, "minBin");
			return this;
		}

		public Criteria andMinBinNotIn(List<String> values) {
			addCriterion("MIN_BIN not in", values, "minBin");
			return this;
		}

		public Criteria andMinBinBetween(String value1, String value2) {
			addCriterion("MIN_BIN between", value1, value2, "minBin");
			return this;
		}

		public Criteria andMinBinNotBetween(String value1, String value2) {
			addCriterion("MIN_BIN not between", value1, value2, "minBin");
			return this;
		}

		public Criteria andTransChnlIsNull() {
			addCriterion("TRANS_CHNL is null");
			return this;
		}

		public Criteria andTransChnlIsNotNull() {
			addCriterion("TRANS_CHNL is not null");
			return this;
		}

		public Criteria andTransChnlEqualTo(String value) {
			addCriterion("TRANS_CHNL =", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlNotEqualTo(String value) {
			addCriterion("TRANS_CHNL <>", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlGreaterThan(String value) {
			addCriterion("TRANS_CHNL >", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlGreaterThanOrEqualTo(String value) {
			addCriterion("TRANS_CHNL >=", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlLessThan(String value) {
			addCriterion("TRANS_CHNL <", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlLessThanOrEqualTo(String value) {
			addCriterion("TRANS_CHNL <=", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlLike(String value) {
			addCriterion("TRANS_CHNL like", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlNotLike(String value) {
			addCriterion("TRANS_CHNL not like", value, "transChnl");
			return this;
		}

		public Criteria andTransChnlIn(List<String> values) {
			addCriterion("TRANS_CHNL in", values, "transChnl");
			return this;
		}

		public Criteria andTransChnlNotIn(List<String> values) {
			addCriterion("TRANS_CHNL not in", values, "transChnl");
			return this;
		}

		public Criteria andTransChnlBetween(String value1, String value2) {
			addCriterion("TRANS_CHNL between", value1, value2, "transChnl");
			return this;
		}

		public Criteria andTransChnlNotBetween(String value1, String value2) {
			addCriterion("TRANS_CHNL not between", value1, value2, "transChnl");
			return this;
		}

		public Criteria andTransIdIsNull() {
			addCriterion("TRANS_ID is null");
			return this;
		}

		public Criteria andTransIdIsNotNull() {
			addCriterion("TRANS_ID is not null");
			return this;
		}

		public Criteria andTransIdEqualTo(String value) {
			addCriterion("TRANS_ID =", value, "transId");
			return this;
		}

		public Criteria andTransIdNotEqualTo(String value) {
			addCriterion("TRANS_ID <>", value, "transId");
			return this;
		}

		public Criteria andTransIdGreaterThan(String value) {
			addCriterion("TRANS_ID >", value, "transId");
			return this;
		}

		public Criteria andTransIdGreaterThanOrEqualTo(String value) {
			addCriterion("TRANS_ID >=", value, "transId");
			return this;
		}

		public Criteria andTransIdLessThan(String value) {
			addCriterion("TRANS_ID <", value, "transId");
			return this;
		}

		public Criteria andTransIdLessThanOrEqualTo(String value) {
			addCriterion("TRANS_ID <=", value, "transId");
			return this;
		}

		public Criteria andTransIdLike(String value) {
			addCriterion("TRANS_ID like", value, "transId");
			return this;
		}

		public Criteria andTransIdNotLike(String value) {
			addCriterion("TRANS_ID not like", value, "transId");
			return this;
		}

		public Criteria andTransIdIn(List<String> values) {
			addCriterion("TRANS_ID in", values, "transId");
			return this;
		}

		public Criteria andTransIdNotIn(List<String> values) {
			addCriterion("TRANS_ID not in", values, "transId");
			return this;
		}

		public Criteria andTransIdBetween(String value1, String value2) {
			addCriterion("TRANS_ID between", value1, value2, "transId");
			return this;
		}

		public Criteria andTransIdNotBetween(String value1, String value2) {
			addCriterion("TRANS_ID not between", value1, value2, "transId");
			return this;
		}

		public Criteria andCardAttrIsNull() {
			addCriterion("CARD_ATTR is null");
			return this;
		}

		public Criteria andCardAttrIsNotNull() {
			addCriterion("CARD_ATTR is not null");
			return this;
		}

		public Criteria andCardAttrEqualTo(String value) {
			addCriterion("CARD_ATTR =", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrNotEqualTo(String value) {
			addCriterion("CARD_ATTR <>", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrGreaterThan(String value) {
			addCriterion("CARD_ATTR >", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_ATTR >=", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrLessThan(String value) {
			addCriterion("CARD_ATTR <", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrLessThanOrEqualTo(String value) {
			addCriterion("CARD_ATTR <=", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrLike(String value) {
			addCriterion("CARD_ATTR like", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrNotLike(String value) {
			addCriterion("CARD_ATTR not like", value, "cardAttr");
			return this;
		}

		public Criteria andCardAttrIn(List<String> values) {
			addCriterion("CARD_ATTR in", values, "cardAttr");
			return this;
		}

		public Criteria andCardAttrNotIn(List<String> values) {
			addCriterion("CARD_ATTR not in", values, "cardAttr");
			return this;
		}

		public Criteria andCardAttrBetween(String value1, String value2) {
			addCriterion("CARD_ATTR between", value1, value2, "cardAttr");
			return this;
		}

		public Criteria andCardAttrNotBetween(String value1, String value2) {
			addCriterion("CARD_ATTR not between", value1, value2, "cardAttr");
			return this;
		}

		public Criteria andRcvInsIdCdIsNull() {
			addCriterion("RCV_INS_ID_CD is null");
			return this;
		}

		public Criteria andRcvInsIdCdIsNotNull() {
			addCriterion("RCV_INS_ID_CD is not null");
			return this;
		}

		public Criteria andRcvInsIdCdEqualTo(String value) {
			addCriterion("RCV_INS_ID_CD =", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdNotEqualTo(String value) {
			addCriterion("RCV_INS_ID_CD <>", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdGreaterThan(String value) {
			addCriterion("RCV_INS_ID_CD >", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdGreaterThanOrEqualTo(String value) {
			addCriterion("RCV_INS_ID_CD >=", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdLessThan(String value) {
			addCriterion("RCV_INS_ID_CD <", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdLessThanOrEqualTo(String value) {
			addCriterion("RCV_INS_ID_CD <=", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdLike(String value) {
			addCriterion("RCV_INS_ID_CD like", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdNotLike(String value) {
			addCriterion("RCV_INS_ID_CD not like", value, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdIn(List<String> values) {
			addCriterion("RCV_INS_ID_CD in", values, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdNotIn(List<String> values) {
			addCriterion("RCV_INS_ID_CD not in", values, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdBetween(String value1, String value2) {
			addCriterion("RCV_INS_ID_CD between", value1, value2, "rcvInsIdCd");
			return this;
		}

		public Criteria andRcvInsIdCdNotBetween(String value1, String value2) {
			addCriterion("RCV_INS_ID_CD not between", value1, value2,
					"rcvInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdIsNull() {
			addCriterion("ISS_INS_ID_CD is null");
			return this;
		}

		public Criteria andIssInsIdCdIsNotNull() {
			addCriterion("ISS_INS_ID_CD is not null");
			return this;
		}

		public Criteria andIssInsIdCdEqualTo(String value) {
			addCriterion("ISS_INS_ID_CD =", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdNotEqualTo(String value) {
			addCriterion("ISS_INS_ID_CD <>", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdGreaterThan(String value) {
			addCriterion("ISS_INS_ID_CD >", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdGreaterThanOrEqualTo(String value) {
			addCriterion("ISS_INS_ID_CD >=", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdLessThan(String value) {
			addCriterion("ISS_INS_ID_CD <", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdLessThanOrEqualTo(String value) {
			addCriterion("ISS_INS_ID_CD <=", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdLike(String value) {
			addCriterion("ISS_INS_ID_CD like", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdNotLike(String value) {
			addCriterion("ISS_INS_ID_CD not like", value, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdIn(List<String> values) {
			addCriterion("ISS_INS_ID_CD in", values, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdNotIn(List<String> values) {
			addCriterion("ISS_INS_ID_CD not in", values, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdBetween(String value1, String value2) {
			addCriterion("ISS_INS_ID_CD between", value1, value2, "issInsIdCd");
			return this;
		}

		public Criteria andIssInsIdCdNotBetween(String value1, String value2) {
			addCriterion("ISS_INS_ID_CD not between", value1, value2,
					"issInsIdCd");
			return this;
		}

		public Criteria andRsvDataIsNull() {
			addCriterion("RSV_DATA is null");
			return this;
		}

		public Criteria andRsvDataIsNotNull() {
			addCriterion("RSV_DATA is not null");
			return this;
		}

		public Criteria andRsvDataEqualTo(String value) {
			addCriterion("RSV_DATA =", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataNotEqualTo(String value) {
			addCriterion("RSV_DATA <>", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataGreaterThan(String value) {
			addCriterion("RSV_DATA >", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataGreaterThanOrEqualTo(String value) {
			addCriterion("RSV_DATA >=", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataLessThan(String value) {
			addCriterion("RSV_DATA <", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataLessThanOrEqualTo(String value) {
			addCriterion("RSV_DATA <=", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataLike(String value) {
			addCriterion("RSV_DATA like", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataNotLike(String value) {
			addCriterion("RSV_DATA not like", value, "rsvData");
			return this;
		}

		public Criteria andRsvDataIn(List<String> values) {
			addCriterion("RSV_DATA in", values, "rsvData");
			return this;
		}

		public Criteria andRsvDataNotIn(List<String> values) {
			addCriterion("RSV_DATA not in", values, "rsvData");
			return this;
		}

		public Criteria andRsvDataBetween(String value1, String value2) {
			addCriterion("RSV_DATA between", value1, value2, "rsvData");
			return this;
		}

		public Criteria andRsvDataNotBetween(String value1, String value2) {
			addCriterion("RSV_DATA not between", value1, value2, "rsvData");
			return this;
		}

		public Criteria andBinValIsNull() {
			addCriterion("BIN_VAL is null");
			return this;
		}

		public Criteria andBinValIsNotNull() {
			addCriterion("BIN_VAL is not null");
			return this;
		}

		public Criteria andBinValEqualTo(String value) {
			addCriterion("BIN_VAL =", value, "binVal");
			return this;
		}

		public Criteria andBinValNotEqualTo(String value) {
			addCriterion("BIN_VAL <>", value, "binVal");
			return this;
		}

		public Criteria andBinValGreaterThan(String value) {
			addCriterion("BIN_VAL >", value, "binVal");
			return this;
		}

		public Criteria andBinValGreaterThanOrEqualTo(String value) {
			addCriterion("BIN_VAL >=", value, "binVal");
			return this;
		}

		public Criteria andBinValLessThan(String value) {
			addCriterion("BIN_VAL <", value, "binVal");
			return this;
		}

		public Criteria andBinValLessThanOrEqualTo(String value) {
			addCriterion("BIN_VAL <=", value, "binVal");
			return this;
		}

		public Criteria andBinValLike(String value) {
			addCriterion("BIN_VAL like", value, "binVal");
			return this;
		}

		public Criteria andBinValNotLike(String value) {
			addCriterion("BIN_VAL not like", value, "binVal");
			return this;
		}

		public Criteria andBinValIn(List<String> values) {
			addCriterion("BIN_VAL in", values, "binVal");
			return this;
		}

		public Criteria andBinValNotIn(List<String> values) {
			addCriterion("BIN_VAL not in", values, "binVal");
			return this;
		}

		public Criteria andBinValBetween(String value1, String value2) {
			addCriterion("BIN_VAL between", value1, value2, "binVal");
			return this;
		}

		public Criteria andBinValNotBetween(String value1, String value2) {
			addCriterion("BIN_VAL not between", value1, value2, "binVal");
			return this;
		}

		public Criteria andRecUpdUsrIdIsNull() {
			addCriterion("REC_UPD_USR_ID is null");
			return this;
		}

		public Criteria andRecUpdUsrIdIsNotNull() {
			addCriterion("REC_UPD_USR_ID is not null");
			return this;
		}

		public Criteria andRecUpdUsrIdEqualTo(String value) {
			addCriterion("REC_UPD_USR_ID =", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdNotEqualTo(String value) {
			addCriterion("REC_UPD_USR_ID <>", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdGreaterThan(String value) {
			addCriterion("REC_UPD_USR_ID >", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdGreaterThanOrEqualTo(String value) {
			addCriterion("REC_UPD_USR_ID >=", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdLessThan(String value) {
			addCriterion("REC_UPD_USR_ID <", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdLessThanOrEqualTo(String value) {
			addCriterion("REC_UPD_USR_ID <=", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdLike(String value) {
			addCriterion("REC_UPD_USR_ID like", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdNotLike(String value) {
			addCriterion("REC_UPD_USR_ID not like", value, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdIn(List<String> values) {
			addCriterion("REC_UPD_USR_ID in", values, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdNotIn(List<String> values) {
			addCriterion("REC_UPD_USR_ID not in", values, "recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdBetween(String value1, String value2) {
			addCriterion("REC_UPD_USR_ID between", value1, value2,
					"recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdUsrIdNotBetween(String value1, String value2) {
			addCriterion("REC_UPD_USR_ID not between", value1, value2,
					"recUpdUsrId");
			return this;
		}

		public Criteria andRecUpdTsIsNull() {
			addCriterion("REC_UPD_TS is null");
			return this;
		}

		public Criteria andRecUpdTsIsNotNull() {
			addCriterion("REC_UPD_TS is not null");
			return this;
		}

		public Criteria andRecUpdTsEqualTo(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS =", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsNotEqualTo(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS <>", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsGreaterThan(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS >", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS >=", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsLessThan(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS <", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("REC_UPD_TS <=", value, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsIn(List<Date> values) {
			addCriterionForJDBCDate("REC_UPD_TS in", values, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsNotIn(List<Date> values) {
			addCriterionForJDBCDate("REC_UPD_TS not in", values, "recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("REC_UPD_TS between", value1, value2,
					"recUpdTs");
			return this;
		}

		public Criteria andRecUpdTsNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("REC_UPD_TS not between", value1, value2,
					"recUpdTs");
			return this;
		}

		public Criteria andRecCrtTsIsNull() {
			addCriterion("REC_CRT_TS is null");
			return this;
		}

		public Criteria andRecCrtTsIsNotNull() {
			addCriterion("REC_CRT_TS is not null");
			return this;
		}

		public Criteria andRecCrtTsEqualTo(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS =", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsNotEqualTo(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS <>", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsGreaterThan(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS >", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS >=", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsLessThan(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS <", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("REC_CRT_TS <=", value, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsIn(List<Date> values) {
			addCriterionForJDBCDate("REC_CRT_TS in", values, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsNotIn(List<Date> values) {
			addCriterionForJDBCDate("REC_CRT_TS not in", values, "recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("REC_CRT_TS between", value1, value2,
					"recCrtTs");
			return this;
		}

		public Criteria andRecCrtTsNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("REC_CRT_TS not between", value1, value2,
					"recCrtTs");
			return this;
		}
	}
}