package com.huateng.framework.ibatis.model;

public class CheckPeopleInfo extends CheckPeopleInfoKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_CHECK_PEOPLE_INFO.CARD_NO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    private String cardNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_CHECK_PEOPLE_INFO.CHECK_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    private String checkState;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TB_CHECK_PEOPLE_INFO.DATA_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    private String dataState;
    
    
    
    private String createTime;
    private String updateTime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_CHECK_PEOPLE_INFO.CARD_NO
     *
     * @return the value of TB_CHECK_PEOPLE_INFO.CARD_NO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_CHECK_PEOPLE_INFO.CARD_NO
     *
     * @param cardNo the value for TB_CHECK_PEOPLE_INFO.CARD_NO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_CHECK_PEOPLE_INFO.CHECK_STATE
     *
     * @return the value of TB_CHECK_PEOPLE_INFO.CHECK_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public String getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_CHECK_PEOPLE_INFO.CHECK_STATE
     *
     * @param checkState the value for TB_CHECK_PEOPLE_INFO.CHECK_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void setCheckState(String checkState) {
        this.checkState = checkState == null ? null : checkState.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TB_CHECK_PEOPLE_INFO.DATA_STATE
     *
     * @return the value of TB_CHECK_PEOPLE_INFO.DATA_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public String getDataState() {
        return dataState;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TB_CHECK_PEOPLE_INFO.DATA_STATE
     *
     * @param dataState the value for TB_CHECK_PEOPLE_INFO.DATA_STATE
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void setDataState(String dataState) {
        this.dataState = dataState == null ? null : dataState.trim();
    }

	public String getCreateTime() {
		return createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}
    
}