package com.huateng.framework.ibatis.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ShopExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public ShopExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	protected ShopExample(ShopExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_SHOP
	 * 
	 * @abatorgenerated Fri Nov 26 14:45:50 CST 2010
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;

		protected List<Map<String, Object>> criteriaWithSingleValue;

		protected List<Map<String, Object>> criteriaWithListValue;

		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andShopIdIsNull() {
			addCriterion("SHOP_ID is null");
			return this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("SHOP_ID is not null");
			return this;
		}

		public Criteria andShopIdEqualTo(String value) {
			addCriterion("SHOP_ID =", value, "shopId");
			return this;
		}

		public Criteria andShopIdNotEqualTo(String value) {
			addCriterion("SHOP_ID <>", value, "shopId");
			return this;
		}

		public Criteria andShopIdGreaterThan(String value) {
			addCriterion("SHOP_ID >", value, "shopId");
			return this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_ID >=", value, "shopId");
			return this;
		}

		public Criteria andShopIdLessThan(String value) {
			addCriterion("SHOP_ID <", value, "shopId");
			return this;
		}

		public Criteria andShopIdLessThanOrEqualTo(String value) {
			addCriterion("SHOP_ID <=", value, "shopId");
			return this;
		}

		public Criteria andShopIdLike(String value) {
			addCriterion("SHOP_ID like", value, "shopId");
			return this;
		}

		public Criteria andShopIdNotLike(String value) {
			addCriterion("SHOP_ID not like", value, "shopId");
			return this;
		}

		public Criteria andShopIdIn(List<String> values) {
			addCriterion("SHOP_ID in", values, "shopId");
			return this;
		}

		public Criteria andShopIdNotIn(List<String> values) {
			addCriterion("SHOP_ID not in", values, "shopId");
			return this;
		}

		public Criteria andShopIdBetween(String value1, String value2) {
			addCriterion("SHOP_ID between", value1, value2, "shopId");
			return this;
		}

		public Criteria andShopIdNotBetween(String value1, String value2) {
			addCriterion("SHOP_ID not between", value1, value2, "shopId");
			return this;
		}

		public Criteria andEntityIdIsNull() {
			addCriterion("ENTITY_ID is null");
			return this;
		}

		public Criteria andEntityIdIsNotNull() {
			addCriterion("ENTITY_ID is not null");
			return this;
		}

		public Criteria andEntityIdEqualTo(String value) {
			addCriterion("ENTITY_ID =", value, "entityId");
			return this;
		}

		public Criteria andEntityIdNotEqualTo(String value) {
			addCriterion("ENTITY_ID <>", value, "entityId");
			return this;
		}

		public Criteria andEntityIdGreaterThan(String value) {
			addCriterion("ENTITY_ID >", value, "entityId");
			return this;
		}

		public Criteria andEntityIdGreaterThanOrEqualTo(String value) {
			addCriterion("ENTITY_ID >=", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLessThan(String value) {
			addCriterion("ENTITY_ID <", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLessThanOrEqualTo(String value) {
			addCriterion("ENTITY_ID <=", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLike(String value) {
			addCriterion("ENTITY_ID like", value, "entityId");
			return this;
		}

		public Criteria andEntityIdNotLike(String value) {
			addCriterion("ENTITY_ID not like", value, "entityId");
			return this;
		}

		public Criteria andEntityIdIn(List<String> values) {
			addCriterion("ENTITY_ID in", values, "entityId");
			return this;
		}

		public Criteria andEntityIdNotIn(List<String> values) {
			addCriterion("ENTITY_ID not in", values, "entityId");
			return this;
		}

		public Criteria andEntityIdBetween(String value1, String value2) {
			addCriterion("ENTITY_ID between", value1, value2, "entityId");
			return this;
		}

		public Criteria andEntityIdNotBetween(String value1, String value2) {
			addCriterion("ENTITY_ID not between", value1, value2, "entityId");
			return this;
		}

		public Criteria andConsumerIdIsNull() {
			addCriterion("CONSUMER_ID is null");
			return this;
		}

		public Criteria andConsumerIdIsNotNull() {
			addCriterion("CONSUMER_ID is not null");
			return this;
		}

		public Criteria andConsumerIdEqualTo(String value) {
			addCriterion("CONSUMER_ID =", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdNotEqualTo(String value) {
			addCriterion("CONSUMER_ID <>", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdGreaterThan(String value) {
			addCriterion("CONSUMER_ID >", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdGreaterThanOrEqualTo(String value) {
			addCriterion("CONSUMER_ID >=", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdLessThan(String value) {
			addCriterion("CONSUMER_ID <", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdLessThanOrEqualTo(String value) {
			addCriterion("CONSUMER_ID <=", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdLike(String value) {
			addCriterion("CONSUMER_ID like", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdNotLike(String value) {
			addCriterion("CONSUMER_ID not like", value, "consumerId");
			return this;
		}

		public Criteria andConsumerIdIn(List<String> values) {
			addCriterion("CONSUMER_ID in", values, "consumerId");
			return this;
		}

		public Criteria andConsumerIdNotIn(List<String> values) {
			addCriterion("CONSUMER_ID not in", values, "consumerId");
			return this;
		}

		public Criteria andConsumerIdBetween(String value1, String value2) {
			addCriterion("CONSUMER_ID between", value1, value2, "consumerId");
			return this;
		}

		public Criteria andConsumerIdNotBetween(String value1, String value2) {
			addCriterion("CONSUMER_ID not between", value1, value2,
					"consumerId");
			return this;
		}

		public Criteria andShopCodeIsNull() {
			addCriterion("SHOP_CODE is null");
			return this;
		}

		public Criteria andShopCodeIsNotNull() {
			addCriterion("SHOP_CODE is not null");
			return this;
		}

		public Criteria andShopCodeEqualTo(String value) {
			addCriterion("SHOP_CODE =", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotEqualTo(String value) {
			addCriterion("SHOP_CODE <>", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeGreaterThan(String value) {
			addCriterion("SHOP_CODE >", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_CODE >=", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLessThan(String value) {
			addCriterion("SHOP_CODE <", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_CODE <=", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeLike(String value) {
			addCriterion("SHOP_CODE like", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotLike(String value) {
			addCriterion("SHOP_CODE not like", value, "shopCode");
			return this;
		}

		public Criteria andShopCodeIn(List<String> values) {
			addCriterion("SHOP_CODE in", values, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotIn(List<String> values) {
			addCriterion("SHOP_CODE not in", values, "shopCode");
			return this;
		}

		public Criteria andShopCodeBetween(String value1, String value2) {
			addCriterion("SHOP_CODE between", value1, value2, "shopCode");
			return this;
		}

		public Criteria andShopCodeNotBetween(String value1, String value2) {
			addCriterion("SHOP_CODE not between", value1, value2, "shopCode");
			return this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("SHOP_NAME is null");
			return this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("SHOP_NAME is not null");
			return this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("SHOP_NAME =", value, "shopName");
			return this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("SHOP_NAME <>", value, "shopName");
			return this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("SHOP_NAME >", value, "shopName");
			return this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_NAME >=", value, "shopName");
			return this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("SHOP_NAME <", value, "shopName");
			return this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("SHOP_NAME <=", value, "shopName");
			return this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("SHOP_NAME like", value, "shopName");
			return this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("SHOP_NAME not like", value, "shopName");
			return this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("SHOP_NAME in", values, "shopName");
			return this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("SHOP_NAME not in", values, "shopName");
			return this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("SHOP_NAME between", value1, value2, "shopName");
			return this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("SHOP_NAME not between", value1, value2, "shopName");
			return this;
		}

		public Criteria andShopEnglishNameIsNull() {
			addCriterion("SHOP_ENGLISH_NAME is null");
			return this;
		}

		public Criteria andShopEnglishNameIsNotNull() {
			addCriterion("SHOP_ENGLISH_NAME is not null");
			return this;
		}

		public Criteria andShopEnglishNameEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_NAME =", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameNotEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_NAME <>", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameGreaterThan(String value) {
			addCriterion("SHOP_ENGLISH_NAME >", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_NAME >=", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameLessThan(String value) {
			addCriterion("SHOP_ENGLISH_NAME <", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameLessThanOrEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_NAME <=", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameLike(String value) {
			addCriterion("SHOP_ENGLISH_NAME like", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameNotLike(String value) {
			addCriterion("SHOP_ENGLISH_NAME not like", value, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameIn(List<String> values) {
			addCriterion("SHOP_ENGLISH_NAME in", values, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameNotIn(List<String> values) {
			addCriterion("SHOP_ENGLISH_NAME not in", values, "shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameBetween(String value1, String value2) {
			addCriterion("SHOP_ENGLISH_NAME between", value1, value2,
					"shopEnglishName");
			return this;
		}

		public Criteria andShopEnglishNameNotBetween(String value1,
				String value2) {
			addCriterion("SHOP_ENGLISH_NAME not between", value1, value2,
					"shopEnglishName");
			return this;
		}

		public Criteria andShopAddressIsNull() {
			addCriterion("SHOP_ADDRESS is null");
			return this;
		}

		public Criteria andShopAddressIsNotNull() {
			addCriterion("SHOP_ADDRESS is not null");
			return this;
		}

		public Criteria andShopAddressEqualTo(String value) {
			addCriterion("SHOP_ADDRESS =", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressNotEqualTo(String value) {
			addCriterion("SHOP_ADDRESS <>", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressGreaterThan(String value) {
			addCriterion("SHOP_ADDRESS >", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_ADDRESS >=", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressLessThan(String value) {
			addCriterion("SHOP_ADDRESS <", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressLessThanOrEqualTo(String value) {
			addCriterion("SHOP_ADDRESS <=", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressLike(String value) {
			addCriterion("SHOP_ADDRESS like", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressNotLike(String value) {
			addCriterion("SHOP_ADDRESS not like", value, "shopAddress");
			return this;
		}

		public Criteria andShopAddressIn(List<String> values) {
			addCriterion("SHOP_ADDRESS in", values, "shopAddress");
			return this;
		}

		public Criteria andShopAddressNotIn(List<String> values) {
			addCriterion("SHOP_ADDRESS not in", values, "shopAddress");
			return this;
		}

		public Criteria andShopAddressBetween(String value1, String value2) {
			addCriterion("SHOP_ADDRESS between", value1, value2, "shopAddress");
			return this;
		}

		public Criteria andShopAddressNotBetween(String value1, String value2) {
			addCriterion("SHOP_ADDRESS not between", value1, value2,
					"shopAddress");
			return this;
		}

		public Criteria andShopEnglishAddressIsNull() {
			addCriterion("SHOP_ENGLISH_ADDRESS is null");
			return this;
		}

		public Criteria andShopEnglishAddressIsNotNull() {
			addCriterion("SHOP_ENGLISH_ADDRESS is not null");
			return this;
		}

		public Criteria andShopEnglishAddressEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS =", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressNotEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS <>", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressGreaterThan(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS >", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS >=", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressLessThan(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS <", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressLessThanOrEqualTo(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS <=", value, "shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressLike(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS like", value,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressNotLike(String value) {
			addCriterion("SHOP_ENGLISH_ADDRESS not like", value,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressIn(List<String> values) {
			addCriterion("SHOP_ENGLISH_ADDRESS in", values,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressNotIn(List<String> values) {
			addCriterion("SHOP_ENGLISH_ADDRESS not in", values,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressBetween(String value1,
				String value2) {
			addCriterion("SHOP_ENGLISH_ADDRESS between", value1, value2,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopEnglishAddressNotBetween(String value1,
				String value2) {
			addCriterion("SHOP_ENGLISH_ADDRESS not between", value1, value2,
					"shopEnglishAddress");
			return this;
		}

		public Criteria andShopPostcodeIsNull() {
			addCriterion("SHOP_POSTCODE is null");
			return this;
		}

		public Criteria andShopPostcodeIsNotNull() {
			addCriterion("SHOP_POSTCODE is not null");
			return this;
		}

		public Criteria andShopPostcodeEqualTo(String value) {
			addCriterion("SHOP_POSTCODE =", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeNotEqualTo(String value) {
			addCriterion("SHOP_POSTCODE <>", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeGreaterThan(String value) {
			addCriterion("SHOP_POSTCODE >", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_POSTCODE >=", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeLessThan(String value) {
			addCriterion("SHOP_POSTCODE <", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_POSTCODE <=", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeLike(String value) {
			addCriterion("SHOP_POSTCODE like", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeNotLike(String value) {
			addCriterion("SHOP_POSTCODE not like", value, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeIn(List<String> values) {
			addCriterion("SHOP_POSTCODE in", values, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeNotIn(List<String> values) {
			addCriterion("SHOP_POSTCODE not in", values, "shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeBetween(String value1, String value2) {
			addCriterion("SHOP_POSTCODE between", value1, value2,
					"shopPostcode");
			return this;
		}

		public Criteria andShopPostcodeNotBetween(String value1, String value2) {
			addCriterion("SHOP_POSTCODE not between", value1, value2,
					"shopPostcode");
			return this;
		}

		public Criteria andShopTelephoneIsNull() {
			addCriterion("SHOP_TELEPHONE is null");
			return this;
		}

		public Criteria andShopTelephoneIsNotNull() {
			addCriterion("SHOP_TELEPHONE is not null");
			return this;
		}

		public Criteria andShopTelephoneEqualTo(String value) {
			addCriterion("SHOP_TELEPHONE =", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneNotEqualTo(String value) {
			addCriterion("SHOP_TELEPHONE <>", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneGreaterThan(String value) {
			addCriterion("SHOP_TELEPHONE >", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_TELEPHONE >=", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneLessThan(String value) {
			addCriterion("SHOP_TELEPHONE <", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneLessThanOrEqualTo(String value) {
			addCriterion("SHOP_TELEPHONE <=", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneLike(String value) {
			addCriterion("SHOP_TELEPHONE like", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneNotLike(String value) {
			addCriterion("SHOP_TELEPHONE not like", value, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneIn(List<String> values) {
			addCriterion("SHOP_TELEPHONE in", values, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneNotIn(List<String> values) {
			addCriterion("SHOP_TELEPHONE not in", values, "shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneBetween(String value1, String value2) {
			addCriterion("SHOP_TELEPHONE between", value1, value2,
					"shopTelephone");
			return this;
		}

		public Criteria andShopTelephoneNotBetween(String value1, String value2) {
			addCriterion("SHOP_TELEPHONE not between", value1, value2,
					"shopTelephone");
			return this;
		}

		public Criteria andShopFaxIsNull() {
			addCriterion("SHOP_FAX is null");
			return this;
		}

		public Criteria andShopFaxIsNotNull() {
			addCriterion("SHOP_FAX is not null");
			return this;
		}

		public Criteria andShopFaxEqualTo(String value) {
			addCriterion("SHOP_FAX =", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxNotEqualTo(String value) {
			addCriterion("SHOP_FAX <>", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxGreaterThan(String value) {
			addCriterion("SHOP_FAX >", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_FAX >=", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxLessThan(String value) {
			addCriterion("SHOP_FAX <", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxLessThanOrEqualTo(String value) {
			addCriterion("SHOP_FAX <=", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxLike(String value) {
			addCriterion("SHOP_FAX like", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxNotLike(String value) {
			addCriterion("SHOP_FAX not like", value, "shopFax");
			return this;
		}

		public Criteria andShopFaxIn(List<String> values) {
			addCriterion("SHOP_FAX in", values, "shopFax");
			return this;
		}

		public Criteria andShopFaxNotIn(List<String> values) {
			addCriterion("SHOP_FAX not in", values, "shopFax");
			return this;
		}

		public Criteria andShopFaxBetween(String value1, String value2) {
			addCriterion("SHOP_FAX between", value1, value2, "shopFax");
			return this;
		}

		public Criteria andShopFaxNotBetween(String value1, String value2) {
			addCriterion("SHOP_FAX not between", value1, value2, "shopFax");
			return this;
		}

		public Criteria andShopWebsiteIsNull() {
			addCriterion("SHOP_WEBSITE is null");
			return this;
		}

		public Criteria andShopWebsiteIsNotNull() {
			addCriterion("SHOP_WEBSITE is not null");
			return this;
		}

		public Criteria andShopWebsiteEqualTo(String value) {
			addCriterion("SHOP_WEBSITE =", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteNotEqualTo(String value) {
			addCriterion("SHOP_WEBSITE <>", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteGreaterThan(String value) {
			addCriterion("SHOP_WEBSITE >", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_WEBSITE >=", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteLessThan(String value) {
			addCriterion("SHOP_WEBSITE <", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteLessThanOrEqualTo(String value) {
			addCriterion("SHOP_WEBSITE <=", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteLike(String value) {
			addCriterion("SHOP_WEBSITE like", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteNotLike(String value) {
			addCriterion("SHOP_WEBSITE not like", value, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteIn(List<String> values) {
			addCriterion("SHOP_WEBSITE in", values, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteNotIn(List<String> values) {
			addCriterion("SHOP_WEBSITE not in", values, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteBetween(String value1, String value2) {
			addCriterion("SHOP_WEBSITE between", value1, value2, "shopWebsite");
			return this;
		}

		public Criteria andShopWebsiteNotBetween(String value1, String value2) {
			addCriterion("SHOP_WEBSITE not between", value1, value2,
					"shopWebsite");
			return this;
		}

		public Criteria andShopCityIsNull() {
			addCriterion("SHOP_CITY is null");
			return this;
		}

		public Criteria andShopCityIsNotNull() {
			addCriterion("SHOP_CITY is not null");
			return this;
		}

		public Criteria andShopCityEqualTo(String value) {
			addCriterion("SHOP_CITY =", value, "shopCity");
			return this;
		}

		public Criteria andShopCityNotEqualTo(String value) {
			addCriterion("SHOP_CITY <>", value, "shopCity");
			return this;
		}

		public Criteria andShopCityGreaterThan(String value) {
			addCriterion("SHOP_CITY >", value, "shopCity");
			return this;
		}

		public Criteria andShopCityGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_CITY >=", value, "shopCity");
			return this;
		}

		public Criteria andShopCityLessThan(String value) {
			addCriterion("SHOP_CITY <", value, "shopCity");
			return this;
		}

		public Criteria andShopCityLessThanOrEqualTo(String value) {
			addCriterion("SHOP_CITY <=", value, "shopCity");
			return this;
		}

		public Criteria andShopCityLike(String value) {
			addCriterion("SHOP_CITY like", value, "shopCity");
			return this;
		}

		public Criteria andShopCityNotLike(String value) {
			addCriterion("SHOP_CITY not like", value, "shopCity");
			return this;
		}

		public Criteria andShopCityIn(List<String> values) {
			addCriterion("SHOP_CITY in", values, "shopCity");
			return this;
		}

		public Criteria andShopCityNotIn(List<String> values) {
			addCriterion("SHOP_CITY not in", values, "shopCity");
			return this;
		}

		public Criteria andShopCityBetween(String value1, String value2) {
			addCriterion("SHOP_CITY between", value1, value2, "shopCity");
			return this;
		}

		public Criteria andShopCityNotBetween(String value1, String value2) {
			addCriterion("SHOP_CITY not between", value1, value2, "shopCity");
			return this;
		}

		public Criteria andBusinessAreaIsNull() {
			addCriterion("BUSINESS_AREA is null");
			return this;
		}

		public Criteria andBusinessAreaIsNotNull() {
			addCriterion("BUSINESS_AREA is not null");
			return this;
		}

		public Criteria andBusinessAreaEqualTo(String value) {
			addCriterion("BUSINESS_AREA =", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaNotEqualTo(String value) {
			addCriterion("BUSINESS_AREA <>", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaGreaterThan(String value) {
			addCriterion("BUSINESS_AREA >", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaGreaterThanOrEqualTo(String value) {
			addCriterion("BUSINESS_AREA >=", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaLessThan(String value) {
			addCriterion("BUSINESS_AREA <", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaLessThanOrEqualTo(String value) {
			addCriterion("BUSINESS_AREA <=", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaLike(String value) {
			addCriterion("BUSINESS_AREA like", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaNotLike(String value) {
			addCriterion("BUSINESS_AREA not like", value, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaIn(List<String> values) {
			addCriterion("BUSINESS_AREA in", values, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaNotIn(List<String> values) {
			addCriterion("BUSINESS_AREA not in", values, "businessArea");
			return this;
		}

		public Criteria andBusinessAreaBetween(String value1, String value2) {
			addCriterion("BUSINESS_AREA between", value1, value2,
					"businessArea");
			return this;
		}

		public Criteria andBusinessAreaNotBetween(String value1, String value2) {
			addCriterion("BUSINESS_AREA not between", value1, value2,
					"businessArea");
			return this;
		}

		public Criteria andShopCategoryIsNull() {
			addCriterion("SHOP_CATEGORY is null");
			return this;
		}

		public Criteria andShopCategoryIsNotNull() {
			addCriterion("SHOP_CATEGORY is not null");
			return this;
		}

		public Criteria andShopCategoryEqualTo(String value) {
			addCriterion("SHOP_CATEGORY =", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryNotEqualTo(String value) {
			addCriterion("SHOP_CATEGORY <>", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryGreaterThan(String value) {
			addCriterion("SHOP_CATEGORY >", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_CATEGORY >=", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryLessThan(String value) {
			addCriterion("SHOP_CATEGORY <", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryLessThanOrEqualTo(String value) {
			addCriterion("SHOP_CATEGORY <=", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryLike(String value) {
			addCriterion("SHOP_CATEGORY like", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryNotLike(String value) {
			addCriterion("SHOP_CATEGORY not like", value, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryIn(List<String> values) {
			addCriterion("SHOP_CATEGORY in", values, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryNotIn(List<String> values) {
			addCriterion("SHOP_CATEGORY not in", values, "shopCategory");
			return this;
		}

		public Criteria andShopCategoryBetween(String value1, String value2) {
			addCriterion("SHOP_CATEGORY between", value1, value2,
					"shopCategory");
			return this;
		}

		public Criteria andShopCategoryNotBetween(String value1, String value2) {
			addCriterion("SHOP_CATEGORY not between", value1, value2,
					"shopCategory");
			return this;
		}

		public Criteria andShopTypeIsNull() {
			addCriterion("SHOP_TYPE is null");
			return this;
		}

		public Criteria andShopTypeIsNotNull() {
			addCriterion("SHOP_TYPE is not null");
			return this;
		}

		public Criteria andShopTypeEqualTo(String value) {
			addCriterion("SHOP_TYPE =", value, "shopType");
			return this;
		}

		public Criteria andShopTypeNotEqualTo(String value) {
			addCriterion("SHOP_TYPE <>", value, "shopType");
			return this;
		}

		public Criteria andShopTypeGreaterThan(String value) {
			addCriterion("SHOP_TYPE >", value, "shopType");
			return this;
		}

		public Criteria andShopTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_TYPE >=", value, "shopType");
			return this;
		}

		public Criteria andShopTypeLessThan(String value) {
			addCriterion("SHOP_TYPE <", value, "shopType");
			return this;
		}

		public Criteria andShopTypeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_TYPE <=", value, "shopType");
			return this;
		}

		public Criteria andShopTypeLike(String value) {
			addCriterion("SHOP_TYPE like", value, "shopType");
			return this;
		}

		public Criteria andShopTypeNotLike(String value) {
			addCriterion("SHOP_TYPE not like", value, "shopType");
			return this;
		}

		public Criteria andShopTypeIn(List<String> values) {
			addCriterion("SHOP_TYPE in", values, "shopType");
			return this;
		}

		public Criteria andShopTypeNotIn(List<String> values) {
			addCriterion("SHOP_TYPE not in", values, "shopType");
			return this;
		}

		public Criteria andShopTypeBetween(String value1, String value2) {
			addCriterion("SHOP_TYPE between", value1, value2, "shopType");
			return this;
		}

		public Criteria andShopTypeNotBetween(String value1, String value2) {
			addCriterion("SHOP_TYPE not between", value1, value2, "shopType");
			return this;
		}

		public Criteria andShopRankIsNull() {
			addCriterion("SHOP_RANK is null");
			return this;
		}

		public Criteria andShopRankIsNotNull() {
			addCriterion("SHOP_RANK is not null");
			return this;
		}

		public Criteria andShopRankEqualTo(String value) {
			addCriterion("SHOP_RANK =", value, "shopRank");
			return this;
		}

		public Criteria andShopRankNotEqualTo(String value) {
			addCriterion("SHOP_RANK <>", value, "shopRank");
			return this;
		}

		public Criteria andShopRankGreaterThan(String value) {
			addCriterion("SHOP_RANK >", value, "shopRank");
			return this;
		}

		public Criteria andShopRankGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_RANK >=", value, "shopRank");
			return this;
		}

		public Criteria andShopRankLessThan(String value) {
			addCriterion("SHOP_RANK <", value, "shopRank");
			return this;
		}

		public Criteria andShopRankLessThanOrEqualTo(String value) {
			addCriterion("SHOP_RANK <=", value, "shopRank");
			return this;
		}

		public Criteria andShopRankLike(String value) {
			addCriterion("SHOP_RANK like", value, "shopRank");
			return this;
		}

		public Criteria andShopRankNotLike(String value) {
			addCriterion("SHOP_RANK not like", value, "shopRank");
			return this;
		}

		public Criteria andShopRankIn(List<String> values) {
			addCriterion("SHOP_RANK in", values, "shopRank");
			return this;
		}

		public Criteria andShopRankNotIn(List<String> values) {
			addCriterion("SHOP_RANK not in", values, "shopRank");
			return this;
		}

		public Criteria andShopRankBetween(String value1, String value2) {
			addCriterion("SHOP_RANK between", value1, value2, "shopRank");
			return this;
		}

		public Criteria andShopRankNotBetween(String value1, String value2) {
			addCriterion("SHOP_RANK not between", value1, value2, "shopRank");
			return this;
		}

		public Criteria andPaymentTypeIsNull() {
			addCriterion("PAYMENT_TYPE is null");
			return this;
		}

		public Criteria andPaymentTypeIsNotNull() {
			addCriterion("PAYMENT_TYPE is not null");
			return this;
		}

		public Criteria andPaymentTypeEqualTo(String value) {
			addCriterion("PAYMENT_TYPE =", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeNotEqualTo(String value) {
			addCriterion("PAYMENT_TYPE <>", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeGreaterThan(String value) {
			addCriterion("PAYMENT_TYPE >", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeGreaterThanOrEqualTo(String value) {
			addCriterion("PAYMENT_TYPE >=", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeLessThan(String value) {
			addCriterion("PAYMENT_TYPE <", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeLessThanOrEqualTo(String value) {
			addCriterion("PAYMENT_TYPE <=", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeLike(String value) {
			addCriterion("PAYMENT_TYPE like", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeNotLike(String value) {
			addCriterion("PAYMENT_TYPE not like", value, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeIn(List<String> values) {
			addCriterion("PAYMENT_TYPE in", values, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeNotIn(List<String> values) {
			addCriterion("PAYMENT_TYPE not in", values, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeBetween(String value1, String value2) {
			addCriterion("PAYMENT_TYPE between", value1, value2, "paymentType");
			return this;
		}

		public Criteria andPaymentTypeNotBetween(String value1, String value2) {
			addCriterion("PAYMENT_TYPE not between", value1, value2,
					"paymentType");
			return this;
		}

		public Criteria andShopLongitudeIsNull() {
			addCriterion("SHOP_LONGITUDE is null");
			return this;
		}

		public Criteria andShopLongitudeIsNotNull() {
			addCriterion("SHOP_LONGITUDE is not null");
			return this;
		}

		public Criteria andShopLongitudeEqualTo(String value) {
			addCriterion("SHOP_LONGITUDE =", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeNotEqualTo(String value) {
			addCriterion("SHOP_LONGITUDE <>", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeGreaterThan(String value) {
			addCriterion("SHOP_LONGITUDE >", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_LONGITUDE >=", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeLessThan(String value) {
			addCriterion("SHOP_LONGITUDE <", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_LONGITUDE <=", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeLike(String value) {
			addCriterion("SHOP_LONGITUDE like", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeNotLike(String value) {
			addCriterion("SHOP_LONGITUDE not like", value, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeIn(List<String> values) {
			addCriterion("SHOP_LONGITUDE in", values, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeNotIn(List<String> values) {
			addCriterion("SHOP_LONGITUDE not in", values, "shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeBetween(String value1, String value2) {
			addCriterion("SHOP_LONGITUDE between", value1, value2,
					"shopLongitude");
			return this;
		}

		public Criteria andShopLongitudeNotBetween(String value1, String value2) {
			addCriterion("SHOP_LONGITUDE not between", value1, value2,
					"shopLongitude");
			return this;
		}

		public Criteria andShopLatitudeIsNull() {
			addCriterion("SHOP_LATITUDE is null");
			return this;
		}

		public Criteria andShopLatitudeIsNotNull() {
			addCriterion("SHOP_LATITUDE is not null");
			return this;
		}

		public Criteria andShopLatitudeEqualTo(String value) {
			addCriterion("SHOP_LATITUDE =", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeNotEqualTo(String value) {
			addCriterion("SHOP_LATITUDE <>", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeGreaterThan(String value) {
			addCriterion("SHOP_LATITUDE >", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_LATITUDE >=", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeLessThan(String value) {
			addCriterion("SHOP_LATITUDE <", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeLessThanOrEqualTo(String value) {
			addCriterion("SHOP_LATITUDE <=", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeLike(String value) {
			addCriterion("SHOP_LATITUDE like", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeNotLike(String value) {
			addCriterion("SHOP_LATITUDE not like", value, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeIn(List<String> values) {
			addCriterion("SHOP_LATITUDE in", values, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeNotIn(List<String> values) {
			addCriterion("SHOP_LATITUDE not in", values, "shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeBetween(String value1, String value2) {
			addCriterion("SHOP_LATITUDE between", value1, value2,
					"shopLatitude");
			return this;
		}

		public Criteria andShopLatitudeNotBetween(String value1, String value2) {
			addCriterion("SHOP_LATITUDE not between", value1, value2,
					"shopLatitude");
			return this;
		}

		public Criteria andShopNotesIsNull() {
			addCriterion("SHOP_NOTES is null");
			return this;
		}

		public Criteria andShopNotesIsNotNull() {
			addCriterion("SHOP_NOTES is not null");
			return this;
		}

		public Criteria andShopNotesEqualTo(String value) {
			addCriterion("SHOP_NOTES =", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesNotEqualTo(String value) {
			addCriterion("SHOP_NOTES <>", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesGreaterThan(String value) {
			addCriterion("SHOP_NOTES >", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_NOTES >=", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesLessThan(String value) {
			addCriterion("SHOP_NOTES <", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesLessThanOrEqualTo(String value) {
			addCriterion("SHOP_NOTES <=", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesLike(String value) {
			addCriterion("SHOP_NOTES like", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesNotLike(String value) {
			addCriterion("SHOP_NOTES not like", value, "shopNotes");
			return this;
		}

		public Criteria andShopNotesIn(List<String> values) {
			addCriterion("SHOP_NOTES in", values, "shopNotes");
			return this;
		}

		public Criteria andShopNotesNotIn(List<String> values) {
			addCriterion("SHOP_NOTES not in", values, "shopNotes");
			return this;
		}

		public Criteria andShopNotesBetween(String value1, String value2) {
			addCriterion("SHOP_NOTES between", value1, value2, "shopNotes");
			return this;
		}

		public Criteria andShopNotesNotBetween(String value1, String value2) {
			addCriterion("SHOP_NOTES not between", value1, value2, "shopNotes");
			return this;
		}

		public Criteria andEnglishNotesIsNull() {
			addCriterion("ENGLISH_NOTES is null");
			return this;
		}

		public Criteria andEnglishNotesIsNotNull() {
			addCriterion("ENGLISH_NOTES is not null");
			return this;
		}

		public Criteria andEnglishNotesEqualTo(String value) {
			addCriterion("ENGLISH_NOTES =", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesNotEqualTo(String value) {
			addCriterion("ENGLISH_NOTES <>", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesGreaterThan(String value) {
			addCriterion("ENGLISH_NOTES >", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesGreaterThanOrEqualTo(String value) {
			addCriterion("ENGLISH_NOTES >=", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesLessThan(String value) {
			addCriterion("ENGLISH_NOTES <", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesLessThanOrEqualTo(String value) {
			addCriterion("ENGLISH_NOTES <=", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesLike(String value) {
			addCriterion("ENGLISH_NOTES like", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesNotLike(String value) {
			addCriterion("ENGLISH_NOTES not like", value, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesIn(List<String> values) {
			addCriterion("ENGLISH_NOTES in", values, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesNotIn(List<String> values) {
			addCriterion("ENGLISH_NOTES not in", values, "englishNotes");
			return this;
		}

		public Criteria andEnglishNotesBetween(String value1, String value2) {
			addCriterion("ENGLISH_NOTES between", value1, value2,
					"englishNotes");
			return this;
		}

		public Criteria andEnglishNotesNotBetween(String value1, String value2) {
			addCriterion("ENGLISH_NOTES not between", value1, value2,
					"englishNotes");
			return this;
		}

		public Criteria andDefaultFlagIsNull() {
			addCriterion("DEFAULT_FLAG is null");
			return this;
		}

		public Criteria andDefaultFlagIsNotNull() {
			addCriterion("DEFAULT_FLAG is not null");
			return this;
		}

		public Criteria andDefaultFlagEqualTo(String value) {
			addCriterion("DEFAULT_FLAG =", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagNotEqualTo(String value) {
			addCriterion("DEFAULT_FLAG <>", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagGreaterThan(String value) {
			addCriterion("DEFAULT_FLAG >", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagGreaterThanOrEqualTo(String value) {
			addCriterion("DEFAULT_FLAG >=", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagLessThan(String value) {
			addCriterion("DEFAULT_FLAG <", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagLessThanOrEqualTo(String value) {
			addCriterion("DEFAULT_FLAG <=", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagLike(String value) {
			addCriterion("DEFAULT_FLAG like", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagNotLike(String value) {
			addCriterion("DEFAULT_FLAG not like", value, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagIn(List<String> values) {
			addCriterion("DEFAULT_FLAG in", values, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagNotIn(List<String> values) {
			addCriterion("DEFAULT_FLAG not in", values, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagBetween(String value1, String value2) {
			addCriterion("DEFAULT_FLAG between", value1, value2, "defaultFlag");
			return this;
		}

		public Criteria andDefaultFlagNotBetween(String value1, String value2) {
			addCriterion("DEFAULT_FLAG not between", value1, value2,
					"defaultFlag");
			return this;
		}

		public Criteria andShopStateIsNull() {
			addCriterion("SHOP_STATE is null");
			return this;
		}

		public Criteria andShopStateIsNotNull() {
			addCriterion("SHOP_STATE is not null");
			return this;
		}

		public Criteria andShopStateEqualTo(String value) {
			addCriterion("SHOP_STATE =", value, "shopState");
			return this;
		}

		public Criteria andShopStateNotEqualTo(String value) {
			addCriterion("SHOP_STATE <>", value, "shopState");
			return this;
		}

		public Criteria andShopStateGreaterThan(String value) {
			addCriterion("SHOP_STATE >", value, "shopState");
			return this;
		}

		public Criteria andShopStateGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_STATE >=", value, "shopState");
			return this;
		}

		public Criteria andShopStateLessThan(String value) {
			addCriterion("SHOP_STATE <", value, "shopState");
			return this;
		}

		public Criteria andShopStateLessThanOrEqualTo(String value) {
			addCriterion("SHOP_STATE <=", value, "shopState");
			return this;
		}

		public Criteria andShopStateLike(String value) {
			addCriterion("SHOP_STATE like", value, "shopState");
			return this;
		}

		public Criteria andShopStateNotLike(String value) {
			addCriterion("SHOP_STATE not like", value, "shopState");
			return this;
		}

		public Criteria andShopStateIn(List<String> values) {
			addCriterion("SHOP_STATE in", values, "shopState");
			return this;
		}

		public Criteria andShopStateNotIn(List<String> values) {
			addCriterion("SHOP_STATE not in", values, "shopState");
			return this;
		}

		public Criteria andShopStateBetween(String value1, String value2) {
			addCriterion("SHOP_STATE between", value1, value2, "shopState");
			return this;
		}

		public Criteria andShopStateNotBetween(String value1, String value2) {
			addCriterion("SHOP_STATE not between", value1, value2, "shopState");
			return this;
		}

		public Criteria andJoinDateIsNull() {
			addCriterion("JOIN_DATE is null");
			return this;
		}

		public Criteria andJoinDateIsNotNull() {
			addCriterion("JOIN_DATE is not null");
			return this;
		}

		public Criteria andJoinDateEqualTo(String value) {
			addCriterion("JOIN_DATE =", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateNotEqualTo(String value) {
			addCriterion("JOIN_DATE <>", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateGreaterThan(String value) {
			addCriterion("JOIN_DATE >", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateGreaterThanOrEqualTo(String value) {
			addCriterion("JOIN_DATE >=", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateLessThan(String value) {
			addCriterion("JOIN_DATE <", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateLessThanOrEqualTo(String value) {
			addCriterion("JOIN_DATE <=", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateLike(String value) {
			addCriterion("JOIN_DATE like", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateNotLike(String value) {
			addCriterion("JOIN_DATE not like", value, "joinDate");
			return this;
		}

		public Criteria andJoinDateIn(List<String> values) {
			addCriterion("JOIN_DATE in", values, "joinDate");
			return this;
		}

		public Criteria andJoinDateNotIn(List<String> values) {
			addCriterion("JOIN_DATE not in", values, "joinDate");
			return this;
		}

		public Criteria andJoinDateBetween(String value1, String value2) {
			addCriterion("JOIN_DATE between", value1, value2, "joinDate");
			return this;
		}

		public Criteria andJoinDateNotBetween(String value1, String value2) {
			addCriterion("JOIN_DATE not between", value1, value2, "joinDate");
			return this;
		}

		public Criteria andShopCommentIsNull() {
			addCriterion("SHOP_COMMENT is null");
			return this;
		}

		public Criteria andShopCommentIsNotNull() {
			addCriterion("SHOP_COMMENT is not null");
			return this;
		}

		public Criteria andShopCommentEqualTo(String value) {
			addCriterion("SHOP_COMMENT =", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentNotEqualTo(String value) {
			addCriterion("SHOP_COMMENT <>", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentGreaterThan(String value) {
			addCriterion("SHOP_COMMENT >", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_COMMENT >=", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentLessThan(String value) {
			addCriterion("SHOP_COMMENT <", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentLessThanOrEqualTo(String value) {
			addCriterion("SHOP_COMMENT <=", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentLike(String value) {
			addCriterion("SHOP_COMMENT like", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentNotLike(String value) {
			addCriterion("SHOP_COMMENT not like", value, "shopComment");
			return this;
		}

		public Criteria andShopCommentIn(List<String> values) {
			addCriterion("SHOP_COMMENT in", values, "shopComment");
			return this;
		}

		public Criteria andShopCommentNotIn(List<String> values) {
			addCriterion("SHOP_COMMENT not in", values, "shopComment");
			return this;
		}

		public Criteria andShopCommentBetween(String value1, String value2) {
			addCriterion("SHOP_COMMENT between", value1, value2, "shopComment");
			return this;
		}

		public Criteria andShopCommentNotBetween(String value1, String value2) {
			addCriterion("SHOP_COMMENT not between", value1, value2,
					"shopComment");
			return this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2,
					"modifyUser");
			return this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return this;
		}

		public Criteria andModifyTimeEqualTo(String value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotEqualTo(String value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThan(String value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThan(String value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLike(String value) {
			addCriterion("MODIFY_TIME like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotLike(String value) {
			addCriterion("MODIFY_TIME not like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeIn(List<String> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotIn(List<String> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME not between", value1, value2,
					"modifyTime");
			return this;
		}

		public Criteria andDataStateIsNull() {
			addCriterion("DATA_STATE is null");
			return this;
		}

		public Criteria andDataStateIsNotNull() {
			addCriterion("DATA_STATE is not null");
			return this;
		}

		public Criteria andDataStateEqualTo(String value) {
			addCriterion("DATA_STATE =", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotEqualTo(String value) {
			addCriterion("DATA_STATE <>", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThan(String value) {
			addCriterion("DATA_STATE >", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_STATE >=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThan(String value) {
			addCriterion("DATA_STATE <", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThanOrEqualTo(String value) {
			addCriterion("DATA_STATE <=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLike(String value) {
			addCriterion("DATA_STATE like", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotLike(String value) {
			addCriterion("DATA_STATE not like", value, "dataState");
			return this;
		}

		public Criteria andDataStateIn(List<String> values) {
			addCriterion("DATA_STATE in", values, "dataState");
			return this;
		}

		public Criteria andDataStateNotIn(List<String> values) {
			addCriterion("DATA_STATE not in", values, "dataState");
			return this;
		}

		public Criteria andDataStateBetween(String value1, String value2) {
			addCriterion("DATA_STATE between", value1, value2, "dataState");
			return this;
		}

		public Criteria andDataStateNotBetween(String value1, String value2) {
			addCriterion("DATA_STATE not between", value1, value2, "dataState");
			return this;
		}
	}
}