package com.suning.svc.ibatis.dao;

import java.util.List;

import com.suning.svc.ibatis.model.ConsumeOrder;
import com.suning.svc.ibatis.model.ConsumeOrderExample;

public interface ConsumeOrderDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    void insert(ConsumeOrder record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int updateByPrimaryKey(ConsumeOrder record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int updateByPrimaryKeySelective(ConsumeOrder record);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    List selectByExample(ConsumeOrderExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    ConsumeOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int deleteByExample(ConsumeOrderExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int countByExample(ConsumeOrderExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int updateByExampleSelective(ConsumeOrder record, ConsumeOrderExample example);

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_CONSUME_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:17:09 CST 2013
     */
    int updateByExample(ConsumeOrder record, ConsumeOrderExample example);
}