package com.suning.svc.ibatis.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.suning.svc.ibatis.model.DepositOrder;
import com.suning.svc.ibatis.model.DepositOrderExample;

public class DepositOrderDAOImpl extends SqlMapClientDaoSupport implements DepositOrderDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public DepositOrderDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public void insert(DepositOrder record) {
        getSqlMapClientTemplate().insert("CP_DEPOSIT_ORDER.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int updateByPrimaryKey(DepositOrder record) {
        int rows = getSqlMapClientTemplate().update("CP_DEPOSIT_ORDER.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int updateByPrimaryKeySelective(DepositOrder record) {
        int rows = getSqlMapClientTemplate().update("CP_DEPOSIT_ORDER.abatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public List selectByExample(DepositOrderExample example) {
        List list = getSqlMapClientTemplate().queryForList("CP_DEPOSIT_ORDER.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public DepositOrder selectByPrimaryKey(Long id) {
        DepositOrder key = new DepositOrder();
        key.setId(id);
        DepositOrder record = (DepositOrder) getSqlMapClientTemplate().queryForObject(
                "CP_DEPOSIT_ORDER.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int deleteByExample(DepositOrderExample example) {
        int rows = getSqlMapClientTemplate().delete("CP_DEPOSIT_ORDER.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        DepositOrder key = new DepositOrder();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("CP_DEPOSIT_ORDER.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int countByExample(DepositOrderExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "CP_DEPOSIT_ORDER.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int updateByExampleSelective(DepositOrder record, DepositOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CP_DEPOSIT_ORDER.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    public int updateByExample(DepositOrder record, DepositOrderExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CP_DEPOSIT_ORDER.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table CP_DEPOSIT_ORDER
     * 
     * @abatorgenerated Mon Nov 04 20:16:05 CST 2013
     */
    private static class UpdateByExampleParms extends DepositOrderExample {
        private Object record;

        public UpdateByExampleParms(Object record, DepositOrderExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}