package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.BlackList;
import com.huateng.framework.ibatis.model.BlackListExample;
import java.util.List;

public interface BlackListDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    void insert(BlackList record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int updateByPrimaryKey(BlackList record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int updateByPrimaryKeySelective(BlackList record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    List<BlackList> selectByExample(BlackListExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    BlackList selectByPrimaryKey(String cardNo);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int deleteByExample(BlackListExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int deleteByPrimaryKey(String cardNo);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int countByExample(BlackListExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int updateByExampleSelective(BlackList record, BlackListExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table ISMNGDB_1_0_7_1.TB_BLACKLIST
     *
     * @abatorgenerated Tue Nov 06 19:18:47 CST 2012
     */
    int updateByExample(BlackList record, BlackListExample example);
}