package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.CardholderEnterPrise;
import com.huateng.framework.ibatis.model.CardholderEnterPriseExample;
import com.huateng.framework.ibatis.model.CardholderEnterPriseKey;
import java.util.List;

public interface CardholderEnterPriseDAO {

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int countByExample(CardholderEnterPriseExample example);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int deleteByExample(CardholderEnterPriseExample example);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int deleteByPrimaryKey(CardholderEnterPriseKey key);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    void insert(CardholderEnterPrise record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    void insertSelective(CardholderEnterPrise record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    List selectByExample(CardholderEnterPriseExample example);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    CardholderEnterPrise selectByPrimaryKey(CardholderEnterPriseKey key);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int updateByExampleSelective(CardholderEnterPrise record, CardholderEnterPriseExample example);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int updateByExample(CardholderEnterPrise record, CardholderEnterPriseExample example);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int updateByPrimaryKeySelective(CardholderEnterPrise record);

    /**
     * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_CARDHOLDER_ENTERPRISE
     * @ibatorgenerated  Thu Aug 03 18:20:15 CST 2017
     */
    int updateByPrimaryKey(CardholderEnterPrise record);
}