package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.CardholderPersonal;
import com.huateng.framework.ibatis.model.CardholderPersonalExample;
import com.huateng.framework.ibatis.model.CardholderPersonalKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CardholderPersonalDAOImpl extends SqlMapClientDaoSupport implements CardholderPersonalDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public CardholderPersonalDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int countByExample(CardholderPersonalExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_CARDHOLDER_PERSONAL.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int deleteByExample(CardholderPersonalExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_CARDHOLDER_PERSONAL.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int deleteByPrimaryKey(CardholderPersonalKey key) {
        int rows = getSqlMapClientTemplate().delete("TB_CARDHOLDER_PERSONAL.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public void insert(CardholderPersonal record) {
        getSqlMapClientTemplate().insert("TB_CARDHOLDER_PERSONAL.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public void insertSelective(CardholderPersonal record) {
        getSqlMapClientTemplate().insert("TB_CARDHOLDER_PERSONAL.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public List selectByExample(CardholderPersonalExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_CARDHOLDER_PERSONAL.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public CardholderPersonal selectByPrimaryKey(CardholderPersonalKey key) {
        CardholderPersonal record = (CardholderPersonal) getSqlMapClientTemplate().queryForObject("TB_CARDHOLDER_PERSONAL.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int updateByExampleSelective(CardholderPersonal record, CardholderPersonalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CARDHOLDER_PERSONAL.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int updateByExample(CardholderPersonal record, CardholderPersonalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CARDHOLDER_PERSONAL.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int updateByPrimaryKeySelective(CardholderPersonal record) {
        int rows = getSqlMapClientTemplate().update("TB_CARDHOLDER_PERSONAL.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    public int updateByPrimaryKey(CardholderPersonal record) {
        int rows = getSqlMapClientTemplate().update("TB_CARDHOLDER_PERSONAL.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_CARDHOLDER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:01:39 CST 2017
     */
    private static class UpdateByExampleParms extends CardholderPersonalExample {
        private Object record;

        public UpdateByExampleParms(Object record, CardholderPersonalExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}