package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.CheckPeopleInfo;
import com.huateng.framework.ibatis.model.CheckPeopleInfoExample;
import com.huateng.framework.ibatis.model.CheckPeopleInfoKey;

import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CheckPeopleInfoDAOImpl extends SqlMapClientDaoSupport implements CheckPeopleInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public CheckPeopleInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int countByExample(CheckPeopleInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_CHECK_PEOPLE_INFO.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int deleteByExample(CheckPeopleInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_CHECK_PEOPLE_INFO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int deleteByPrimaryKey(CheckPeopleInfoKey key) {
        int rows = getSqlMapClientTemplate().delete("TB_CHECK_PEOPLE_INFO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void insert(CheckPeopleInfo record) {
        getSqlMapClientTemplate().insert("TB_CHECK_PEOPLE_INFO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void insertSelective(CheckPeopleInfo record) {
        getSqlMapClientTemplate().insert("TB_CHECK_PEOPLE_INFO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public List selectByExample(CheckPeopleInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_CHECK_PEOPLE_INFO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public CheckPeopleInfo selectByPrimaryKey(CheckPeopleInfoKey key) {
        CheckPeopleInfo record = (CheckPeopleInfo) getSqlMapClientTemplate().queryForObject("TB_CHECK_PEOPLE_INFO.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByExampleSelective(CheckPeopleInfo record, CheckPeopleInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CHECK_PEOPLE_INFO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByExample(CheckPeopleInfo record, CheckPeopleInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CHECK_PEOPLE_INFO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByPrimaryKeySelective(CheckPeopleInfo record) {
        int rows = getSqlMapClientTemplate().update("TB_CHECK_PEOPLE_INFO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByPrimaryKey(CheckPeopleInfo record) {
        int rows = getSqlMapClientTemplate().update("TB_CHECK_PEOPLE_INFO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_CHECK_PEOPLE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    private static class UpdateByExampleParms extends CheckPeopleInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, CheckPeopleInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    public int updateByIdNo(Map<String, Object> map) {
		int rows = getSqlMapClientTemplate().update(
				"TB_CHECK_PEOPLE_INFO.updateByIdNo",
				map);
		return rows;
	}
}