package com.huateng.framework.ibatis.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.allinfinance.univer.seller.cardholder.dto.CompanyInfoDTO;
import com.huateng.framework.ibatis.model.CompanyInfo;
import com.huateng.framework.ibatis.model.CompanyInfoExample;
import com.huateng.framework.ibatis.model.CompanyInfoKey;

public class CompanyInfoDAOImpl extends SqlMapClientDaoSupport implements CompanyInfoDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public CompanyInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int countByExample(CompanyInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject("TB_COMPANY_INFO.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int deleteByExample(CompanyInfoExample example) {
		int rows = getSqlMapClientTemplate().delete("TB_COMPANY_INFO.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int deleteByPrimaryKey(CompanyInfoKey key) {
		int rows = getSqlMapClientTemplate().delete("TB_COMPANY_INFO.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public void insert(CompanyInfo record) {
		getSqlMapClientTemplate().insert("TB_COMPANY_INFO.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public void insertSelective(CompanyInfo record) {
		getSqlMapClientTemplate().insert("TB_COMPANY_INFO.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public List selectByExample(CompanyInfoExample example) {
		List list = getSqlMapClientTemplate().queryForList("TB_COMPANY_INFO.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public CompanyInfo selectByPrimaryKey(CompanyInfoKey key) {
		CompanyInfo record = (CompanyInfo) getSqlMapClientTemplate()
				.queryForObject("TB_COMPANY_INFO.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int updateByExampleSelective(CompanyInfo record, CompanyInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_COMPANY_INFO.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int updateByExample(CompanyInfo record, CompanyInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("TB_COMPANY_INFO.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int updateByPrimaryKeySelective(CompanyInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_COMPANY_INFO.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	public int updateByPrimaryKey(CompanyInfo record) {
		int rows = getSqlMapClientTemplate().update("TB_COMPANY_INFO.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table TB_COMPANY_INFO
	 * @ibatorgenerated  Thu Aug 31 13:29:40 CST 2017
	 */
	private static class UpdateByExampleParms extends CompanyInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, CompanyInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	/**
	 * This mothod select enterprise cardholder by cardholder ID;
	 */
    @Override
	@SuppressWarnings("unchecked")
    public List<CompanyInfoDTO> selectByCusCardholderIdNo(CompanyInfoDTO companyInfoDTO){
            List<CompanyInfoDTO> resultCardholder = this.getSqlMapClientTemplate().
                    queryForList("TB_COMPANY_INFO.selectByCusCardholderIdNo", companyInfoDTO);   
            return resultCardholder;
    }

    /**
	 * This mothed judge if the id is used by other cardholder.
	 */
    @Override
	@SuppressWarnings("unchecked")
    public List<CompanyInfoDTO> selectOtherCusCardholderByIdNo(CompanyInfoDTO companyInfoDTO) {
            List<CompanyInfoDTO> resultCardholder = this.getSqlMapClientTemplate().
                queryForList("TB_COMPANY_INFO.selectOtherCusCardholderByIdNo", companyInfoDTO);
            return resultCardholder;
    }
}