package com.huateng.framework.ibatis.dao;

import com.allinfinance.univer.consumer.merchant.dto.MerchantDTO;
import com.huateng.framework.ibatis.model.Consumer;
import com.huateng.framework.ibatis.model.ConsumerExample;
import com.huateng.framework.ibatis.model.ConsumerKey;

import java.util.List;

public interface ConsumerDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	void insert(Consumer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int updateByPrimaryKey(Consumer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int updateByPrimaryKeySelective(Consumer record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	List<Consumer> selectByExample(ConsumerExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	Consumer selectByPrimaryKey(ConsumerKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int deleteByExample(ConsumerExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int deleteByPrimaryKey(ConsumerKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int countByExample(ConsumerExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int updateByExampleSelective(Consumer record, ConsumerExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CONSUMER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	int updateByExample(Consumer record, ConsumerExample example);

	public List<MerchantDTO> selectMerchantByconsumer(String consumerId);
}