package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.DictType;
import com.huateng.framework.ibatis.model.DictTypeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DictTypeDAOImpl extends SqlMapClientDaoSupport implements
		DictTypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public DictTypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public void insert(DictType record) {
		getSqlMapClientTemplate().insert("TB_DICT_TYPE.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int updateByPrimaryKey(DictType record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_DICT_TYPE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int updateByPrimaryKeySelective(DictType record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_DICT_TYPE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<DictType> selectByExample(DictTypeExample example) {
		List<DictType> list = (List<DictType>) getSqlMapClientTemplate()
				.queryForList("TB_DICT_TYPE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public DictType selectByPrimaryKey(String dictTypeCode) {
		DictType key = new DictType();
		key.setDictTypeCode(dictTypeCode);
		DictType record = (DictType) getSqlMapClientTemplate().queryForObject(
				"TB_DICT_TYPE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int deleteByExample(DictTypeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_DICT_TYPE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int deleteByPrimaryKey(String dictTypeCode) {
		DictType key = new DictType();
		key.setDictTypeCode(dictTypeCode);
		int rows = getSqlMapClientTemplate().delete(
				"TB_DICT_TYPE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int countByExample(DictTypeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_DICT_TYPE.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int updateByExampleSelective(DictType record, DictTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_DICT_TYPE.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public int updateByExample(DictType record, DictTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_DICT_TYPE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	private static class UpdateByExampleParms extends DictTypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, DictTypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}