package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.DictInfo;
import com.huateng.framework.ibatis.model.DictInfoExample;
import java.util.List;

public interface DictInfoDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	void insert(DictInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int updateByPrimaryKey(DictInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int updateByPrimaryKeySelective(DictInfo record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	List<DictInfo> selectByExample(DictInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	DictInfo selectByPrimaryKey(String dictId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int deleteByExample(DictInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int deleteByPrimaryKey(String dictId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int countByExample(DictInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int updateByExampleSelective(DictInfo record, DictInfoExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_DICT_INFO
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:36 CST 2010
	 */
	int updateByExample(DictInfo record, DictInfoExample example);
}