package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.EntityDictType;
import com.huateng.framework.ibatis.model.EntityDictTypeExample;
import com.huateng.framework.ibatis.model.EntityDictTypeKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EntityDictTypeDAOImpl extends SqlMapClientDaoSupport implements
		EntityDictTypeDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public EntityDictTypeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public void insert(EntityDictType record) {
		getSqlMapClientTemplate().insert(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int updateByPrimaryKey(EntityDictType record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int updateByPrimaryKeySelective(EntityDictType record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_DICT_TYPE.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EntityDictType> selectByExample(EntityDictTypeExample example) {
		List<EntityDictType> list = (List<EntityDictType>) getSqlMapClientTemplate()
				.queryForList(
						"TB_ENTITY_DICT_TYPE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public EntityDictType selectByPrimaryKey(EntityDictTypeKey key) {
		EntityDictType record = (EntityDictType) getSqlMapClientTemplate()
				.queryForObject(
						"TB_ENTITY_DICT_TYPE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int deleteByExample(EntityDictTypeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int deleteByPrimaryKey(EntityDictTypeKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int countByExample(EntityDictTypeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int updateByExampleSelective(EntityDictType record,
			EntityDictTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	public int updateByExample(EntityDictType record,
			EntityDictTypeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_DICT_TYPE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ENTITY_DICT_TYPE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:42 CST 2010
	 */
	private static class UpdateByExampleParms extends EntityDictTypeExample {
		private Object record;

		public UpdateByExampleParms(Object record, EntityDictTypeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}