package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.FunctionRole;
import com.huateng.framework.ibatis.model.FunctionRoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FunctionRoleDAOImpl extends SqlMapClientDaoSupport implements
		FunctionRoleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public FunctionRoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public void insert(FunctionRole record) {
		getSqlMapClientTemplate().insert(
				"TB_FUNCTION_ROLE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int updateByPrimaryKey(FunctionRole record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_FUNCTION_ROLE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int updateByPrimaryKeySelective(FunctionRole record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_FUNCTION_ROLE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<FunctionRole> selectByExample(FunctionRoleExample example) {
		List<FunctionRole> list = (List<FunctionRole>) getSqlMapClientTemplate()
				.queryForList(
						"TB_FUNCTION_ROLE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public FunctionRole selectByPrimaryKey(String functionRoleId) {
		FunctionRole key = new FunctionRole();
		key.setFunctionRoleId(functionRoleId);
		FunctionRole record = (FunctionRole) getSqlMapClientTemplate()
				.queryForObject(
						"TB_FUNCTION_ROLE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int deleteByExample(FunctionRoleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_FUNCTION_ROLE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int deleteByPrimaryKey(String functionRoleId) {
		FunctionRole key = new FunctionRole();
		key.setFunctionRoleId(functionRoleId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_FUNCTION_ROLE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int countByExample(FunctionRoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_FUNCTION_ROLE.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int updateByExampleSelective(FunctionRole record,
			FunctionRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_FUNCTION_ROLE.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	public int updateByExample(FunctionRole record, FunctionRoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_FUNCTION_ROLE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_FUNCTION_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:09 CST 2010
	 */
	private static class UpdateByExampleParms extends FunctionRoleExample {
		private Object record;

		public UpdateByExampleParms(Object record, FunctionRoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}