package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.IssuerIndex;
import com.huateng.framework.ibatis.model.IssuerIndexExample;
import java.util.List;

public interface IssuerIndexDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	void insert(IssuerIndex record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int updateByPrimaryKey(IssuerIndex record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int updateByPrimaryKeySelective(IssuerIndex record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	List<IssuerIndex> selectByExample(IssuerIndexExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	IssuerIndex selectByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int deleteByExample(IssuerIndexExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int countByExample(IssuerIndexExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int updateByExampleSelective(IssuerIndex record, IssuerIndexExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISSUER_INDEX
	 * 
	 * @abatorgenerated Tue Mar 01 15:23:10 CST 2011
	 */
	int updateByExample(IssuerIndex record, IssuerIndexExample example);
}