package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.PictrueInfo;
import com.huateng.framework.ibatis.model.PictrueInfoExample;
import com.huateng.framework.ibatis.model.PictrueInfoKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PictrueInfoDAOImpl extends SqlMapClientDaoSupport implements PictrueInfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public PictrueInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int countByExample(PictrueInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_PICTURE_INFO.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int deleteByExample(PictrueInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_PICTURE_INFO.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int deleteByPrimaryKey(PictrueInfoKey key) {
        int rows = getSqlMapClientTemplate().delete("TB_PICTURE_INFO.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void insert(PictrueInfo record) {
        getSqlMapClientTemplate().insert("TB_PICTURE_INFO.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public void insertSelective(PictrueInfo record) {
        getSqlMapClientTemplate().insert("TB_PICTURE_INFO.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public List selectByExample(PictrueInfoExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_PICTURE_INFO.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public PictrueInfo selectByPrimaryKey(PictrueInfoKey key) {
        PictrueInfo record = (PictrueInfo) getSqlMapClientTemplate().queryForObject("TB_PICTURE_INFO.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByExampleSelective(PictrueInfo record, PictrueInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_PICTURE_INFO.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByExample(PictrueInfo record, PictrueInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_PICTURE_INFO.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByPrimaryKeySelective(PictrueInfo record) {
        int rows = getSqlMapClientTemplate().update("TB_PICTURE_INFO.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    public int updateByPrimaryKey(PictrueInfo record) {
        int rows = getSqlMapClientTemplate().update("TB_PICTURE_INFO.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_PICTURE_INFO
     *
     * @ibatorgenerated Thu Nov 16 09:32:07 CST 2017
     */
    private static class UpdateByExampleParms extends PictrueInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, PictrueInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}