package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.ProductPackage;
import com.huateng.framework.ibatis.model.ProductPackageExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductPackageDAOImpl extends SqlMapClientDaoSupport implements
		ProductPackageDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public ProductPackageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public void insert(ProductPackage record) {
		getSqlMapClientTemplate().insert(
				"TB_REL_PRODUCT_PACKAGE.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int updateByPrimaryKey(ProductPackage record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_REL_PRODUCT_PACKAGE.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int updateByPrimaryKeySelective(ProductPackage record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_REL_PRODUCT_PACKAGE.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<ProductPackage> selectByExample(ProductPackageExample example) {
		List<ProductPackage> list = (List<ProductPackage>) getSqlMapClientTemplate()
				.queryForList(
						"TB_REL_PRODUCT_PACKAGE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public ProductPackage selectByPrimaryKey(String relId) {
		ProductPackage key = new ProductPackage();
		key.setRelId(relId);
		ProductPackage record = (ProductPackage) getSqlMapClientTemplate()
				.queryForObject(
						"TB_REL_PRODUCT_PACKAGE.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int deleteByExample(ProductPackageExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_REL_PRODUCT_PACKAGE.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int deleteByPrimaryKey(String relId) {
		ProductPackage key = new ProductPackage();
		key.setRelId(relId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_REL_PRODUCT_PACKAGE.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int countByExample(ProductPackageExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_REL_PRODUCT_PACKAGE.abatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int updateByExampleSelective(ProductPackage record,
			ProductPackageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_REL_PRODUCT_PACKAGE.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	public int updateByExample(ProductPackage record,
			ProductPackageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_REL_PRODUCT_PACKAGE.abatorgenerated_updateByExample",
						parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_REL_PRODUCT_PACKAGE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:20 CST 2010
	 */
	private static class UpdateByExampleParms extends ProductPackageExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductPackageExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}