package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.Role;
import com.huateng.framework.ibatis.model.RoleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RoleDAOImpl extends SqlMapClientDaoSupport implements RoleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public RoleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public void insert(Role record) {
		getSqlMapClientTemplate().insert("TB_ROLE.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int updateByPrimaryKey(Role record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ROLE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int updateByPrimaryKeySelective(Role record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ROLE.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Role> selectByExample(RoleExample example) {
		List<Role> list = (List<Role>) getSqlMapClientTemplate().queryForList(
				"TB_ROLE.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public Role selectByPrimaryKey(String roleId) {
		Role key = new Role();
		key.setRoleId(roleId);
		Role record = (Role) getSqlMapClientTemplate().queryForObject(
				"TB_ROLE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int deleteByExample(RoleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ROLE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int deleteByPrimaryKey(String roleId) {
		Role key = new Role();
		key.setRoleId(roleId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_ROLE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int countByExample(RoleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ROLE.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int updateByExampleSelective(Role record, RoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ROLE.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	public int updateByExample(Role record, RoleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ROLE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:30 CST 2010
	 */
	private static class UpdateByExampleParms extends RoleExample {
		private Object record;

		public UpdateByExampleParms(Object record, RoleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}