package com.huateng.framework.ibatis.dao;

import java.util.List;

import com.allinfinance.univer.seller.order.dto.SellOrderDownLoadDTO;
import com.huateng.framework.ibatis.model.BatchSum;
import com.huateng.framework.ibatis.model.SellOrder;
import com.huateng.framework.ibatis.model.SellOrderExample;

public interface SellOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	void insert(SellOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int updateByPrimaryKey(SellOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int updateByPrimaryKeySelective(SellOrder record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	List<SellOrder> selectByExample(SellOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	SellOrder selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int deleteByExample(SellOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int countByExample(SellOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int updateByExampleSelective(SellOrder record, SellOrderExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table INS_JAVA.TB_SELL_ORDER
	 * 
	 * @abatorgenerated Wed Mar 28 11:18:19 CST 2012
	 */
	int updateByExample(SellOrder record, SellOrderExample example);
	
	SellOrder selectByPrimaryKeyLockNowait(String orderId);
	List<BatchSum> selectOrderWithBatchSum(SellOrder order);
	
	/** 下载邮寄信息文件查询*/
	List<SellOrderDownLoadDTO> selectMailingInfos(SellOrderDownLoadDTO order);
	/**下载邮寄信息后更新下载标识*/
	int updateDownloadFalgByOrderId(SellOrderDownLoadDTO order);
	
}