package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.SellContract;
import com.huateng.framework.ibatis.model.SellContractExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SellContractDAOImpl extends SqlMapClientDaoSupport implements
		SellContractDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public SellContractDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public void insert(SellContract record) {
		getSqlMapClientTemplate().insert(
				"TB_SELL_CONTRACT.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int updateByPrimaryKey(SellContract record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_CONTRACT.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int updateByPrimaryKeySelective(SellContract record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_CONTRACT.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SellContract> selectByExample(SellContractExample example) {
		List<SellContract> list = (List<SellContract>) getSqlMapClientTemplate()
				.queryForList(
						"TB_SELL_CONTRACT.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public SellContract selectByPrimaryKey(String sellContractId) {
		SellContract key = new SellContract();
		key.setSellContractId(sellContractId);
		SellContract record = (SellContract) getSqlMapClientTemplate()
				.queryForObject(
						"TB_SELL_CONTRACT.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int deleteByExample(SellContractExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELL_CONTRACT.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int deleteByPrimaryKey(String sellContractId) {
		SellContract key = new SellContract();
		key.setSellContractId(sellContractId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELL_CONTRACT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int countByExample(SellContractExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_SELL_CONTRACT.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int updateByExampleSelective(SellContract record,
			SellContractExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_CONTRACT.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	public int updateByExample(SellContract record, SellContractExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_CONTRACT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_SELL_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 12:49:21 CST 2010
	 */
	private static class UpdateByExampleParms extends SellContractExample {
		private Object record;

		public UpdateByExampleParms(Object record, SellContractExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public SellContract selectByPrimary(SellContract sellContract) {
		SellContract Contract=(SellContract) getSqlMapClientTemplate().queryForObject("TB_SELL_CONTRACT.abatorgenerated_select", sellContract);
		return Contract;
	}
	
	@Override
	public SellContract selectByContractSeller(String contractBuyer) {
		SellContract key = new SellContract();
		key.setContractBuyer(contractBuyer);
		key.setContractType("1");
		SellContract record = (SellContract) getSqlMapClientTemplate()
				.queryForObject(
						"TB_SELL_CONTRACT.abatorgenerated_selectByContractBuyer",
						key);
		return record;
	}
}