package com.allinfinance.prepay.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.ENTITY_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEFAULT_FLAG
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String defaultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DATA_STATE
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    private String dataState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_ID
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_ID
     *
     * @param departmentId the value for SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId == null ? null : departmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.ENTITY_ID
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.ENTITY_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.ENTITY_ID
     *
     * @param entityId the value for SVC_MNG.TB_ENTITY_DEPARTMENT.ENTITY_ID
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_NAME
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_NAME
     *
     * @param departmentName the value for SVC_MNG.TB_ENTITY_DEPARTMENT.DEPARTMENT_NAME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEFAULT_FLAG
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.DEFAULT_FLAG
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DEFAULT_FLAG
     *
     * @param defaultFlag the value for SVC_MNG.TB_ENTITY_DEPARTMENT.DEFAULT_FLAG
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setDefaultFlag(String defaultFlag) {
        this.defaultFlag = defaultFlag == null ? null : defaultFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_USER
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_USER
     *
     * @param createUser the value for SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_TIME
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_TIME
     *
     * @param createTime the value for SVC_MNG.TB_ENTITY_DEPARTMENT.CREATE_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_USER
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_USER
     *
     * @param modifyUser the value for SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_USER
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_TIME
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_TIME
     *
     * @param modifyTime the value for SVC_MNG.TB_ENTITY_DEPARTMENT.MODIFY_TIME
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DATA_STATE
     *
     * @return the value of SVC_MNG.TB_ENTITY_DEPARTMENT.DATA_STATE
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public String getDataState() {
        return dataState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_ENTITY_DEPARTMENT.DATA_STATE
     *
     * @param dataState the value for SVC_MNG.TB_ENTITY_DEPARTMENT.DATA_STATE
     *
     * @mbggenerated Mon Apr 25 11:09:39 CST 2016
     */
    public void setDataState(String dataState) {
        this.dataState = dataState == null ? null : dataState.trim();
    }
}