package com.allinfinance.prepay.model;

import java.util.ArrayList;
import java.util.List;

public class EntityInvoiceAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public EntityInvoiceAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andInvoiceAddressIdIsNull() {
            addCriterion("INVOICE_ADDRESS_ID is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdIsNotNull() {
            addCriterion("INVOICE_ADDRESS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS_ID =", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdNotEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS_ID <>", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdGreaterThan(String value) {
            addCriterion("INVOICE_ADDRESS_ID >", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS_ID >=", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdLessThan(String value) {
            addCriterion("INVOICE_ADDRESS_ID <", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS_ID <=", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdLike(String value) {
            addCriterion("INVOICE_ADDRESS_ID like", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdNotLike(String value) {
            addCriterion("INVOICE_ADDRESS_ID not like", value, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdIn(List<String> values) {
            addCriterion("INVOICE_ADDRESS_ID in", values, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdNotIn(List<String> values) {
            addCriterion("INVOICE_ADDRESS_ID not in", values, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS_ID between", value1, value2, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIdNotBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS_ID not between", value1, value2, "invoiceAddressId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNull() {
            addCriterion("ENTITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNotNull() {
            addCriterion("ENTITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntityIdEqualTo(String value) {
            addCriterion("ENTITY_ID =", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotEqualTo(String value) {
            addCriterion("ENTITY_ID <>", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThan(String value) {
            addCriterion("ENTITY_ID >", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThanOrEqualTo(String value) {
            addCriterion("ENTITY_ID >=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThan(String value) {
            addCriterion("ENTITY_ID <", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThanOrEqualTo(String value) {
            addCriterion("ENTITY_ID <=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLike(String value) {
            addCriterion("ENTITY_ID like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotLike(String value) {
            addCriterion("ENTITY_ID not like", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIn(List<String> values) {
            addCriterion("ENTITY_ID in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotIn(List<String> values) {
            addCriterion("ENTITY_ID not in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdBetween(String value1, String value2) {
            addCriterion("ENTITY_ID between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotBetween(String value1, String value2) {
            addCriterion("ENTITY_ID not between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientIsNull() {
            addCriterion("INVOICE_RECIPIENT is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientIsNotNull() {
            addCriterion("INVOICE_RECIPIENT is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientEqualTo(String value) {
            addCriterion("INVOICE_RECIPIENT =", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientNotEqualTo(String value) {
            addCriterion("INVOICE_RECIPIENT <>", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientGreaterThan(String value) {
            addCriterion("INVOICE_RECIPIENT >", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_RECIPIENT >=", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientLessThan(String value) {
            addCriterion("INVOICE_RECIPIENT <", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_RECIPIENT <=", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientLike(String value) {
            addCriterion("INVOICE_RECIPIENT like", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientNotLike(String value) {
            addCriterion("INVOICE_RECIPIENT not like", value, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientIn(List<String> values) {
            addCriterion("INVOICE_RECIPIENT in", values, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientNotIn(List<String> values) {
            addCriterion("INVOICE_RECIPIENT not in", values, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientBetween(String value1, String value2) {
            addCriterion("INVOICE_RECIPIENT between", value1, value2, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andInvoiceRecipientNotBetween(String value1, String value2) {
            addCriterion("INVOICE_RECIPIENT not between", value1, value2, "invoiceRecipient");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNull() {
            addCriterion("ADDRESS_POSTCODE is null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIsNotNull() {
            addCriterion("ADDRESS_POSTCODE is not null");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE =", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE <>", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThan(String value) {
            addCriterion("ADDRESS_POSTCODE >", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE >=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThan(String value) {
            addCriterion("ADDRESS_POSTCODE <", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS_POSTCODE <=", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeLike(String value) {
            addCriterion("ADDRESS_POSTCODE like", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotLike(String value) {
            addCriterion("ADDRESS_POSTCODE not like", value, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeIn(List<String> values) {
            addCriterion("ADDRESS_POSTCODE in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotIn(List<String> values) {
            addCriterion("ADDRESS_POSTCODE not in", values, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeBetween(String value1, String value2) {
            addCriterion("ADDRESS_POSTCODE between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andAddressPostcodeNotBetween(String value1, String value2) {
            addCriterion("ADDRESS_POSTCODE not between", value1, value2, "addressPostcode");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIsNull() {
            addCriterion("INVOICE_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIsNotNull() {
            addCriterion("INVOICE_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS =", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressNotEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS <>", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressGreaterThan(String value) {
            addCriterion("INVOICE_ADDRESS >", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressGreaterThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS >=", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressLessThan(String value) {
            addCriterion("INVOICE_ADDRESS <", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressLessThanOrEqualTo(String value) {
            addCriterion("INVOICE_ADDRESS <=", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressLike(String value) {
            addCriterion("INVOICE_ADDRESS like", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressNotLike(String value) {
            addCriterion("INVOICE_ADDRESS not like", value, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressIn(List<String> values) {
            addCriterion("INVOICE_ADDRESS in", values, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressNotIn(List<String> values) {
            addCriterion("INVOICE_ADDRESS not in", values, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS between", value1, value2, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andInvoiceAddressNotBetween(String value1, String value2) {
            addCriterion("INVOICE_ADDRESS not between", value1, value2, "invoiceAddress");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionIsNull() {
            addCriterion("DELIVERY_OPTION is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionIsNotNull() {
            addCriterion("DELIVERY_OPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionEqualTo(String value) {
            addCriterion("DELIVERY_OPTION =", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionNotEqualTo(String value) {
            addCriterion("DELIVERY_OPTION <>", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionGreaterThan(String value) {
            addCriterion("DELIVERY_OPTION >", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_OPTION >=", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionLessThan(String value) {
            addCriterion("DELIVERY_OPTION <", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_OPTION <=", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionLike(String value) {
            addCriterion("DELIVERY_OPTION like", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionNotLike(String value) {
            addCriterion("DELIVERY_OPTION not like", value, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionIn(List<String> values) {
            addCriterion("DELIVERY_OPTION in", values, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionNotIn(List<String> values) {
            addCriterion("DELIVERY_OPTION not in", values, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionBetween(String value1, String value2) {
            addCriterion("DELIVERY_OPTION between", value1, value2, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDeliveryOptionNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_OPTION not between", value1, value2, "deliveryOption");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagIsNull() {
            addCriterion("DEFAULT_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagIsNotNull() {
            addCriterion("DEFAULT_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagEqualTo(String value) {
            addCriterion("DEFAULT_FLAG =", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagNotEqualTo(String value) {
            addCriterion("DEFAULT_FLAG <>", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagGreaterThan(String value) {
            addCriterion("DEFAULT_FLAG >", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULT_FLAG >=", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagLessThan(String value) {
            addCriterion("DEFAULT_FLAG <", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagLessThanOrEqualTo(String value) {
            addCriterion("DEFAULT_FLAG <=", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagLike(String value) {
            addCriterion("DEFAULT_FLAG like", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagNotLike(String value) {
            addCriterion("DEFAULT_FLAG not like", value, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagIn(List<String> values) {
            addCriterion("DEFAULT_FLAG in", values, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagNotIn(List<String> values) {
            addCriterion("DEFAULT_FLAG not in", values, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagBetween(String value1, String value2) {
            addCriterion("DEFAULT_FLAG between", value1, value2, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andDefaultFlagNotBetween(String value1, String value2) {
            addCriterion("DEFAULT_FLAG not between", value1, value2, "defaultFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(String value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(String value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(String value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(String value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLike(String value) {
            addCriterion("MODIFY_TIME like", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotLike(String value) {
            addCriterion("MODIFY_TIME not like", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<String> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<String> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(String value1, String value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(String value1, String value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDataStateIsNull() {
            addCriterion("DATA_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDataStateIsNotNull() {
            addCriterion("DATA_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDataStateEqualTo(String value) {
            addCriterion("DATA_STATE =", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotEqualTo(String value) {
            addCriterion("DATA_STATE <>", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateGreaterThan(String value) {
            addCriterion("DATA_STATE >", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_STATE >=", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLessThan(String value) {
            addCriterion("DATA_STATE <", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLessThanOrEqualTo(String value) {
            addCriterion("DATA_STATE <=", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLike(String value) {
            addCriterion("DATA_STATE like", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotLike(String value) {
            addCriterion("DATA_STATE not like", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateIn(List<String> values) {
            addCriterion("DATA_STATE in", values, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotIn(List<String> values) {
            addCriterion("DATA_STATE not in", values, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateBetween(String value1, String value2) {
            addCriterion("DATA_STATE between", value1, value2, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotBetween(String value1, String value2) {
            addCriterion("DATA_STATE not between", value1, value2, "dataState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 25 15:23:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_ENTITY_INVOICE_ADDRESS
     *
     * @mbggenerated Mon Apr 25 15:23:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}