package com.allinfinance.prepay.model;

import java.util.ArrayList;
import java.util.List;

public class SellContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public SellContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSellContractIdIsNull() {
            addCriterion("SELL_CONTRACT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSellContractIdIsNotNull() {
            addCriterion("SELL_CONTRACT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSellContractIdEqualTo(String value) {
            addCriterion("SELL_CONTRACT_ID =", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotEqualTo(String value) {
            addCriterion("SELL_CONTRACT_ID <>", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdGreaterThan(String value) {
            addCriterion("SELL_CONTRACT_ID >", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("SELL_CONTRACT_ID >=", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdLessThan(String value) {
            addCriterion("SELL_CONTRACT_ID <", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdLessThanOrEqualTo(String value) {
            addCriterion("SELL_CONTRACT_ID <=", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdLike(String value) {
            addCriterion("SELL_CONTRACT_ID like", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotLike(String value) {
            addCriterion("SELL_CONTRACT_ID not like", value, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdIn(List<String> values) {
            addCriterion("SELL_CONTRACT_ID in", values, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotIn(List<String> values) {
            addCriterion("SELL_CONTRACT_ID not in", values, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdBetween(String value1, String value2) {
            addCriterion("SELL_CONTRACT_ID between", value1, value2, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andSellContractIdNotBetween(String value1, String value2) {
            addCriterion("SELL_CONTRACT_ID not between", value1, value2, "sellContractId");
            return (Criteria) this;
        }

        public Criteria andContractBuyerIsNull() {
            addCriterion("CONTRACT_BUYER is null");
            return (Criteria) this;
        }

        public Criteria andContractBuyerIsNotNull() {
            addCriterion("CONTRACT_BUYER is not null");
            return (Criteria) this;
        }

        public Criteria andContractBuyerEqualTo(String value) {
            addCriterion("CONTRACT_BUYER =", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerNotEqualTo(String value) {
            addCriterion("CONTRACT_BUYER <>", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerGreaterThan(String value) {
            addCriterion("CONTRACT_BUYER >", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_BUYER >=", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerLessThan(String value) {
            addCriterion("CONTRACT_BUYER <", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_BUYER <=", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerLike(String value) {
            addCriterion("CONTRACT_BUYER like", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerNotLike(String value) {
            addCriterion("CONTRACT_BUYER not like", value, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerIn(List<String> values) {
            addCriterion("CONTRACT_BUYER in", values, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerNotIn(List<String> values) {
            addCriterion("CONTRACT_BUYER not in", values, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerBetween(String value1, String value2) {
            addCriterion("CONTRACT_BUYER between", value1, value2, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractBuyerNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_BUYER not between", value1, value2, "contractBuyer");
            return (Criteria) this;
        }

        public Criteria andContractSellerIsNull() {
            addCriterion("CONTRACT_SELLER is null");
            return (Criteria) this;
        }

        public Criteria andContractSellerIsNotNull() {
            addCriterion("CONTRACT_SELLER is not null");
            return (Criteria) this;
        }

        public Criteria andContractSellerEqualTo(String value) {
            addCriterion("CONTRACT_SELLER =", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerNotEqualTo(String value) {
            addCriterion("CONTRACT_SELLER <>", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerGreaterThan(String value) {
            addCriterion("CONTRACT_SELLER >", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_SELLER >=", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerLessThan(String value) {
            addCriterion("CONTRACT_SELLER <", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_SELLER <=", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerLike(String value) {
            addCriterion("CONTRACT_SELLER like", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerNotLike(String value) {
            addCriterion("CONTRACT_SELLER not like", value, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerIn(List<String> values) {
            addCriterion("CONTRACT_SELLER in", values, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerNotIn(List<String> values) {
            addCriterion("CONTRACT_SELLER not in", values, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerBetween(String value1, String value2) {
            addCriterion("CONTRACT_SELLER between", value1, value2, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andContractSellerNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_SELLER not between", value1, value2, "contractSeller");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeIsNull() {
            addCriterion("DELIVERY_FEE is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeIsNotNull() {
            addCriterion("DELIVERY_FEE is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeEqualTo(String value) {
            addCriterion("DELIVERY_FEE =", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeNotEqualTo(String value) {
            addCriterion("DELIVERY_FEE <>", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeGreaterThan(String value) {
            addCriterion("DELIVERY_FEE >", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_FEE >=", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeLessThan(String value) {
            addCriterion("DELIVERY_FEE <", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_FEE <=", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeLike(String value) {
            addCriterion("DELIVERY_FEE like", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeNotLike(String value) {
            addCriterion("DELIVERY_FEE not like", value, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeIn(List<String> values) {
            addCriterion("DELIVERY_FEE in", values, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeNotIn(List<String> values) {
            addCriterion("DELIVERY_FEE not in", values, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeBetween(String value1, String value2) {
            addCriterion("DELIVERY_FEE between", value1, value2, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andDeliveryFeeNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_FEE not between", value1, value2, "deliveryFee");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleIsNull() {
            addCriterion("SETTLE_PERIOD_RULE is null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleIsNotNull() {
            addCriterion("SETTLE_PERIOD_RULE is not null");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleEqualTo(String value) {
            addCriterion("SETTLE_PERIOD_RULE =", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleNotEqualTo(String value) {
            addCriterion("SETTLE_PERIOD_RULE <>", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleGreaterThan(String value) {
            addCriterion("SETTLE_PERIOD_RULE >", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleGreaterThanOrEqualTo(String value) {
            addCriterion("SETTLE_PERIOD_RULE >=", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleLessThan(String value) {
            addCriterion("SETTLE_PERIOD_RULE <", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleLessThanOrEqualTo(String value) {
            addCriterion("SETTLE_PERIOD_RULE <=", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleLike(String value) {
            addCriterion("SETTLE_PERIOD_RULE like", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleNotLike(String value) {
            addCriterion("SETTLE_PERIOD_RULE not like", value, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleIn(List<String> values) {
            addCriterion("SETTLE_PERIOD_RULE in", values, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleNotIn(List<String> values) {
            addCriterion("SETTLE_PERIOD_RULE not in", values, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleBetween(String value1, String value2) {
            addCriterion("SETTLE_PERIOD_RULE between", value1, value2, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSettlePeriodRuleNotBetween(String value1, String value2) {
            addCriterion("SETTLE_PERIOD_RULE not between", value1, value2, "settlePeriodRule");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatIsNull() {
            addCriterion("SMS_SVC_STAT is null");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatIsNotNull() {
            addCriterion("SMS_SVC_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatEqualTo(String value) {
            addCriterion("SMS_SVC_STAT =", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatNotEqualTo(String value) {
            addCriterion("SMS_SVC_STAT <>", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatGreaterThan(String value) {
            addCriterion("SMS_SVC_STAT >", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_SVC_STAT >=", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatLessThan(String value) {
            addCriterion("SMS_SVC_STAT <", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatLessThanOrEqualTo(String value) {
            addCriterion("SMS_SVC_STAT <=", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatLike(String value) {
            addCriterion("SMS_SVC_STAT like", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatNotLike(String value) {
            addCriterion("SMS_SVC_STAT not like", value, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatIn(List<String> values) {
            addCriterion("SMS_SVC_STAT in", values, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatNotIn(List<String> values) {
            addCriterion("SMS_SVC_STAT not in", values, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatBetween(String value1, String value2) {
            addCriterion("SMS_SVC_STAT between", value1, value2, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andSmsSvcStatNotBetween(String value1, String value2) {
            addCriterion("SMS_SVC_STAT not between", value1, value2, "smsSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatIsNull() {
            addCriterion("EMAIL_SVC_STAT is null");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatIsNotNull() {
            addCriterion("EMAIL_SVC_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatEqualTo(String value) {
            addCriterion("EMAIL_SVC_STAT =", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatNotEqualTo(String value) {
            addCriterion("EMAIL_SVC_STAT <>", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatGreaterThan(String value) {
            addCriterion("EMAIL_SVC_STAT >", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL_SVC_STAT >=", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatLessThan(String value) {
            addCriterion("EMAIL_SVC_STAT <", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatLessThanOrEqualTo(String value) {
            addCriterion("EMAIL_SVC_STAT <=", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatLike(String value) {
            addCriterion("EMAIL_SVC_STAT like", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatNotLike(String value) {
            addCriterion("EMAIL_SVC_STAT not like", value, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatIn(List<String> values) {
            addCriterion("EMAIL_SVC_STAT in", values, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatNotIn(List<String> values) {
            addCriterion("EMAIL_SVC_STAT not in", values, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatBetween(String value1, String value2) {
            addCriterion("EMAIL_SVC_STAT between", value1, value2, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andEmailSvcStatNotBetween(String value1, String value2) {
            addCriterion("EMAIL_SVC_STAT not between", value1, value2, "emailSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatIsNull() {
            addCriterion("MONSTMT_SVC_STAT is null");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatIsNotNull() {
            addCriterion("MONSTMT_SVC_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatEqualTo(String value) {
            addCriterion("MONSTMT_SVC_STAT =", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatNotEqualTo(String value) {
            addCriterion("MONSTMT_SVC_STAT <>", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatGreaterThan(String value) {
            addCriterion("MONSTMT_SVC_STAT >", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatGreaterThanOrEqualTo(String value) {
            addCriterion("MONSTMT_SVC_STAT >=", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatLessThan(String value) {
            addCriterion("MONSTMT_SVC_STAT <", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatLessThanOrEqualTo(String value) {
            addCriterion("MONSTMT_SVC_STAT <=", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatLike(String value) {
            addCriterion("MONSTMT_SVC_STAT like", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatNotLike(String value) {
            addCriterion("MONSTMT_SVC_STAT not like", value, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatIn(List<String> values) {
            addCriterion("MONSTMT_SVC_STAT in", values, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatNotIn(List<String> values) {
            addCriterion("MONSTMT_SVC_STAT not in", values, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatBetween(String value1, String value2) {
            addCriterion("MONSTMT_SVC_STAT between", value1, value2, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andMonstmtSvcStatNotBetween(String value1, String value2) {
            addCriterion("MONSTMT_SVC_STAT not between", value1, value2, "monstmtSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatIsNull() {
            addCriterion("WEB_PAY_STAT is null");
            return (Criteria) this;
        }

        public Criteria andWebPayStatIsNotNull() {
            addCriterion("WEB_PAY_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andWebPayStatEqualTo(String value) {
            addCriterion("WEB_PAY_STAT =", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatNotEqualTo(String value) {
            addCriterion("WEB_PAY_STAT <>", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatGreaterThan(String value) {
            addCriterion("WEB_PAY_STAT >", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatGreaterThanOrEqualTo(String value) {
            addCriterion("WEB_PAY_STAT >=", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatLessThan(String value) {
            addCriterion("WEB_PAY_STAT <", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatLessThanOrEqualTo(String value) {
            addCriterion("WEB_PAY_STAT <=", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatLike(String value) {
            addCriterion("WEB_PAY_STAT like", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatNotLike(String value) {
            addCriterion("WEB_PAY_STAT not like", value, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatIn(List<String> values) {
            addCriterion("WEB_PAY_STAT in", values, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatNotIn(List<String> values) {
            addCriterion("WEB_PAY_STAT not in", values, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatBetween(String value1, String value2) {
            addCriterion("WEB_PAY_STAT between", value1, value2, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebPayStatNotBetween(String value1, String value2) {
            addCriterion("WEB_PAY_STAT not between", value1, value2, "webPayStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatIsNull() {
            addCriterion("WEB_SMS_SVC_STAT is null");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatIsNotNull() {
            addCriterion("WEB_SMS_SVC_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatEqualTo(String value) {
            addCriterion("WEB_SMS_SVC_STAT =", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatNotEqualTo(String value) {
            addCriterion("WEB_SMS_SVC_STAT <>", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatGreaterThan(String value) {
            addCriterion("WEB_SMS_SVC_STAT >", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatGreaterThanOrEqualTo(String value) {
            addCriterion("WEB_SMS_SVC_STAT >=", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatLessThan(String value) {
            addCriterion("WEB_SMS_SVC_STAT <", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatLessThanOrEqualTo(String value) {
            addCriterion("WEB_SMS_SVC_STAT <=", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatLike(String value) {
            addCriterion("WEB_SMS_SVC_STAT like", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatNotLike(String value) {
            addCriterion("WEB_SMS_SVC_STAT not like", value, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatIn(List<String> values) {
            addCriterion("WEB_SMS_SVC_STAT in", values, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatNotIn(List<String> values) {
            addCriterion("WEB_SMS_SVC_STAT not in", values, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatBetween(String value1, String value2) {
            addCriterion("WEB_SMS_SVC_STAT between", value1, value2, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebSmsSvcStatNotBetween(String value1, String value2) {
            addCriterion("WEB_SMS_SVC_STAT not between", value1, value2, "webSmsSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatIsNull() {
            addCriterion("WEB_EMAIL_SVC_STAT is null");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatIsNotNull() {
            addCriterion("WEB_EMAIL_SVC_STAT is not null");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatEqualTo(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT =", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatNotEqualTo(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT <>", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatGreaterThan(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT >", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatGreaterThanOrEqualTo(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT >=", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatLessThan(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT <", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatLessThanOrEqualTo(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT <=", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatLike(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT like", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatNotLike(String value) {
            addCriterion("WEB_EMAIL_SVC_STAT not like", value, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatIn(List<String> values) {
            addCriterion("WEB_EMAIL_SVC_STAT in", values, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatNotIn(List<String> values) {
            addCriterion("WEB_EMAIL_SVC_STAT not in", values, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatBetween(String value1, String value2) {
            addCriterion("WEB_EMAIL_SVC_STAT between", value1, value2, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andWebEmailSvcStatNotBetween(String value1, String value2) {
            addCriterion("WEB_EMAIL_SVC_STAT not between", value1, value2, "webEmailSvcStat");
            return (Criteria) this;
        }

        public Criteria andContractStateIsNull() {
            addCriterion("CONTRACT_STATE is null");
            return (Criteria) this;
        }

        public Criteria andContractStateIsNotNull() {
            addCriterion("CONTRACT_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andContractStateEqualTo(String value) {
            addCriterion("CONTRACT_STATE =", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateNotEqualTo(String value) {
            addCriterion("CONTRACT_STATE <>", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateGreaterThan(String value) {
            addCriterion("CONTRACT_STATE >", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_STATE >=", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateLessThan(String value) {
            addCriterion("CONTRACT_STATE <", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_STATE <=", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateLike(String value) {
            addCriterion("CONTRACT_STATE like", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateNotLike(String value) {
            addCriterion("CONTRACT_STATE not like", value, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateIn(List<String> values) {
            addCriterion("CONTRACT_STATE in", values, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateNotIn(List<String> values) {
            addCriterion("CONTRACT_STATE not in", values, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateBetween(String value1, String value2) {
            addCriterion("CONTRACT_STATE between", value1, value2, "contractState");
            return (Criteria) this;
        }

        public Criteria andContractStateNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_STATE not between", value1, value2, "contractState");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIsNull() {
            addCriterion("EXPIRY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIsNotNull() {
            addCriterion("EXPIRY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpiryDateEqualTo(String value) {
            addCriterion("EXPIRY_DATE =", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotEqualTo(String value) {
            addCriterion("EXPIRY_DATE <>", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateGreaterThan(String value) {
            addCriterion("EXPIRY_DATE >", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateGreaterThanOrEqualTo(String value) {
            addCriterion("EXPIRY_DATE >=", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateLessThan(String value) {
            addCriterion("EXPIRY_DATE <", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateLessThanOrEqualTo(String value) {
            addCriterion("EXPIRY_DATE <=", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateLike(String value) {
            addCriterion("EXPIRY_DATE like", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotLike(String value) {
            addCriterion("EXPIRY_DATE not like", value, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateIn(List<String> values) {
            addCriterion("EXPIRY_DATE in", values, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotIn(List<String> values) {
            addCriterion("EXPIRY_DATE not in", values, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateBetween(String value1, String value2) {
            addCriterion("EXPIRY_DATE between", value1, value2, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andExpiryDateNotBetween(String value1, String value2) {
            addCriterion("EXPIRY_DATE not between", value1, value2, "expiryDate");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNull() {
            addCriterion("MODIFY_USER is null");
            return (Criteria) this;
        }

        public Criteria andModifyUserIsNotNull() {
            addCriterion("MODIFY_USER is not null");
            return (Criteria) this;
        }

        public Criteria andModifyUserEqualTo(String value) {
            addCriterion("MODIFY_USER =", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotEqualTo(String value) {
            addCriterion("MODIFY_USER <>", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThan(String value) {
            addCriterion("MODIFY_USER >", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER >=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThan(String value) {
            addCriterion("MODIFY_USER <", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USER <=", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserLike(String value) {
            addCriterion("MODIFY_USER like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotLike(String value) {
            addCriterion("MODIFY_USER not like", value, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserIn(List<String> values) {
            addCriterion("MODIFY_USER in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotIn(List<String> values) {
            addCriterion("MODIFY_USER not in", values, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserBetween(String value1, String value2) {
            addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyUserNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USER not between", value1, value2, "modifyUser");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(String value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(String value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(String value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(String value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLike(String value) {
            addCriterion("MODIFY_TIME like", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotLike(String value) {
            addCriterion("MODIFY_TIME not like", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<String> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<String> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(String value1, String value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(String value1, String value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andDataStateIsNull() {
            addCriterion("DATA_STATE is null");
            return (Criteria) this;
        }

        public Criteria andDataStateIsNotNull() {
            addCriterion("DATA_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andDataStateEqualTo(String value) {
            addCriterion("DATA_STATE =", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotEqualTo(String value) {
            addCriterion("DATA_STATE <>", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateGreaterThan(String value) {
            addCriterion("DATA_STATE >", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_STATE >=", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLessThan(String value) {
            addCriterion("DATA_STATE <", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLessThanOrEqualTo(String value) {
            addCriterion("DATA_STATE <=", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateLike(String value) {
            addCriterion("DATA_STATE like", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotLike(String value) {
            addCriterion("DATA_STATE not like", value, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateIn(List<String> values) {
            addCriterion("DATA_STATE in", values, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotIn(List<String> values) {
            addCriterion("DATA_STATE not in", values, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateBetween(String value1, String value2) {
            addCriterion("DATA_STATE between", value1, value2, "dataState");
            return (Criteria) this;
        }

        public Criteria andDataStateNotBetween(String value1, String value2) {
            addCriterion("DATA_STATE not between", value1, value2, "dataState");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNull() {
            addCriterion("CONTRACT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andContractTypeIsNotNull() {
            addCriterion("CONTRACT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andContractTypeEqualTo(String value) {
            addCriterion("CONTRACT_TYPE =", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotEqualTo(String value) {
            addCriterion("CONTRACT_TYPE <>", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThan(String value) {
            addCriterion("CONTRACT_TYPE >", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONTRACT_TYPE >=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThan(String value) {
            addCriterion("CONTRACT_TYPE <", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLessThanOrEqualTo(String value) {
            addCriterion("CONTRACT_TYPE <=", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeLike(String value) {
            addCriterion("CONTRACT_TYPE like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotLike(String value) {
            addCriterion("CONTRACT_TYPE not like", value, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeIn(List<String> values) {
            addCriterion("CONTRACT_TYPE in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotIn(List<String> values) {
            addCriterion("CONTRACT_TYPE not in", values, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeBetween(String value1, String value2) {
            addCriterion("CONTRACT_TYPE between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andContractTypeNotBetween(String value1, String value2) {
            addCriterion("CONTRACT_TYPE not between", value1, value2, "contractType");
            return (Criteria) this;
        }

        public Criteria andClearTpIsNull() {
            addCriterion("CLEAR_TP is null");
            return (Criteria) this;
        }

        public Criteria andClearTpIsNotNull() {
            addCriterion("CLEAR_TP is not null");
            return (Criteria) this;
        }

        public Criteria andClearTpEqualTo(String value) {
            addCriterion("CLEAR_TP =", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpNotEqualTo(String value) {
            addCriterion("CLEAR_TP <>", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpGreaterThan(String value) {
            addCriterion("CLEAR_TP >", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpGreaterThanOrEqualTo(String value) {
            addCriterion("CLEAR_TP >=", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpLessThan(String value) {
            addCriterion("CLEAR_TP <", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpLessThanOrEqualTo(String value) {
            addCriterion("CLEAR_TP <=", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpLike(String value) {
            addCriterion("CLEAR_TP like", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpNotLike(String value) {
            addCriterion("CLEAR_TP not like", value, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpIn(List<String> values) {
            addCriterion("CLEAR_TP in", values, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpNotIn(List<String> values) {
            addCriterion("CLEAR_TP not in", values, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpBetween(String value1, String value2) {
            addCriterion("CLEAR_TP between", value1, value2, "clearTp");
            return (Criteria) this;
        }

        public Criteria andClearTpNotBetween(String value1, String value2) {
            addCriterion("CLEAR_TP not between", value1, value2, "clearTp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated do_not_delete_during_merge Mon Apr 25 16:54:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SVC_MNG.TB_SELL_CONTRACT
     *
     * @mbggenerated Mon Apr 25 16:54:33 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}