package com.allinfinance.prepay.model;

public class SellAcctypeContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.SELL_CONTRACT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String sellContractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.RULE_NO
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String ruleNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ACCTYPE_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String acctypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.TXN_NUM
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String txnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.FEE
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    private String fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ID
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ID
     *
     * @param id the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.SELL_CONTRACT_ID
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.SELL_CONTRACT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getSellContractId() {
        return sellContractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.SELL_CONTRACT_ID
     *
     * @param sellContractId the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.SELL_CONTRACT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setSellContractId(String sellContractId) {
        this.sellContractId = sellContractId == null ? null : sellContractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.RULE_NO
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.RULE_NO
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getRuleNo() {
        return ruleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.RULE_NO
     *
     * @param ruleNo the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.RULE_NO
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setRuleNo(String ruleNo) {
        this.ruleNo = ruleNo == null ? null : ruleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.PRODUCT_ID
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.PRODUCT_ID
     *
     * @param productId the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.PRODUCT_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ACCTYPE_ID
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ACCTYPE_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getAcctypeId() {
        return acctypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ACCTYPE_ID
     *
     * @param acctypeId the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.ACCTYPE_ID
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setAcctypeId(String acctypeId) {
        this.acctypeId = acctypeId == null ? null : acctypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.TXN_NUM
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.TXN_NUM
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getTxnNum() {
        return txnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.TXN_NUM
     *
     * @param txnNum the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.TXN_NUM
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setTxnNum(String txnNum) {
        this.txnNum = txnNum == null ? null : txnNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_USER
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_USER
     *
     * @param createUser the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_TIME
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_TIME
     *
     * @param createTime the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.CREATE_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_USER
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_USER
     *
     * @param modifyUser the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_USER
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_TIME
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_TIME
     *
     * @param modifyTime the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.MODIFY_TIME
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.FEE
     *
     * @return the value of SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.FEE
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.FEE
     *
     * @param fee the value for SVC_MNG.TB_SELL_ACCTYPE_CONTRACT.FEE
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }
}