DELETE FROM "SVC_MNG"."TB_SELL_ORDER" WHERE order_id = '-2222';
DELETE FROM "SVC_MNG"."TB_SELL_ORDER_LIST" WHERE order_id = '-2222';
DELETE FROM "SVC_MNG"."TB_SELL_ORDER_LIST" WHERE order_list_id = '-3333';
DELETE FROM "SVC_MNG"."TB_SELL_ORDER_LIST" WHERE order_list_id = '-4444';