package com.allinfinance.prepay.model;

public class CardholderEnterPriseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.SYSTEM_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    private String systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.CARD_HOLDER_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    private String cardHolderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.SYSTEM_ID
     *
     * @return the value of SVC_MNG.TB_CARDHOLDER_ENTERPRISE.SYSTEM_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.SYSTEM_ID
     *
     * @param systemId the value for SVC_MNG.TB_CARDHOLDER_ENTERPRISE.SYSTEM_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.CARD_HOLDER_ID
     *
     * @return the value of SVC_MNG.TB_CARDHOLDER_ENTERPRISE.CARD_HOLDER_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    public String getCardHolderId() {
        return cardHolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SVC_MNG.TB_CARDHOLDER_ENTERPRISE.CARD_HOLDER_ID
     *
     * @param cardHolderId the value for SVC_MNG.TB_CARDHOLDER_ENTERPRISE.CARD_HOLDER_ID
     *
     * @mbggenerated Mon Aug 14 15:33:00 CST 2017
     */
    public void setCardHolderId(String cardHolderId) {
        this.cardHolderId = cardHolderId == null ? null : cardHolderId.trim();
    }
}