package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.CardSerialNumber;
import com.huateng.framework.db.ibatis.model.CardSerialNumberExample;
import com.huateng.framework.db.ibatis.model.CardSerialNumberKey;
import java.util.List;

public interface CardSerialNumberDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	void insert(CardSerialNumber record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int updateByPrimaryKey(CardSerialNumber record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int updateByPrimaryKeySelective(CardSerialNumber record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	List<CardSerialNumber> selectByExample(CardSerialNumberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	CardSerialNumber selectByPrimaryKey(CardSerialNumberKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int deleteByExample(CardSerialNumberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int deleteByPrimaryKey(CardSerialNumberKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int countByExample(CardSerialNumberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int updateByExampleSelective(CardSerialNumber record,
			CardSerialNumberExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_SERIAL_NUMBER
	 * 
	 * @abatorgenerated Mon Dec 06 11:18:09 CST 2010
	 */
	int updateByExample(CardSerialNumber record, CardSerialNumberExample example);
}