package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.CardCompany;
import com.huateng.framework.db.ibatis.model.CardCompanyExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CardCompanyDAOImpl extends SqlMapClientDaoSupport implements
		CardCompanyDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public CardCompanyDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public void insert(CardCompany record) {
		getSqlMapClientTemplate().insert(
				"TB_CARD_COMPANY.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int updateByPrimaryKey(CardCompany record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_CARD_COMPANY.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int updateByPrimaryKeySelective(CardCompany record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_CARD_COMPANY.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<CardCompany> selectByExample(CardCompanyExample example) {
		List<CardCompany> list = (List<CardCompany>) getSqlMapClientTemplate()
				.queryForList(
						"TB_CARD_COMPANY.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public CardCompany selectByPrimaryKey(String cardCompanyId) {
		CardCompany key = new CardCompany();
		key.setCardCompanyId(cardCompanyId);
		CardCompany record = (CardCompany) getSqlMapClientTemplate()
				.queryForObject(
						"TB_CARD_COMPANY.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int deleteByExample(CardCompanyExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_CARD_COMPANY.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int deleteByPrimaryKey(String cardCompanyId) {
		CardCompany key = new CardCompany();
		key.setCardCompanyId(cardCompanyId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_CARD_COMPANY.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int countByExample(CardCompanyExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_CARD_COMPANY.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int updateByExampleSelective(CardCompany record,
			CardCompanyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_CARD_COMPANY.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	public int updateByExample(CardCompany record, CardCompanyExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_CARD_COMPANY.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_CARD_COMPANY
	 * 
	 * @abatorgenerated Sun Sep 26 15:53:52 CST 2010
	 */
	private static class UpdateByExampleParms extends CardCompanyExample {
		private Object record;

		public UpdateByExampleParms(Object record, CardCompanyExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}