package com.huateng.framework.db.ibatis.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.huateng.framework.db.ibatis.model.EntitySystemParameter;
import com.huateng.framework.db.ibatis.model.EntitySystemParameterExample;
import com.huateng.framework.db.ibatis.model.EntitySystemParameterKey;

public class EntitySystemParameterDAOImpl extends SqlMapClientDaoSupport
		implements EntitySystemParameterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public EntitySystemParameterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public void insert(EntitySystemParameter record) {
		getSqlMapClientTemplate().insert(
				"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int updateByPrimaryKey(EntitySystemParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int updateByPrimaryKeySelective(EntitySystemParameter record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EntitySystemParameter> selectByExample(
			EntitySystemParameterExample example) {
		List<EntitySystemParameter> list = (List<EntitySystemParameter>) getSqlMapClientTemplate()
				.queryForList(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public EntitySystemParameter selectByPrimaryKey(EntitySystemParameterKey key) {
		EntitySystemParameter record = (EntitySystemParameter) getSqlMapClientTemplate()
				.queryForObject(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int deleteByExample(EntitySystemParameterExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int deleteByPrimaryKey(EntitySystemParameterKey key) {
		int rows = getSqlMapClientTemplate()
				.delete(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int countByExample(EntitySystemParameterExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int updateByExampleSelective(EntitySystemParameter record,
			EntitySystemParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	public int updateByExample(EntitySystemParameter record,
			EntitySystemParameterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_SYSTEM_PARAMETER.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ENTITY_SYSTEM_PARAMETER
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:52 CST 2010
	 */
	private static class UpdateByExampleParms extends
			EntitySystemParameterExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EntitySystemParameterExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}