package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.EntityInvoiceAddress;
import com.huateng.framework.db.ibatis.model.EntityInvoiceAddressExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EntityInvoiceAddressDAOImpl extends SqlMapClientDaoSupport
		implements EntityInvoiceAddressDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public EntityInvoiceAddressDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public void insert(EntityInvoiceAddress record) {
		getSqlMapClientTemplate().insert(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int updateByPrimaryKey(EntityInvoiceAddress record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int updateByPrimaryKeySelective(EntityInvoiceAddress record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EntityInvoiceAddress> selectByExample(
			EntityInvoiceAddressExample example) {
		List<EntityInvoiceAddress> list = (List<EntityInvoiceAddress>) getSqlMapClientTemplate()
				.queryForList(
						"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public EntityInvoiceAddress selectByPrimaryKey(String invoiceAddressId) {
		EntityInvoiceAddress key = new EntityInvoiceAddress();
		key.setInvoiceAddressId(invoiceAddressId);
		EntityInvoiceAddress record = (EntityInvoiceAddress) getSqlMapClientTemplate()
				.queryForObject(
						"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int deleteByExample(EntityInvoiceAddressExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int deleteByPrimaryKey(String invoiceAddressId) {
		EntityInvoiceAddress key = new EntityInvoiceAddress();
		key.setInvoiceAddressId(invoiceAddressId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int countByExample(EntityInvoiceAddressExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int updateByExampleSelective(EntityInvoiceAddress record,
			EntityInvoiceAddressExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	public int updateByExample(EntityInvoiceAddress record,
			EntityInvoiceAddressExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_INVOICE_ADDRESS.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	private static class UpdateByExampleParms extends
			EntityInvoiceAddressExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EntityInvoiceAddressExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}