package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.EntityStock;
import com.huateng.framework.db.ibatis.model.EntityStockExample;
import java.util.List;

public interface EntityStockDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	void insert(EntityStock record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int updateByPrimaryKey(EntityStock record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int updateByPrimaryKeySelective(EntityStock record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	List<EntityStock> selectByExample(EntityStockExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	EntityStock selectByPrimaryKey(String cardNo);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int deleteByExample(EntityStockExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int deleteByPrimaryKey(String cardNo);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int countByExample(EntityStockExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int updateByExampleSelective(EntityStock record, EntityStockExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK
	 * 
	 * @abatorgenerated Thu Jan 13 14:19:16 CST 2011
	 */
	int updateByExample(EntityStock record, EntityStockExample example);
}