package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.InsTransPriv;
import com.huateng.framework.db.ibatis.model.InsTransPrivExample;
import com.huateng.framework.db.ibatis.model.InsTransPrivKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class InsTransPrivDAOImpl extends SqlMapClientDaoSupport implements
		InsTransPrivDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public InsTransPrivDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public void insert(InsTransPriv record) {
		getSqlMapClientTemplate().insert(
				"TBL_INS_TRANS_PRIV.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int updateByPrimaryKey(InsTransPriv record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TBL_INS_TRANS_PRIV.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int updateByPrimaryKeySelective(InsTransPriv record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TBL_INS_TRANS_PRIV.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<InsTransPriv> selectByExample(InsTransPrivExample example) {
		List<InsTransPriv> list = (List<InsTransPriv>) getSqlMapClientTemplate()
				.queryForList(
						"TBL_INS_TRANS_PRIV.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public InsTransPriv selectByPrimaryKey(InsTransPrivKey key) {
		InsTransPriv record = (InsTransPriv) getSqlMapClientTemplate()
				.queryForObject(
						"TBL_INS_TRANS_PRIV.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int deleteByExample(InsTransPrivExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TBL_INS_TRANS_PRIV.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int deleteByPrimaryKey(InsTransPrivKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"TBL_INS_TRANS_PRIV.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int countByExample(InsTransPrivExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TBL_INS_TRANS_PRIV.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int updateByExampleSelective(InsTransPriv record,
			InsTransPrivExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TBL_INS_TRANS_PRIV.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	public int updateByExample(InsTransPriv record, InsTransPrivExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TBL_INS_TRANS_PRIV.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TBL_INS_TRANS_PRIV
	 * 
	 * @abatorgenerated Wed Dec 28 14:51:12 CST 2011
	 */
	private static class UpdateByExampleParms extends InsTransPrivExample {
		private Object record;

		public UpdateByExampleParms(Object record, InsTransPrivExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}