package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.IssChnl;
import com.huateng.framework.db.ibatis.model.IssChnlExample;
import com.huateng.framework.db.ibatis.model.IssChnlKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IssChnlDAOImpl extends SqlMapClientDaoSupport implements
		IssChnlDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public IssChnlDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public void insert(IssChnl record) {
		getSqlMapClientTemplate().insert("TB_ISS_CHNL.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int updateByPrimaryKey(IssChnl record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ISS_CHNL.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int updateByPrimaryKeySelective(IssChnl record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ISS_CHNL.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	@SuppressWarnings("unchecked")
	public List<IssChnl> selectByExample(IssChnlExample example) {
		List<IssChnl> list = (List<IssChnl>) getSqlMapClientTemplate()
				.queryForList("TB_ISS_CHNL.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public IssChnl selectByPrimaryKey(IssChnlKey key) {
		IssChnl record = (IssChnl) getSqlMapClientTemplate().queryForObject(
				"TB_ISS_CHNL.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int deleteByExample(IssChnlExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ISS_CHNL.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int deleteByPrimaryKey(IssChnlKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ISS_CHNL.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int countByExample(IssChnlExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ISS_CHNL.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int updateByExampleSelective(IssChnl record, IssChnlExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ISS_CHNL.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	public int updateByExample(IssChnl record, IssChnlExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ISS_CHNL.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ISS_CHNL
	 * 
	 * @abatorgenerated Mon Feb 20 09:43:01 CST 2012
	 */
	private static class UpdateByExampleParms extends IssChnlExample {
		private Object record;

		public UpdateByExampleParms(Object record, IssChnlExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}