package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.ProductCardBin;
import com.huateng.framework.db.ibatis.model.ProductCardBinExample;
import com.huateng.framework.db.ibatis.model.ProductCardBinKey;
import java.util.List;

public interface ProductCardBinDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	void insert(ProductCardBin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int updateByPrimaryKey(ProductCardBin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int updateByPrimaryKeySelective(ProductCardBin record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	List<ProductCardBin> selectByExample(ProductCardBinExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	ProductCardBin selectByPrimaryKey(ProductCardBinKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int deleteByExample(ProductCardBinExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int deleteByPrimaryKey(ProductCardBinKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int countByExample(ProductCardBinExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int updateByExampleSelective(ProductCardBin record,
			ProductCardBinExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT_CARD_BIN
	 * 
	 * @abatorgenerated Fri Mar 04 11:28:35 CST 2011
	 */
	int updateByExample(ProductCardBin record, ProductCardBinExample example);
}