package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.SellOrderOrigCardList;
import com.huateng.framework.db.ibatis.model.SellOrderOrigCardListExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SellOrderOrigCardListDAOImpl extends SqlMapClientDaoSupport
		implements SellOrderOrigCardListDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public SellOrderOrigCardListDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public void insert(SellOrderOrigCardList record) {
		getSqlMapClientTemplate().insert(
				"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<SellOrderOrigCardList> selectByExample(
			SellOrderOrigCardListExample example) {
		List<SellOrderOrigCardList> list = (List<SellOrderOrigCardList>) getSqlMapClientTemplate()
				.queryForList(
						"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public int deleteByExample(SellOrderOrigCardListExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public int countByExample(SellOrderOrigCardListExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public int updateByExampleSelective(SellOrderOrigCardList record,
			SellOrderOrigCardListExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerate_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	public int updateByExample(SellOrderOrigCardList record,
			SellOrderOrigCardListExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_ORDER_ORIGCARD_LIST.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table MNGDB.TB_SELL_ORDER_ORIGCARD_LIST
	 * 
	 * @abatorgenerated Fri Nov 25 18:08:40 CST 2011
	 */
	private static class UpdateByExampleParms extends
			SellOrderOrigCardListExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				SellOrderOrigCardListExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}