package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.SellProdContract;
import com.huateng.framework.db.ibatis.model.SellProdContractExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SellProdContractDAOImpl extends SqlMapClientDaoSupport implements
		SellProdContractDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public SellProdContractDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public void insert(SellProdContract record) {
		getSqlMapClientTemplate().insert(
				"TB_SELL_PROD_CONTRACT.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int updateByPrimaryKey(SellProdContract record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_PROD_CONTRACT.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int updateByPrimaryKeySelective(SellProdContract record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<SellProdContract> selectByExample(
			SellProdContractExample example) {
		List<SellProdContract> list = (List<SellProdContract>) getSqlMapClientTemplate()
				.queryForList(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public SellProdContract selectByPrimaryKey(String id) {
		SellProdContract key = new SellProdContract();
		key.setId(id);
		SellProdContract record = (SellProdContract) getSqlMapClientTemplate()
				.queryForObject(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int deleteByExample(SellProdContractExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELL_PROD_CONTRACT.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		SellProdContract key = new SellProdContract();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_deleteByPrimaryKey",
						key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int countByExample(SellProdContractExample example) {
		Integer count = (Integer) getSqlMapClientTemplate()
				.queryForObject(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_countByExample",
						example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int updateByExampleSelective(SellProdContract record,
			SellProdContractExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_SELL_PROD_CONTRACT.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	public int updateByExample(SellProdContract record,
			SellProdContractExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELL_PROD_CONTRACT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_SELL_PROD_CONTRACT
	 * 
	 * @abatorgenerated Sat Nov 20 13:52:37 CST 2010
	 */
	private static class UpdateByExampleParms extends SellProdContractExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				SellProdContractExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}