package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.EntityContact;
import com.allinfinance.prepay.model.EntityContactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntityContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int countByExample(EntityContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int deleteByExample(EntityContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int insert(EntityContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int insertSelective(EntityContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    List<EntityContact> selectByExample(EntityContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") EntityContact record, @Param("example") EntityContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_CONTACT
     *
     * @mbggenerated Mon Apr 25 14:42:01 CST 2016
     */
    int updateByExample(@Param("record") EntityContact record, @Param("example") EntityContactExample example);
}