package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.EntityDictInfo;
import com.allinfinance.prepay.model.EntityDictInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntityDictInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int countByExample(EntityDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int deleteByExample(EntityDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int insert(EntityDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int insertSelective(EntityDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    List<EntityDictInfo> selectByExample(EntityDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") EntityDictInfo record, @Param("example") EntityDictInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DICT_INFO
     *
     * @mbggenerated Wed Jun 21 14:49:49 CST 2017
     */
    int updateByExample(@Param("record") EntityDictInfo record, @Param("example") EntityDictInfoExample example);
}