package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.InvoiceCompany;
import com.allinfinance.prepay.model.InvoiceCompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvoiceCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int countByExample(InvoiceCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int deleteByExample(InvoiceCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int insert(InvoiceCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int insertSelective(InvoiceCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    List<InvoiceCompany> selectByExample(InvoiceCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") InvoiceCompany record, @Param("example") InvoiceCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_INVOICE_COMPANY
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int updateByExample(@Param("record") InvoiceCompany record, @Param("example") InvoiceCompanyExample example);
}