package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.ProductPackage;
import com.allinfinance.prepay.model.ProductPackageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int countByExample(ProductPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int deleteByExample(ProductPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int insert(ProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int insertSelective(ProductPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    List<ProductPackage> selectByExample(ProductPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProductPackage record, @Param("example") ProductPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_REL_PRODUCT_PACKAGE
     *
     * @mbggenerated Mon Apr 25 10:05:50 CST 2016
     */
    int updateByExample(@Param("record") ProductPackage record, @Param("example") ProductPackageExample example);
}