package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.SellOrderCardList;
import com.allinfinance.prepay.model.SellOrderCardListExample;
import com.allinfinance.univer.seller.order.dto.SellOrderCardListDTO;
import com.allinfinance.univer.seller.order.dto.SellOrderListDTO;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SellOrderCardListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int countByExample(SellOrderCardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int deleteByExample(SellOrderCardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int insert(SellOrderCardList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int insertSelective(SellOrderCardList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    List<SellOrderCardList> selectByExample(SellOrderCardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int updateByExampleSelective(@Param("record") SellOrderCardList record, @Param("example") SellOrderCardListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ORDER_CARD_LIST
     *
     * @mbggenerated Tue Apr 26 17:16:38 CST 2016
     */
    int updateByExample(@Param("record") SellOrderCardList record, @Param("example") SellOrderCardListExample example);
    
    List<SellOrderListDTO> selectByOrderId(String orderId);
}