package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.Merchant;
import com.huateng.framework.db.ibatis.model.MerchantExample;
import com.huateng.framework.db.ibatis.model.MerchantKey;
import java.util.List;

public interface MerchantDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	void insert(Merchant record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int updateByPrimaryKey(Merchant record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int updateByPrimaryKeySelective(Merchant record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	List<Merchant> selectByExample(MerchantExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	Merchant selectByPrimaryKey(MerchantKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int deleteByExample(MerchantExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int deleteByPrimaryKey(MerchantKey key);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int countByExample(MerchantExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int updateByExampleSelective(Merchant record, MerchantExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TXNDB.TB_MERCHANT
	 * 
	 * @abatorgenerated Wed Feb 08 15:04:51 CST 2012
	 */
	int updateByExample(Merchant record, MerchantExample example);
}