package com.huateng.framework.db.ibatis.dao;

import com.huateng.framework.db.ibatis.model.Resource;
import com.huateng.framework.db.ibatis.model.ResourceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ResourceDAOImpl extends SqlMapClientDaoSupport implements
		ResourceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public ResourceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public void insert(Resource record) {
		getSqlMapClientTemplate().insert("TB_RESOURCE.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int updateByPrimaryKey(Resource record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_RESOURCE.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int updateByPrimaryKeySelective(Resource record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_RESOURCE.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Resource> selectByExample(ResourceExample example) {
		List<Resource> list = (List<Resource>) getSqlMapClientTemplate()
				.queryForList("TB_RESOURCE.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public Resource selectByPrimaryKey(String resourceId) {
		Resource key = new Resource();
		key.setResourceId(resourceId);
		Resource record = (Resource) getSqlMapClientTemplate().queryForObject(
				"TB_RESOURCE.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int deleteByExample(ResourceExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_RESOURCE.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int deleteByPrimaryKey(String resourceId) {
		Resource key = new Resource();
		key.setResourceId(resourceId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_RESOURCE.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int countByExample(ResourceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_RESOURCE.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int updateByExampleSelective(Resource record, ResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_RESOURCE.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	public int updateByExample(Resource record, ResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_RESOURCE.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_RESOURCE
	 * 
	 * @abatorgenerated Sun Sep 26 15:56:28 CST 2010
	 */
	private static class UpdateByExampleParms extends ResourceExample {
		private Object record;

		public UpdateByExampleParms(Object record, ResourceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}