package com.huateng.framework.ibatis.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EntityStockOperaterExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public EntityStockOperaterExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	protected EntityStockOperaterExample(EntityStockOperaterExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andOperaterIdIsNull() {
			addCriterion("OPERATER_ID is null");
			return this;
		}

		public Criteria andOperaterIdIsNotNull() {
			addCriterion("OPERATER_ID is not null");
			return this;
		}

		public Criteria andOperaterIdEqualTo(String value) {
			addCriterion("OPERATER_ID =", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdNotEqualTo(String value) {
			addCriterion("OPERATER_ID <>", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdGreaterThan(String value) {
			addCriterion("OPERATER_ID >", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATER_ID >=", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdLessThan(String value) {
			addCriterion("OPERATER_ID <", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdLessThanOrEqualTo(String value) {
			addCriterion("OPERATER_ID <=", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdLike(String value) {
			addCriterion("OPERATER_ID like", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdNotLike(String value) {
			addCriterion("OPERATER_ID not like", value, "operaterId");
			return this;
		}

		public Criteria andOperaterIdIn(List<String> values) {
			addCriterion("OPERATER_ID in", values, "operaterId");
			return this;
		}

		public Criteria andOperaterIdNotIn(List<String> values) {
			addCriterion("OPERATER_ID not in", values, "operaterId");
			return this;
		}

		public Criteria andOperaterIdBetween(String value1, String value2) {
			addCriterion("OPERATER_ID between", value1, value2, "operaterId");
			return this;
		}

		public Criteria andOperaterIdNotBetween(String value1, String value2) {
			addCriterion("OPERATER_ID not between", value1, value2,
					"operaterId");
			return this;
		}

		public Criteria andOperaterTypeIsNull() {
			addCriterion("OPERATER_TYPE is null");
			return this;
		}

		public Criteria andOperaterTypeIsNotNull() {
			addCriterion("OPERATER_TYPE is not null");
			return this;
		}

		public Criteria andOperaterTypeEqualTo(String value) {
			addCriterion("OPERATER_TYPE =", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeNotEqualTo(String value) {
			addCriterion("OPERATER_TYPE <>", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeGreaterThan(String value) {
			addCriterion("OPERATER_TYPE >", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATER_TYPE >=", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeLessThan(String value) {
			addCriterion("OPERATER_TYPE <", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeLessThanOrEqualTo(String value) {
			addCriterion("OPERATER_TYPE <=", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeLike(String value) {
			addCriterion("OPERATER_TYPE like", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeNotLike(String value) {
			addCriterion("OPERATER_TYPE not like", value, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeIn(List<String> values) {
			addCriterion("OPERATER_TYPE in", values, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeNotIn(List<String> values) {
			addCriterion("OPERATER_TYPE not in", values, "operaterType");
			return this;
		}

		public Criteria andOperaterTypeBetween(String value1, String value2) {
			addCriterion("OPERATER_TYPE between", value1, value2,
					"operaterType");
			return this;
		}

		public Criteria andOperaterTypeNotBetween(String value1, String value2) {
			addCriterion("OPERATER_TYPE not between", value1, value2,
					"operaterType");
			return this;
		}

		public Criteria andCardNoIsNull() {
			addCriterion("CARD_NO is null");
			return this;
		}

		public Criteria andCardNoIsNotNull() {
			addCriterion("CARD_NO is not null");
			return this;
		}

		public Criteria andCardNoEqualTo(String value) {
			addCriterion("CARD_NO =", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotEqualTo(String value) {
			addCriterion("CARD_NO <>", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThan(String value) {
			addCriterion("CARD_NO >", value, "cardNo");
			return this;
		}

		public Criteria andCardNoGreaterThanOrEqualTo(String value) {
			addCriterion("CARD_NO >=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThan(String value) {
			addCriterion("CARD_NO <", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLessThanOrEqualTo(String value) {
			addCriterion("CARD_NO <=", value, "cardNo");
			return this;
		}

		public Criteria andCardNoLike(String value) {
			addCriterion("CARD_NO like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoNotLike(String value) {
			addCriterion("CARD_NO not like", value, "cardNo");
			return this;
		}

		public Criteria andCardNoIn(List<String> values) {
			addCriterion("CARD_NO in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoNotIn(List<String> values) {
			addCriterion("CARD_NO not in", values, "cardNo");
			return this;
		}

		public Criteria andCardNoBetween(String value1, String value2) {
			addCriterion("CARD_NO between", value1, value2, "cardNo");
			return this;
		}

		public Criteria andCardNoNotBetween(String value1, String value2) {
			addCriterion("CARD_NO not between", value1, value2, "cardNo");
			return this;
		}

		public Criteria andEntityIdIsNull() {
			addCriterion("ENTITY_ID is null");
			return this;
		}

		public Criteria andEntityIdIsNotNull() {
			addCriterion("ENTITY_ID is not null");
			return this;
		}

		public Criteria andEntityIdEqualTo(String value) {
			addCriterion("ENTITY_ID =", value, "entityId");
			return this;
		}

		public Criteria andEntityIdNotEqualTo(String value) {
			addCriterion("ENTITY_ID <>", value, "entityId");
			return this;
		}

		public Criteria andEntityIdGreaterThan(String value) {
			addCriterion("ENTITY_ID >", value, "entityId");
			return this;
		}

		public Criteria andEntityIdGreaterThanOrEqualTo(String value) {
			addCriterion("ENTITY_ID >=", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLessThan(String value) {
			addCriterion("ENTITY_ID <", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLessThanOrEqualTo(String value) {
			addCriterion("ENTITY_ID <=", value, "entityId");
			return this;
		}

		public Criteria andEntityIdLike(String value) {
			addCriterion("ENTITY_ID like", value, "entityId");
			return this;
		}

		public Criteria andEntityIdNotLike(String value) {
			addCriterion("ENTITY_ID not like", value, "entityId");
			return this;
		}

		public Criteria andEntityIdIn(List<String> values) {
			addCriterion("ENTITY_ID in", values, "entityId");
			return this;
		}

		public Criteria andEntityIdNotIn(List<String> values) {
			addCriterion("ENTITY_ID not in", values, "entityId");
			return this;
		}

		public Criteria andEntityIdBetween(String value1, String value2) {
			addCriterion("ENTITY_ID between", value1, value2, "entityId");
			return this;
		}

		public Criteria andEntityIdNotBetween(String value1, String value2) {
			addCriterion("ENTITY_ID not between", value1, value2, "entityId");
			return this;
		}

		public Criteria andFuncationRoleIdIsNull() {
			addCriterion("FUNCATION_ROLE_ID is null");
			return this;
		}

		public Criteria andFuncationRoleIdIsNotNull() {
			addCriterion("FUNCATION_ROLE_ID is not null");
			return this;
		}

		public Criteria andFuncationRoleIdEqualTo(String value) {
			addCriterion("FUNCATION_ROLE_ID =", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdNotEqualTo(String value) {
			addCriterion("FUNCATION_ROLE_ID <>", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdGreaterThan(String value) {
			addCriterion("FUNCATION_ROLE_ID >", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdGreaterThanOrEqualTo(String value) {
			addCriterion("FUNCATION_ROLE_ID >=", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdLessThan(String value) {
			addCriterion("FUNCATION_ROLE_ID <", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdLessThanOrEqualTo(String value) {
			addCriterion("FUNCATION_ROLE_ID <=", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdLike(String value) {
			addCriterion("FUNCATION_ROLE_ID like", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdNotLike(String value) {
			addCriterion("FUNCATION_ROLE_ID not like", value, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdIn(List<String> values) {
			addCriterion("FUNCATION_ROLE_ID in", values, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdNotIn(List<String> values) {
			addCriterion("FUNCATION_ROLE_ID not in", values, "funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdBetween(String value1, String value2) {
			addCriterion("FUNCATION_ROLE_ID between", value1, value2,
					"funcationRoleId");
			return this;
		}

		public Criteria andFuncationRoleIdNotBetween(String value1,
				String value2) {
			addCriterion("FUNCATION_ROLE_ID not between", value1, value2,
					"funcationRoleId");
			return this;
		}

		public Criteria andOrderIdIsNull() {
			addCriterion("ORDER_ID is null");
			return this;
		}

		public Criteria andOrderIdIsNotNull() {
			addCriterion("ORDER_ID is not null");
			return this;
		}

		public Criteria andOrderIdEqualTo(String value) {
			addCriterion("ORDER_ID =", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotEqualTo(String value) {
			addCriterion("ORDER_ID <>", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThan(String value) {
			addCriterion("ORDER_ID >", value, "orderId");
			return this;
		}

		public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_ID >=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThan(String value) {
			addCriterion("ORDER_ID <", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLessThanOrEqualTo(String value) {
			addCriterion("ORDER_ID <=", value, "orderId");
			return this;
		}

		public Criteria andOrderIdLike(String value) {
			addCriterion("ORDER_ID like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdNotLike(String value) {
			addCriterion("ORDER_ID not like", value, "orderId");
			return this;
		}

		public Criteria andOrderIdIn(List<String> values) {
			addCriterion("ORDER_ID in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdNotIn(List<String> values) {
			addCriterion("ORDER_ID not in", values, "orderId");
			return this;
		}

		public Criteria andOrderIdBetween(String value1, String value2) {
			addCriterion("ORDER_ID between", value1, value2, "orderId");
			return this;
		}

		public Criteria andOrderIdNotBetween(String value1, String value2) {
			addCriterion("ORDER_ID not between", value1, value2, "orderId");
			return this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2,
					"modifyUser");
			return this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return this;
		}

		public Criteria andModifyTimeEqualTo(String value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotEqualTo(String value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThan(String value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThan(String value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLike(String value) {
			addCriterion("MODIFY_TIME like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotLike(String value) {
			addCriterion("MODIFY_TIME not like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeIn(List<String> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotIn(List<String> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME not between", value1, value2,
					"modifyTime");
			return this;
		}

		public Criteria andDataStateIsNull() {
			addCriterion("DATA_STATE is null");
			return this;
		}

		public Criteria andDataStateIsNotNull() {
			addCriterion("DATA_STATE is not null");
			return this;
		}

		public Criteria andDataStateEqualTo(String value) {
			addCriterion("DATA_STATE =", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotEqualTo(String value) {
			addCriterion("DATA_STATE <>", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThan(String value) {
			addCriterion("DATA_STATE >", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_STATE >=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThan(String value) {
			addCriterion("DATA_STATE <", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThanOrEqualTo(String value) {
			addCriterion("DATA_STATE <=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLike(String value) {
			addCriterion("DATA_STATE like", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotLike(String value) {
			addCriterion("DATA_STATE not like", value, "dataState");
			return this;
		}

		public Criteria andDataStateIn(List<String> values) {
			addCriterion("DATA_STATE in", values, "dataState");
			return this;
		}

		public Criteria andDataStateNotIn(List<String> values) {
			addCriterion("DATA_STATE not in", values, "dataState");
			return this;
		}

		public Criteria andDataStateBetween(String value1, String value2) {
			addCriterion("DATA_STATE between", value1, value2, "dataState");
			return this;
		}

		public Criteria andDataStateNotBetween(String value1, String value2) {
			addCriterion("DATA_STATE not between", value1, value2, "dataState");
			return this;
		}

		public Criteria andStockStateIsNull() {
			addCriterion("STOCK_STATE is null");
			return this;
		}

		public Criteria andStockStateIsNotNull() {
			addCriterion("STOCK_STATE is not null");
			return this;
		}

		public Criteria andStockStateEqualTo(String value) {
			addCriterion("STOCK_STATE =", value, "stockState");
			return this;
		}

		public Criteria andStockStateNotEqualTo(String value) {
			addCriterion("STOCK_STATE <>", value, "stockState");
			return this;
		}

		public Criteria andStockStateGreaterThan(String value) {
			addCriterion("STOCK_STATE >", value, "stockState");
			return this;
		}

		public Criteria andStockStateGreaterThanOrEqualTo(String value) {
			addCriterion("STOCK_STATE >=", value, "stockState");
			return this;
		}

		public Criteria andStockStateLessThan(String value) {
			addCriterion("STOCK_STATE <", value, "stockState");
			return this;
		}

		public Criteria andStockStateLessThanOrEqualTo(String value) {
			addCriterion("STOCK_STATE <=", value, "stockState");
			return this;
		}

		public Criteria andStockStateLike(String value) {
			addCriterion("STOCK_STATE like", value, "stockState");
			return this;
		}

		public Criteria andStockStateNotLike(String value) {
			addCriterion("STOCK_STATE not like", value, "stockState");
			return this;
		}

		public Criteria andStockStateIn(List<String> values) {
			addCriterion("STOCK_STATE in", values, "stockState");
			return this;
		}

		public Criteria andStockStateNotIn(List<String> values) {
			addCriterion("STOCK_STATE not in", values, "stockState");
			return this;
		}

		public Criteria andStockStateBetween(String value1, String value2) {
			addCriterion("STOCK_STATE between", value1, value2, "stockState");
			return this;
		}

		public Criteria andStockStateNotBetween(String value1, String value2) {
			addCriterion("STOCK_STATE not between", value1, value2,
					"stockState");
			return this;
		}

		public Criteria andOrderFlowNodeIsNull() {
			addCriterion("ORDER_FLOW_NODE is null");
			return this;
		}

		public Criteria andOrderFlowNodeIsNotNull() {
			addCriterion("ORDER_FLOW_NODE is not null");
			return this;
		}

		public Criteria andOrderFlowNodeEqualTo(String value) {
			addCriterion("ORDER_FLOW_NODE =", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeNotEqualTo(String value) {
			addCriterion("ORDER_FLOW_NODE <>", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeGreaterThan(String value) {
			addCriterion("ORDER_FLOW_NODE >", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeGreaterThanOrEqualTo(String value) {
			addCriterion("ORDER_FLOW_NODE >=", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeLessThan(String value) {
			addCriterion("ORDER_FLOW_NODE <", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeLessThanOrEqualTo(String value) {
			addCriterion("ORDER_FLOW_NODE <=", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeLike(String value) {
			addCriterion("ORDER_FLOW_NODE like", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeNotLike(String value) {
			addCriterion("ORDER_FLOW_NODE not like", value, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeIn(List<String> values) {
			addCriterion("ORDER_FLOW_NODE in", values, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeNotIn(List<String> values) {
			addCriterion("ORDER_FLOW_NODE not in", values, "orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeBetween(String value1, String value2) {
			addCriterion("ORDER_FLOW_NODE between", value1, value2,
					"orderFlowNode");
			return this;
		}

		public Criteria andOrderFlowNodeNotBetween(String value1, String value2) {
			addCriterion("ORDER_FLOW_NODE not between", value1, value2,
					"orderFlowNode");
			return this;
		}
	}
}