package com.huateng.framework.db.ibatis.model;

public class DictType {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_DICT_TYPE.DICT_TYPE_CODE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	private String dictTypeCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_DICT_TYPE.DICT_TYPE_NAME
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	private String dictTypeName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_DICT_TYPE.DICT_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	private String dictRole;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column TB_DICT_TYPE.UPDATE_FLAG
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	private String updateFlag;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_DICT_TYPE.DICT_TYPE_CODE
	 * 
	 * @return the value of TB_DICT_TYPE.DICT_TYPE_CODE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public String getDictTypeCode() {
		return dictTypeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_DICT_TYPE.DICT_TYPE_CODE
	 * 
	 * @param dictTypeCode
	 *            the value for TB_DICT_TYPE.DICT_TYPE_CODE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public void setDictTypeCode(String dictTypeCode) {
		this.dictTypeCode = dictTypeCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_DICT_TYPE.DICT_TYPE_NAME
	 * 
	 * @return the value of TB_DICT_TYPE.DICT_TYPE_NAME
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public String getDictTypeName() {
		return dictTypeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_DICT_TYPE.DICT_TYPE_NAME
	 * 
	 * @param dictTypeName
	 *            the value for TB_DICT_TYPE.DICT_TYPE_NAME
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public void setDictTypeName(String dictTypeName) {
		this.dictTypeName = dictTypeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_DICT_TYPE.DICT_ROLE
	 * 
	 * @return the value of TB_DICT_TYPE.DICT_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public String getDictRole() {
		return dictRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_DICT_TYPE.DICT_ROLE
	 * 
	 * @param dictRole
	 *            the value for TB_DICT_TYPE.DICT_ROLE
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public void setDictRole(String dictRole) {
		this.dictRole = dictRole;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column TB_DICT_TYPE.UPDATE_FLAG
	 * 
	 * @return the value of TB_DICT_TYPE.UPDATE_FLAG
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public String getUpdateFlag() {
		return updateFlag;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column TB_DICT_TYPE.UPDATE_FLAG
	 * 
	 * @param updateFlag
	 *            the value for TB_DICT_TYPE.UPDATE_FLAG
	 * 
	 * @abatorgenerated Sun Sep 26 15:55:37 CST 2010
	 */
	public void setUpdateFlag(String updateFlag) {
		this.updateFlag = updateFlag;
	}
}