package com.huateng.framework.db.ibatis.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LoyaltyContractExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public LoyaltyContractExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	protected LoyaltyContractExample(LoyaltyContractExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_LOYALTY_CONTRACT
	 * 
	 * @abatorgenerated Thu Nov 18 15:31:30 CST 2010
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;

		protected List<Map<String, Object>> criteriaWithSingleValue;

		protected List<Map<String, Object>> criteriaWithListValue;

		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andLoyaltyContractIdIsNull() {
			addCriterion("LOYALTY_CONTRACT_ID is null");
			return this;
		}

		public Criteria andLoyaltyContractIdIsNotNull() {
			addCriterion("LOYALTY_CONTRACT_ID is not null");
			return this;
		}

		public Criteria andLoyaltyContractIdEqualTo(String value) {
			addCriterion("LOYALTY_CONTRACT_ID =", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdNotEqualTo(String value) {
			addCriterion("LOYALTY_CONTRACT_ID <>", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdGreaterThan(String value) {
			addCriterion("LOYALTY_CONTRACT_ID >", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdGreaterThanOrEqualTo(String value) {
			addCriterion("LOYALTY_CONTRACT_ID >=", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdLessThan(String value) {
			addCriterion("LOYALTY_CONTRACT_ID <", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdLessThanOrEqualTo(String value) {
			addCriterion("LOYALTY_CONTRACT_ID <=", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdLike(String value) {
			addCriterion("LOYALTY_CONTRACT_ID like", value, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdNotLike(String value) {
			addCriterion("LOYALTY_CONTRACT_ID not like", value,
					"loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdIn(List<String> values) {
			addCriterion("LOYALTY_CONTRACT_ID in", values, "loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdNotIn(List<String> values) {
			addCriterion("LOYALTY_CONTRACT_ID not in", values,
					"loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdBetween(String value1, String value2) {
			addCriterion("LOYALTY_CONTRACT_ID between", value1, value2,
					"loyaltyContractId");
			return this;
		}

		public Criteria andLoyaltyContractIdNotBetween(String value1,
				String value2) {
			addCriterion("LOYALTY_CONTRACT_ID not between", value1, value2,
					"loyaltyContractId");
			return this;
		}

		public Criteria andRuleNoIsNull() {
			addCriterion("RULE_NO is null");
			return this;
		}

		public Criteria andRuleNoIsNotNull() {
			addCriterion("RULE_NO is not null");
			return this;
		}

		public Criteria andRuleNoEqualTo(String value) {
			addCriterion("RULE_NO =", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoNotEqualTo(String value) {
			addCriterion("RULE_NO <>", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoGreaterThan(String value) {
			addCriterion("RULE_NO >", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoGreaterThanOrEqualTo(String value) {
			addCriterion("RULE_NO >=", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoLessThan(String value) {
			addCriterion("RULE_NO <", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoLessThanOrEqualTo(String value) {
			addCriterion("RULE_NO <=", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoLike(String value) {
			addCriterion("RULE_NO like", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoNotLike(String value) {
			addCriterion("RULE_NO not like", value, "ruleNo");
			return this;
		}

		public Criteria andRuleNoIn(List<String> values) {
			addCriterion("RULE_NO in", values, "ruleNo");
			return this;
		}

		public Criteria andRuleNoNotIn(List<String> values) {
			addCriterion("RULE_NO not in", values, "ruleNo");
			return this;
		}

		public Criteria andRuleNoBetween(String value1, String value2) {
			addCriterion("RULE_NO between", value1, value2, "ruleNo");
			return this;
		}

		public Criteria andRuleNoNotBetween(String value1, String value2) {
			addCriterion("RULE_NO not between", value1, value2, "ruleNo");
			return this;
		}

		public Criteria andContractBuyerIsNull() {
			addCriterion("CONTRACT_BUYER is null");
			return this;
		}

		public Criteria andContractBuyerIsNotNull() {
			addCriterion("CONTRACT_BUYER is not null");
			return this;
		}

		public Criteria andContractBuyerEqualTo(String value) {
			addCriterion("CONTRACT_BUYER =", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerNotEqualTo(String value) {
			addCriterion("CONTRACT_BUYER <>", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerGreaterThan(String value) {
			addCriterion("CONTRACT_BUYER >", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerGreaterThanOrEqualTo(String value) {
			addCriterion("CONTRACT_BUYER >=", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerLessThan(String value) {
			addCriterion("CONTRACT_BUYER <", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerLessThanOrEqualTo(String value) {
			addCriterion("CONTRACT_BUYER <=", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerLike(String value) {
			addCriterion("CONTRACT_BUYER like", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerNotLike(String value) {
			addCriterion("CONTRACT_BUYER not like", value, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerIn(List<String> values) {
			addCriterion("CONTRACT_BUYER in", values, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerNotIn(List<String> values) {
			addCriterion("CONTRACT_BUYER not in", values, "contractBuyer");
			return this;
		}

		public Criteria andContractBuyerBetween(String value1, String value2) {
			addCriterion("CONTRACT_BUYER between", value1, value2,
					"contractBuyer");
			return this;
		}

		public Criteria andContractBuyerNotBetween(String value1, String value2) {
			addCriterion("CONTRACT_BUYER not between", value1, value2,
					"contractBuyer");
			return this;
		}

		public Criteria andDeliveryFeeIsNull() {
			addCriterion("DELIVERY_FEE is null");
			return this;
		}

		public Criteria andDeliveryFeeIsNotNull() {
			addCriterion("DELIVERY_FEE is not null");
			return this;
		}

		public Criteria andDeliveryFeeEqualTo(String value) {
			addCriterion("DELIVERY_FEE =", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeNotEqualTo(String value) {
			addCriterion("DELIVERY_FEE <>", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeGreaterThan(String value) {
			addCriterion("DELIVERY_FEE >", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeGreaterThanOrEqualTo(String value) {
			addCriterion("DELIVERY_FEE >=", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeLessThan(String value) {
			addCriterion("DELIVERY_FEE <", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeLessThanOrEqualTo(String value) {
			addCriterion("DELIVERY_FEE <=", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeLike(String value) {
			addCriterion("DELIVERY_FEE like", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeNotLike(String value) {
			addCriterion("DELIVERY_FEE not like", value, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeIn(List<String> values) {
			addCriterion("DELIVERY_FEE in", values, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeNotIn(List<String> values) {
			addCriterion("DELIVERY_FEE not in", values, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeBetween(String value1, String value2) {
			addCriterion("DELIVERY_FEE between", value1, value2, "deliveryFee");
			return this;
		}

		public Criteria andDeliveryFeeNotBetween(String value1, String value2) {
			addCriterion("DELIVERY_FEE not between", value1, value2,
					"deliveryFee");
			return this;
		}

		public Criteria andContractSellerIsNull() {
			addCriterion("CONTRACT_SELLER is null");
			return this;
		}

		public Criteria andContractSellerIsNotNull() {
			addCriterion("CONTRACT_SELLER is not null");
			return this;
		}

		public Criteria andContractSellerEqualTo(String value) {
			addCriterion("CONTRACT_SELLER =", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerNotEqualTo(String value) {
			addCriterion("CONTRACT_SELLER <>", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerGreaterThan(String value) {
			addCriterion("CONTRACT_SELLER >", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerGreaterThanOrEqualTo(String value) {
			addCriterion("CONTRACT_SELLER >=", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerLessThan(String value) {
			addCriterion("CONTRACT_SELLER <", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerLessThanOrEqualTo(String value) {
			addCriterion("CONTRACT_SELLER <=", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerLike(String value) {
			addCriterion("CONTRACT_SELLER like", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerNotLike(String value) {
			addCriterion("CONTRACT_SELLER not like", value, "contractSeller");
			return this;
		}

		public Criteria andContractSellerIn(List<String> values) {
			addCriterion("CONTRACT_SELLER in", values, "contractSeller");
			return this;
		}

		public Criteria andContractSellerNotIn(List<String> values) {
			addCriterion("CONTRACT_SELLER not in", values, "contractSeller");
			return this;
		}

		public Criteria andContractSellerBetween(String value1, String value2) {
			addCriterion("CONTRACT_SELLER between", value1, value2,
					"contractSeller");
			return this;
		}

		public Criteria andContractSellerNotBetween(String value1, String value2) {
			addCriterion("CONTRACT_SELLER not between", value1, value2,
					"contractSeller");
			return this;
		}

		public Criteria andSmsSvcStatIsNull() {
			addCriterion("SMS_SVC_STAT is null");
			return this;
		}

		public Criteria andSmsSvcStatIsNotNull() {
			addCriterion("SMS_SVC_STAT is not null");
			return this;
		}

		public Criteria andSmsSvcStatEqualTo(String value) {
			addCriterion("SMS_SVC_STAT =", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatNotEqualTo(String value) {
			addCriterion("SMS_SVC_STAT <>", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatGreaterThan(String value) {
			addCriterion("SMS_SVC_STAT >", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatGreaterThanOrEqualTo(String value) {
			addCriterion("SMS_SVC_STAT >=", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatLessThan(String value) {
			addCriterion("SMS_SVC_STAT <", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatLessThanOrEqualTo(String value) {
			addCriterion("SMS_SVC_STAT <=", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatLike(String value) {
			addCriterion("SMS_SVC_STAT like", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatNotLike(String value) {
			addCriterion("SMS_SVC_STAT not like", value, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatIn(List<String> values) {
			addCriterion("SMS_SVC_STAT in", values, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatNotIn(List<String> values) {
			addCriterion("SMS_SVC_STAT not in", values, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatBetween(String value1, String value2) {
			addCriterion("SMS_SVC_STAT between", value1, value2, "smsSvcStat");
			return this;
		}

		public Criteria andSmsSvcStatNotBetween(String value1, String value2) {
			addCriterion("SMS_SVC_STAT not between", value1, value2,
					"smsSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatIsNull() {
			addCriterion("EMAIL_SVC_STAT is null");
			return this;
		}

		public Criteria andEmailSvcStatIsNotNull() {
			addCriterion("EMAIL_SVC_STAT is not null");
			return this;
		}

		public Criteria andEmailSvcStatEqualTo(String value) {
			addCriterion("EMAIL_SVC_STAT =", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatNotEqualTo(String value) {
			addCriterion("EMAIL_SVC_STAT <>", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatGreaterThan(String value) {
			addCriterion("EMAIL_SVC_STAT >", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL_SVC_STAT >=", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatLessThan(String value) {
			addCriterion("EMAIL_SVC_STAT <", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatLessThanOrEqualTo(String value) {
			addCriterion("EMAIL_SVC_STAT <=", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatLike(String value) {
			addCriterion("EMAIL_SVC_STAT like", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatNotLike(String value) {
			addCriterion("EMAIL_SVC_STAT not like", value, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatIn(List<String> values) {
			addCriterion("EMAIL_SVC_STAT in", values, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatNotIn(List<String> values) {
			addCriterion("EMAIL_SVC_STAT not in", values, "emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatBetween(String value1, String value2) {
			addCriterion("EMAIL_SVC_STAT between", value1, value2,
					"emailSvcStat");
			return this;
		}

		public Criteria andEmailSvcStatNotBetween(String value1, String value2) {
			addCriterion("EMAIL_SVC_STAT not between", value1, value2,
					"emailSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatIsNull() {
			addCriterion("MONSTMT_SVC_STAT is null");
			return this;
		}

		public Criteria andMonstmtSvcStatIsNotNull() {
			addCriterion("MONSTMT_SVC_STAT is not null");
			return this;
		}

		public Criteria andMonstmtSvcStatEqualTo(String value) {
			addCriterion("MONSTMT_SVC_STAT =", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatNotEqualTo(String value) {
			addCriterion("MONSTMT_SVC_STAT <>", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatGreaterThan(String value) {
			addCriterion("MONSTMT_SVC_STAT >", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatGreaterThanOrEqualTo(String value) {
			addCriterion("MONSTMT_SVC_STAT >=", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatLessThan(String value) {
			addCriterion("MONSTMT_SVC_STAT <", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatLessThanOrEqualTo(String value) {
			addCriterion("MONSTMT_SVC_STAT <=", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatLike(String value) {
			addCriterion("MONSTMT_SVC_STAT like", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatNotLike(String value) {
			addCriterion("MONSTMT_SVC_STAT not like", value, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatIn(List<String> values) {
			addCriterion("MONSTMT_SVC_STAT in", values, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatNotIn(List<String> values) {
			addCriterion("MONSTMT_SVC_STAT not in", values, "monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatBetween(String value1, String value2) {
			addCriterion("MONSTMT_SVC_STAT between", value1, value2,
					"monstmtSvcStat");
			return this;
		}

		public Criteria andMonstmtSvcStatNotBetween(String value1, String value2) {
			addCriterion("MONSTMT_SVC_STAT not between", value1, value2,
					"monstmtSvcStat");
			return this;
		}

		public Criteria andWebPayStatIsNull() {
			addCriterion("WEB_PAY_STAT is null");
			return this;
		}

		public Criteria andWebPayStatIsNotNull() {
			addCriterion("WEB_PAY_STAT is not null");
			return this;
		}

		public Criteria andWebPayStatEqualTo(String value) {
			addCriterion("WEB_PAY_STAT =", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatNotEqualTo(String value) {
			addCriterion("WEB_PAY_STAT <>", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatGreaterThan(String value) {
			addCriterion("WEB_PAY_STAT >", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatGreaterThanOrEqualTo(String value) {
			addCriterion("WEB_PAY_STAT >=", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatLessThan(String value) {
			addCriterion("WEB_PAY_STAT <", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatLessThanOrEqualTo(String value) {
			addCriterion("WEB_PAY_STAT <=", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatLike(String value) {
			addCriterion("WEB_PAY_STAT like", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatNotLike(String value) {
			addCriterion("WEB_PAY_STAT not like", value, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatIn(List<String> values) {
			addCriterion("WEB_PAY_STAT in", values, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatNotIn(List<String> values) {
			addCriterion("WEB_PAY_STAT not in", values, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatBetween(String value1, String value2) {
			addCriterion("WEB_PAY_STAT between", value1, value2, "webPayStat");
			return this;
		}

		public Criteria andWebPayStatNotBetween(String value1, String value2) {
			addCriterion("WEB_PAY_STAT not between", value1, value2,
					"webPayStat");
			return this;
		}

		public Criteria andWebSmsSvcStatIsNull() {
			addCriterion("WEB_SMS_SVC_STAT is null");
			return this;
		}

		public Criteria andWebSmsSvcStatIsNotNull() {
			addCriterion("WEB_SMS_SVC_STAT is not null");
			return this;
		}

		public Criteria andWebSmsSvcStatEqualTo(String value) {
			addCriterion("WEB_SMS_SVC_STAT =", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatNotEqualTo(String value) {
			addCriterion("WEB_SMS_SVC_STAT <>", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatGreaterThan(String value) {
			addCriterion("WEB_SMS_SVC_STAT >", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatGreaterThanOrEqualTo(String value) {
			addCriterion("WEB_SMS_SVC_STAT >=", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatLessThan(String value) {
			addCriterion("WEB_SMS_SVC_STAT <", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatLessThanOrEqualTo(String value) {
			addCriterion("WEB_SMS_SVC_STAT <=", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatLike(String value) {
			addCriterion("WEB_SMS_SVC_STAT like", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatNotLike(String value) {
			addCriterion("WEB_SMS_SVC_STAT not like", value, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatIn(List<String> values) {
			addCriterion("WEB_SMS_SVC_STAT in", values, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatNotIn(List<String> values) {
			addCriterion("WEB_SMS_SVC_STAT not in", values, "webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatBetween(String value1, String value2) {
			addCriterion("WEB_SMS_SVC_STAT between", value1, value2,
					"webSmsSvcStat");
			return this;
		}

		public Criteria andWebSmsSvcStatNotBetween(String value1, String value2) {
			addCriterion("WEB_SMS_SVC_STAT not between", value1, value2,
					"webSmsSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatIsNull() {
			addCriterion("WEB_EMAIL_SVC_STAT is null");
			return this;
		}

		public Criteria andWebEmailSvcStatIsNotNull() {
			addCriterion("WEB_EMAIL_SVC_STAT is not null");
			return this;
		}

		public Criteria andWebEmailSvcStatEqualTo(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT =", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatNotEqualTo(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT <>", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatGreaterThan(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT >", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatGreaterThanOrEqualTo(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT >=", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatLessThan(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT <", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatLessThanOrEqualTo(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT <=", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatLike(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT like", value, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatNotLike(String value) {
			addCriterion("WEB_EMAIL_SVC_STAT not like", value,
					"webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatIn(List<String> values) {
			addCriterion("WEB_EMAIL_SVC_STAT in", values, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatNotIn(List<String> values) {
			addCriterion("WEB_EMAIL_SVC_STAT not in", values, "webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatBetween(String value1, String value2) {
			addCriterion("WEB_EMAIL_SVC_STAT between", value1, value2,
					"webEmailSvcStat");
			return this;
		}

		public Criteria andWebEmailSvcStatNotBetween(String value1,
				String value2) {
			addCriterion("WEB_EMAIL_SVC_STAT not between", value1, value2,
					"webEmailSvcStat");
			return this;
		}

		public Criteria andContractStateIsNull() {
			addCriterion("CONTRACT_STATE is null");
			return this;
		}

		public Criteria andContractStateIsNotNull() {
			addCriterion("CONTRACT_STATE is not null");
			return this;
		}

		public Criteria andContractStateEqualTo(String value) {
			addCriterion("CONTRACT_STATE =", value, "contractState");
			return this;
		}

		public Criteria andContractStateNotEqualTo(String value) {
			addCriterion("CONTRACT_STATE <>", value, "contractState");
			return this;
		}

		public Criteria andContractStateGreaterThan(String value) {
			addCriterion("CONTRACT_STATE >", value, "contractState");
			return this;
		}

		public Criteria andContractStateGreaterThanOrEqualTo(String value) {
			addCriterion("CONTRACT_STATE >=", value, "contractState");
			return this;
		}

		public Criteria andContractStateLessThan(String value) {
			addCriterion("CONTRACT_STATE <", value, "contractState");
			return this;
		}

		public Criteria andContractStateLessThanOrEqualTo(String value) {
			addCriterion("CONTRACT_STATE <=", value, "contractState");
			return this;
		}

		public Criteria andContractStateLike(String value) {
			addCriterion("CONTRACT_STATE like", value, "contractState");
			return this;
		}

		public Criteria andContractStateNotLike(String value) {
			addCriterion("CONTRACT_STATE not like", value, "contractState");
			return this;
		}

		public Criteria andContractStateIn(List<String> values) {
			addCriterion("CONTRACT_STATE in", values, "contractState");
			return this;
		}

		public Criteria andContractStateNotIn(List<String> values) {
			addCriterion("CONTRACT_STATE not in", values, "contractState");
			return this;
		}

		public Criteria andContractStateBetween(String value1, String value2) {
			addCriterion("CONTRACT_STATE between", value1, value2,
					"contractState");
			return this;
		}

		public Criteria andContractStateNotBetween(String value1, String value2) {
			addCriterion("CONTRACT_STATE not between", value1, value2,
					"contractState");
			return this;
		}

		public Criteria andExpiryDateIsNull() {
			addCriterion("EXPIRY_DATE is null");
			return this;
		}

		public Criteria andExpiryDateIsNotNull() {
			addCriterion("EXPIRY_DATE is not null");
			return this;
		}

		public Criteria andExpiryDateEqualTo(String value) {
			addCriterion("EXPIRY_DATE =", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateNotEqualTo(String value) {
			addCriterion("EXPIRY_DATE <>", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateGreaterThan(String value) {
			addCriterion("EXPIRY_DATE >", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateGreaterThanOrEqualTo(String value) {
			addCriterion("EXPIRY_DATE >=", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateLessThan(String value) {
			addCriterion("EXPIRY_DATE <", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateLessThanOrEqualTo(String value) {
			addCriterion("EXPIRY_DATE <=", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateLike(String value) {
			addCriterion("EXPIRY_DATE like", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateNotLike(String value) {
			addCriterion("EXPIRY_DATE not like", value, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateIn(List<String> values) {
			addCriterion("EXPIRY_DATE in", values, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateNotIn(List<String> values) {
			addCriterion("EXPIRY_DATE not in", values, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateBetween(String value1, String value2) {
			addCriterion("EXPIRY_DATE between", value1, value2, "expiryDate");
			return this;
		}

		public Criteria andExpiryDateNotBetween(String value1, String value2) {
			addCriterion("EXPIRY_DATE not between", value1, value2,
					"expiryDate");
			return this;
		}

		public Criteria andCreateUserIsNull() {
			addCriterion("CREATE_USER is null");
			return this;
		}

		public Criteria andCreateUserIsNotNull() {
			addCriterion("CREATE_USER is not null");
			return this;
		}

		public Criteria andCreateUserEqualTo(String value) {
			addCriterion("CREATE_USER =", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotEqualTo(String value) {
			addCriterion("CREATE_USER <>", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThan(String value) {
			addCriterion("CREATE_USER >", value, "createUser");
			return this;
		}

		public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_USER >=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThan(String value) {
			addCriterion("CREATE_USER <", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLessThanOrEqualTo(String value) {
			addCriterion("CREATE_USER <=", value, "createUser");
			return this;
		}

		public Criteria andCreateUserLike(String value) {
			addCriterion("CREATE_USER like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserNotLike(String value) {
			addCriterion("CREATE_USER not like", value, "createUser");
			return this;
		}

		public Criteria andCreateUserIn(List<String> values) {
			addCriterion("CREATE_USER in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserNotIn(List<String> values) {
			addCriterion("CREATE_USER not in", values, "createUser");
			return this;
		}

		public Criteria andCreateUserBetween(String value1, String value2) {
			addCriterion("CREATE_USER between", value1, value2, "createUser");
			return this;
		}

		public Criteria andCreateUserNotBetween(String value1, String value2) {
			addCriterion("CREATE_USER not between", value1, value2,
					"createUser");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CREATE_TIME like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CREATE_TIME not like", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andModifyUserIsNull() {
			addCriterion("MODIFY_USER is null");
			return this;
		}

		public Criteria andModifyUserIsNotNull() {
			addCriterion("MODIFY_USER is not null");
			return this;
		}

		public Criteria andModifyUserEqualTo(String value) {
			addCriterion("MODIFY_USER =", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotEqualTo(String value) {
			addCriterion("MODIFY_USER <>", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThan(String value) {
			addCriterion("MODIFY_USER >", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER >=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThan(String value) {
			addCriterion("MODIFY_USER <", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_USER <=", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserLike(String value) {
			addCriterion("MODIFY_USER like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotLike(String value) {
			addCriterion("MODIFY_USER not like", value, "modifyUser");
			return this;
		}

		public Criteria andModifyUserIn(List<String> values) {
			addCriterion("MODIFY_USER in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotIn(List<String> values) {
			addCriterion("MODIFY_USER not in", values, "modifyUser");
			return this;
		}

		public Criteria andModifyUserBetween(String value1, String value2) {
			addCriterion("MODIFY_USER between", value1, value2, "modifyUser");
			return this;
		}

		public Criteria andModifyUserNotBetween(String value1, String value2) {
			addCriterion("MODIFY_USER not between", value1, value2,
					"modifyUser");
			return this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("MODIFY_TIME is null");
			return this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("MODIFY_TIME is not null");
			return this;
		}

		public Criteria andModifyTimeEqualTo(String value) {
			addCriterion("MODIFY_TIME =", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotEqualTo(String value) {
			addCriterion("MODIFY_TIME <>", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThan(String value) {
			addCriterion("MODIFY_TIME >", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME >=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThan(String value) {
			addCriterion("MODIFY_TIME <", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(String value) {
			addCriterion("MODIFY_TIME <=", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeLike(String value) {
			addCriterion("MODIFY_TIME like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotLike(String value) {
			addCriterion("MODIFY_TIME not like", value, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeIn(List<String> values) {
			addCriterion("MODIFY_TIME in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotIn(List<String> values) {
			addCriterion("MODIFY_TIME not in", values, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
			return this;
		}

		public Criteria andModifyTimeNotBetween(String value1, String value2) {
			addCriterion("MODIFY_TIME not between", value1, value2,
					"modifyTime");
			return this;
		}

		public Criteria andDataStateIsNull() {
			addCriterion("DATA_STATE is null");
			return this;
		}

		public Criteria andDataStateIsNotNull() {
			addCriterion("DATA_STATE is not null");
			return this;
		}

		public Criteria andDataStateEqualTo(String value) {
			addCriterion("DATA_STATE =", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotEqualTo(String value) {
			addCriterion("DATA_STATE <>", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThan(String value) {
			addCriterion("DATA_STATE >", value, "dataState");
			return this;
		}

		public Criteria andDataStateGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_STATE >=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThan(String value) {
			addCriterion("DATA_STATE <", value, "dataState");
			return this;
		}

		public Criteria andDataStateLessThanOrEqualTo(String value) {
			addCriterion("DATA_STATE <=", value, "dataState");
			return this;
		}

		public Criteria andDataStateLike(String value) {
			addCriterion("DATA_STATE like", value, "dataState");
			return this;
		}

		public Criteria andDataStateNotLike(String value) {
			addCriterion("DATA_STATE not like", value, "dataState");
			return this;
		}

		public Criteria andDataStateIn(List<String> values) {
			addCriterion("DATA_STATE in", values, "dataState");
			return this;
		}

		public Criteria andDataStateNotIn(List<String> values) {
			addCriterion("DATA_STATE not in", values, "dataState");
			return this;
		}

		public Criteria andDataStateBetween(String value1, String value2) {
			addCriterion("DATA_STATE between", value1, value2, "dataState");
			return this;
		}

		public Criteria andDataStateNotBetween(String value1, String value2) {
			addCriterion("DATA_STATE not between", value1, value2, "dataState");
			return this;
		}
	}
}