package com.suning.svc.ibatis.model;

import java.util.Date;

public class Settlement {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SETTLEMENT.ID
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long id;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.SETTLE_NO
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String settleNo;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.SETTLE_BATCH_ID
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long settleBatchId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.MCHT_ENTITY_ID
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String mchtEntityId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.FATHER_ENTITY_ID
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String fatherEntityId;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.BEGIN_DATE
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Date beginDate;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.END_DATE
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Date endDate;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.TOTAL_AMOUNT
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long totalAmount;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.COMMISSION_AMOUNT
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long commissionAmount;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.RECEIVED_INVOINCE_AMOUNT
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long receivedInvoinceAmount;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.WAIT_IVC_AMOUNT
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Long waitIvcAmount;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column TB_SETTLEMENT.STATUS
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String status;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.CREATED_TIME
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Date createdTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.UPDATED_TIME
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private Date updatedTime;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.SEND_STATUS
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String sendStatus;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column
     * TB_SETTLEMENT.INVOICE_SEND_STATUS
     * 
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    private String invoiceSendStatus;

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.ID
     * 
     * @return the value of TB_SETTLEMENT.ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.ID
     * 
     * @param id the value for TB_SETTLEMENT.ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.SETTLE_NO
     * 
     * @return the value of TB_SETTLEMENT.SETTLE_NO
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getSettleNo() {
        return settleNo;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.SETTLE_NO
     * 
     * @param settleNo the value for TB_SETTLEMENT.SETTLE_NO
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setSettleNo(String settleNo) {
        this.settleNo = settleNo;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.SETTLE_BATCH_ID
     * 
     * @return the value of TB_SETTLEMENT.SETTLE_BATCH_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getSettleBatchId() {
        return settleBatchId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.SETTLE_BATCH_ID
     * 
     * @param settleBatchId the value for TB_SETTLEMENT.SETTLE_BATCH_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setSettleBatchId(Long settleBatchId) {
        this.settleBatchId = settleBatchId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.MCHT_ENTITY_ID
     * 
     * @return the value of TB_SETTLEMENT.MCHT_ENTITY_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getMchtEntityId() {
        return mchtEntityId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.MCHT_ENTITY_ID
     * 
     * @param mchtEntityId the value for TB_SETTLEMENT.MCHT_ENTITY_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setMchtEntityId(String mchtEntityId) {
        this.mchtEntityId = mchtEntityId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.FATHER_ENTITY_ID
     * 
     * @return the value of TB_SETTLEMENT.FATHER_ENTITY_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getFatherEntityId() {
        return fatherEntityId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.FATHER_ENTITY_ID
     * 
     * @param fatherEntityId the value for TB_SETTLEMENT.FATHER_ENTITY_ID
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setFatherEntityId(String fatherEntityId) {
        this.fatherEntityId = fatherEntityId;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.BEGIN_DATE
     * 
     * @return the value of TB_SETTLEMENT.BEGIN_DATE
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.BEGIN_DATE
     * 
     * @param beginDate the value for TB_SETTLEMENT.BEGIN_DATE
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.END_DATE
     * 
     * @return the value of TB_SETTLEMENT.END_DATE
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.END_DATE
     * 
     * @param endDate the value for TB_SETTLEMENT.END_DATE
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.TOTAL_AMOUNT
     * 
     * @return the value of TB_SETTLEMENT.TOTAL_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.TOTAL_AMOUNT
     * 
     * @param totalAmount the value for TB_SETTLEMENT.TOTAL_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.COMMISSION_AMOUNT
     * 
     * @return the value of TB_SETTLEMENT.COMMISSION_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getCommissionAmount() {
        return commissionAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.COMMISSION_AMOUNT
     * 
     * @param commissionAmount the value for TB_SETTLEMENT.COMMISSION_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setCommissionAmount(Long commissionAmount) {
        this.commissionAmount = commissionAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.RECEIVED_INVOINCE_AMOUNT
     * 
     * @return the value of TB_SETTLEMENT.RECEIVED_INVOINCE_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getReceivedInvoinceAmount() {
        return receivedInvoinceAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.RECEIVED_INVOINCE_AMOUNT
     * 
     * @param receivedInvoinceAmount the value for TB_SETTLEMENT.RECEIVED_INVOINCE_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setReceivedInvoinceAmount(Long receivedInvoinceAmount) {
        this.receivedInvoinceAmount = receivedInvoinceAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.WAIT_IVC_AMOUNT
     * 
     * @return the value of TB_SETTLEMENT.WAIT_IVC_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Long getWaitIvcAmount() {
        return waitIvcAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.WAIT_IVC_AMOUNT
     * 
     * @param waitIvcAmount the value for TB_SETTLEMENT.WAIT_IVC_AMOUNT
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setWaitIvcAmount(Long waitIvcAmount) {
        this.waitIvcAmount = waitIvcAmount;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.STATUS
     * 
     * @return the value of TB_SETTLEMENT.STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.STATUS
     * 
     * @param status the value for TB_SETTLEMENT.STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.CREATED_TIME
     * 
     * @return the value of TB_SETTLEMENT.CREATED_TIME
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.CREATED_TIME
     * 
     * @param createdTime the value for TB_SETTLEMENT.CREATED_TIME
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.UPDATED_TIME
     * 
     * @return the value of TB_SETTLEMENT.UPDATED_TIME
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.UPDATED_TIME
     * 
     * @param updatedTime the value for TB_SETTLEMENT.UPDATED_TIME
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.SEND_STATUS
     * 
     * @return the value of TB_SETTLEMENT.SEND_STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.SEND_STATUS
     * 
     * @param sendStatus the value for TB_SETTLEMENT.SEND_STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setSendStatus(String sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column
     * TB_SETTLEMENT.INVOICE_SEND_STATUS
     * 
     * @return the value of TB_SETTLEMENT.INVOICE_SEND_STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public String getInvoiceSendStatus() {
        return invoiceSendStatus;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column
     * TB_SETTLEMENT.INVOICE_SEND_STATUS
     * 
     * @param invoiceSendStatus the value for TB_SETTLEMENT.INVOICE_SEND_STATUS
     * @abatorgenerated Sat Dec 14 15:22:23 CST 2013
     */
    public void setInvoiceSendStatus(String invoiceSendStatus) {
        this.invoiceSendStatus = invoiceSendStatus;
    }
}