package com.suning.svc.ibatis.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.suning.svc.ibatis.model.Invoice;
import com.suning.svc.ibatis.model.InvoiceExample;

public class InvoiceDAOImpl extends SqlMapClientDaoSupport implements InvoiceDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public InvoiceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public void insert(Invoice record) {
        getSqlMapClientTemplate().insert("TB_INVOICE.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int updateByPrimaryKey(Invoice record) {
        int rows = getSqlMapClientTemplate().update("TB_INVOICE.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int updateByPrimaryKeySelective(Invoice record) {
        int rows = getSqlMapClientTemplate().update("TB_INVOICE.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public List selectByExample(InvoiceExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_INVOICE.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public Invoice selectByPrimaryKey(Long id) {
        Invoice key = new Invoice();
        key.setId(id);
        Invoice record = (Invoice) getSqlMapClientTemplate().queryForObject(
                "TB_INVOICE.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int deleteByExample(InvoiceExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_INVOICE.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        Invoice key = new Invoice();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("TB_INVOICE.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int countByExample(InvoiceExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("TB_INVOICE.abatorgenerated_countByExample",
                example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int updateByExampleSelective(Invoice record, InvoiceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_INVOICE.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    public int updateByExample(Invoice record, InvoiceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_INVOICE.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table TB_INVOICE
     * 
     * @abatorgenerated Sun Nov 10 09:41:06 CST 2013
     */
    private static class UpdateByExampleParms extends InvoiceExample {
        private Object record;

        public UpdateByExampleParms(Object record, InvoiceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}