package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.AccRelCardAccount;
import com.allinfinance.prepay.model.AccRelCardAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccRelCardAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int countByExample(AccRelCardAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int deleteByExample(AccRelCardAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int insert(AccRelCardAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int insertSelective(AccRelCardAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    List<AccRelCardAccount> selectByExample(AccRelCardAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccRelCardAccount record, @Param("example") AccRelCardAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ACC_REL_CARD_ACCOUNT
     *
     * @mbggenerated Fri Apr 29 09:36:15 CST 2016
     */
    int updateByExample(@Param("record") AccRelCardAccount record, @Param("example") AccRelCardAccountExample example);
}