package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.CardholderPersonal;
import com.allinfinance.prepay.model.CardholderPersonalExample;
import com.allinfinance.prepay.model.CardholderPersonalKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardholderPersonalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int countByExample(CardholderPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int deleteByExample(CardholderPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int deleteByPrimaryKey(CardholderPersonalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int insert(CardholderPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int insertSelective(CardholderPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    List<CardholderPersonal> selectByExample(CardholderPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    CardholderPersonal selectByPrimaryKey(CardholderPersonalKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") CardholderPersonal record, @Param("example") CardholderPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int updateByExample(@Param("record") CardholderPersonal record, @Param("example") CardholderPersonalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int updateByPrimaryKeySelective(CardholderPersonal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CARDHOLDER_PERSONAL
     *
     * @mbggenerated Mon Aug 14 15:31:14 CST 2017
     */
    int updateByPrimaryKey(CardholderPersonal record);
}