package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.CompanyInfo;
import com.allinfinance.prepay.model.CompanyInfoExample;
import com.allinfinance.prepay.model.CompanyInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int countByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int deleteByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int deleteByPrimaryKey(CompanyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int insert(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int insertSelective(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    List<CompanyInfo> selectByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    CompanyInfo selectByPrimaryKey(CompanyInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int updateByExampleSelective(@Param("record") CompanyInfo record, @Param("example") CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int updateByExample(@Param("record") CompanyInfo record, @Param("example") CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int updateByPrimaryKeySelective(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_COMPANY_INFO
     *
     * @mbggenerated Mon Aug 14 15:30:07 CST 2017
     */
    int updateByPrimaryKey(CompanyInfo record);
    
    int updateByValidity(CompanyInfo record);
}