package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.CustomerEnterPrise;
import com.allinfinance.prepay.model.CustomerEnterPriseExample;
import com.allinfinance.prepay.model.CustomerEnterPriseKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerEnterPriseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int countByExample(CustomerEnterPriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int deleteByExample(CustomerEnterPriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int deleteByPrimaryKey(CustomerEnterPriseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int insert(CustomerEnterPrise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int insertSelective(CustomerEnterPrise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    List<CustomerEnterPrise> selectByExample(CustomerEnterPriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    CustomerEnterPrise selectByPrimaryKey(CustomerEnterPriseKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") CustomerEnterPrise record, @Param("example") CustomerEnterPriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int updateByExample(@Param("record") CustomerEnterPrise record, @Param("example") CustomerEnterPriseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int updateByPrimaryKeySelective(CustomerEnterPrise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_CUSTOMER_ENTERPRISE
     *
     * @mbggenerated Mon Aug 14 15:28:45 CST 2017
     */
    int updateByPrimaryKey(CustomerEnterPrise record);
}