package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.EntityDelivery;
import com.allinfinance.prepay.model.EntityDeliveryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EntityDeliveryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int countByExample(EntityDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int deleteByExample(EntityDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int insert(EntityDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int insertSelective(EntityDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    List<EntityDelivery> selectByExample(EntityDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") EntityDelivery record, @Param("example") EntityDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_ENTITY_DELIVERY
     *
     * @mbggenerated Mon Apr 25 14:59:50 CST 2016
     */
    int updateByExample(@Param("record") EntityDelivery record, @Param("example") EntityDeliveryExample example);
}