package com.allinfinance.prepay.mapper.svc_mng;

import com.allinfinance.prepay.model.SellAcctypeContract;
import com.allinfinance.prepay.model.SellAcctypeContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellAcctypeContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int countByExample(SellAcctypeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int deleteByExample(SellAcctypeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int insert(SellAcctypeContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int insertSelective(SellAcctypeContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    List<SellAcctypeContract> selectByExample(SellAcctypeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") SellAcctypeContract record, @Param("example") SellAcctypeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SVC_MNG.TB_SELL_ACCTYPE_CONTRACT
     *
     * @mbggenerated Tue Apr 26 11:57:32 CST 2016
     */
    int updateByExample(@Param("record") SellAcctypeContract record, @Param("example") SellAcctypeContractExample example);
}