server:
  port: 8081
 
eureka:
  instance:
    hostname: localhost
    client:
      registerWithEureka: false  #表明自己是一个eureka server
      fetchRegistry: false  #表明自己是一个eureka server
      serviceUrl:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
