package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.CustomerPersonal;
import com.huateng.framework.ibatis.model.CustomerPersonalExample;
import com.huateng.framework.ibatis.model.CustomerPersonalKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CustomerPersonalDAOImpl extends SqlMapClientDaoSupport implements CustomerPersonalDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public CustomerPersonalDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int countByExample(CustomerPersonalExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TB_CUSTOMER_PERSONAL.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int deleteByExample(CustomerPersonalExample example) {
        int rows = getSqlMapClientTemplate().delete("TB_CUSTOMER_PERSONAL.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int deleteByPrimaryKey(CustomerPersonalKey key) {
        int rows = getSqlMapClientTemplate().delete("TB_CUSTOMER_PERSONAL.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public void insert(CustomerPersonal record) {
        getSqlMapClientTemplate().insert("TB_CUSTOMER_PERSONAL.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public void insertSelective(CustomerPersonal record) {
        getSqlMapClientTemplate().insert("TB_CUSTOMER_PERSONAL.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public List selectByExample(CustomerPersonalExample example) {
        List list = getSqlMapClientTemplate().queryForList("TB_CUSTOMER_PERSONAL.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public CustomerPersonal selectByPrimaryKey(CustomerPersonalKey key) {
        CustomerPersonal record = (CustomerPersonal) getSqlMapClientTemplate().queryForObject("TB_CUSTOMER_PERSONAL.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int updateByExampleSelective(CustomerPersonal record, CustomerPersonalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CUSTOMER_PERSONAL.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int updateByExample(CustomerPersonal record, CustomerPersonalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TB_CUSTOMER_PERSONAL.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int updateByPrimaryKeySelective(CustomerPersonal record) {
        int rows = getSqlMapClientTemplate().update("TB_CUSTOMER_PERSONAL.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    public int updateByPrimaryKey(CustomerPersonal record) {
        int rows = getSqlMapClientTemplate().update("TB_CUSTOMER_PERSONAL.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TB_CUSTOMER_PERSONAL
     *
     * @ibatorgenerated Mon Jul 31 17:03:55 CST 2017
     */
    private static class UpdateByExampleParms extends CustomerPersonalExample {
        private Object record;

        public UpdateByExampleParms(Object record, CustomerPersonalExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}