package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.EntityStockOperater;
import com.huateng.framework.ibatis.model.EntityStockOperaterExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EntityStockOperaterDAOImpl extends SqlMapClientDaoSupport
		implements EntityStockOperaterDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public EntityStockOperaterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public void insert(EntityStockOperater record) {
		getSqlMapClientTemplate().insert(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int updateByPrimaryKey(EntityStockOperater record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int updateByPrimaryKeySelective(EntityStockOperater record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_STOCK_OPERATER.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<EntityStockOperater> selectByExample(
			EntityStockOperaterExample example) {
		List<EntityStockOperater> list = (List<EntityStockOperater>) getSqlMapClientTemplate()
				.queryForList(
						"TB_ENTITY_STOCK_OPERATER.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public EntityStockOperater selectByPrimaryKey(String operaterId) {
		EntityStockOperater key = new EntityStockOperater();
		key.setOperaterId(operaterId);
		EntityStockOperater record = (EntityStockOperater) getSqlMapClientTemplate()
				.queryForObject(
						"TB_ENTITY_STOCK_OPERATER.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int deleteByExample(EntityStockOperaterExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int deleteByPrimaryKey(String operaterId) {
		EntityStockOperater key = new EntityStockOperater();
		key.setOperaterId(operaterId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int countByExample(EntityStockOperaterExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_countByExample",
				example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int updateByExampleSelective(EntityStockOperater record,
			EntityStockOperaterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_ENTITY_STOCK_OPERATER.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	public int updateByExample(EntityStockOperater record,
			EntityStockOperaterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_ENTITY_STOCK_OPERATER.abatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_ENTITY_STOCK_OPERATER
	 * 
	 * @abatorgenerated Thu Jan 13 17:14:35 CST 2011
	 */
	private static class UpdateByExampleParms extends
			EntityStockOperaterExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				EntityStockOperaterExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}