package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.EntityInvoiceAddress;
import com.huateng.framework.ibatis.model.EntityInvoiceAddressExample;
import java.util.List;

public interface EntityInvoiceAddressDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	void insert(EntityInvoiceAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int updateByPrimaryKey(EntityInvoiceAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int updateByPrimaryKeySelective(EntityInvoiceAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	List<EntityInvoiceAddress> selectByExample(
			EntityInvoiceAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	EntityInvoiceAddress selectByPrimaryKey(String invoiceAddressId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int deleteByExample(EntityInvoiceAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int deleteByPrimaryKey(String invoiceAddressId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int countByExample(EntityInvoiceAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int updateByExampleSelective(EntityInvoiceAddress record,
			EntityInvoiceAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_ENTITY_INVOICE_ADDRESS
	 * 
	 * @abatorgenerated Thu Nov 18 17:01:26 CST 2010
	 */
	int updateByExample(EntityInvoiceAddress record,
			EntityInvoiceAddressExample example);
}