package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.Seller;
import com.huateng.framework.ibatis.model.SellerExample;
import com.huateng.framework.ibatis.model.SellerKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SellerDAOImpl extends SqlMapClientDaoSupport implements SellerDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public SellerDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public void insert(Seller record) {
		getSqlMapClientTemplate().insert("TB_SELLER.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int updateByPrimaryKey(Seller record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_SELLER.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int updateByPrimaryKeySelective(Seller record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_SELLER.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<Seller> selectByExample(SellerExample example) {
		List<Seller> list = (List<Seller>) getSqlMapClientTemplate()
				.queryForList("TB_SELLER.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public Seller selectByPrimaryKey(SellerKey key) {
		Seller record = (Seller) getSqlMapClientTemplate().queryForObject(
				"TB_SELLER.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int deleteByExample(SellerExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELLER.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int deleteByPrimaryKey(SellerKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_SELLER.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int countByExample(SellerExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_SELLER.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int updateByExampleSelective(Seller record, SellerExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELLER.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	public int updateByExample(Seller record, SellerExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_SELLER.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_SELLER
	 * 
	 * @abatorgenerated Sat Jan 08 16:26:26 CST 2011
	 */
	private static class UpdateByExampleParms extends SellerExample {
		private Object record;

		public UpdateByExampleParms(Object record, SellerExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}