package com.huateng.framework.ibatis.dao;

import com.allinfinance.univer.seller.order.dto.SellOrderDTO;
import com.huateng.framework.ibatis.model.SellOrderList;
import com.huateng.framework.ibatis.model.SellOrderListExample;
import java.util.List;

public interface SellOrderListDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	void insert(SellOrderList record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int updateByPrimaryKey(SellOrderList record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int updateByPrimaryKeySelective(SellOrderList record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	List<SellOrderList> selectByExample(SellOrderListExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	SellOrderList selectByPrimaryKey(String orderListId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int deleteByExample(SellOrderListExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int deleteByPrimaryKey(String orderListId);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int countByExample(SellOrderListExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int updateByExampleSelective(SellOrderList record,
			SellOrderListExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SELL_ORDER_LIST
	 * 
	 * @abatorgenerated Tue Dec 14 10:30:41 CST 2010
	 */
	int updateByExample(SellOrderList record, SellOrderListExample example);
}