package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.SettlePeriodRule;
import com.huateng.framework.ibatis.model.SettlePeriodRuleExample;
import java.util.List;

public interface SettlePeriodRuleDAO {
	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	void insert(SettlePeriodRule record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int updateByPrimaryKey(SettlePeriodRule record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int updateByPrimaryKeySelective(SettlePeriodRule record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	List<SettlePeriodRule> selectByExample(SettlePeriodRuleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	SettlePeriodRule selectByPrimaryKey(String ruleNo);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int deleteByExample(SettlePeriodRuleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int deleteByPrimaryKey(String ruleNo);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int countByExample(SettlePeriodRuleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int updateByExampleSelective(SettlePeriodRule record,
			SettlePeriodRuleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_SETTLE_PERIOD_RULE
	 * 
	 * @abatorgenerated Sun Sep 26 15:57:01 CST 2010
	 */
	int updateByExample(SettlePeriodRule record, SettlePeriodRuleExample example);
}