package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.TblOrderBatchConstrain;
import com.huateng.framework.ibatis.model.TblOrderBatchConstrainExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TblOrderBatchConstrainDAOImpl extends SqlMapClientDaoSupport implements TblOrderBatchConstrainDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public TblOrderBatchConstrainDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public void insert(TblOrderBatchConstrain record) {
        getSqlMapClientTemplate().insert("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int updateByPrimaryKey(TblOrderBatchConstrain record) {
        int rows = getSqlMapClientTemplate().update("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int updateByPrimaryKeySelective(TblOrderBatchConstrain record) {
        int rows = getSqlMapClientTemplate().update("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<TblOrderBatchConstrain> selectByExample(TblOrderBatchConstrainExample example) {
        List<TblOrderBatchConstrain> list = (List<TblOrderBatchConstrain>) getSqlMapClientTemplate().queryForList("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public TblOrderBatchConstrain selectByPrimaryKey(String orderId) {
        TblOrderBatchConstrain key = new TblOrderBatchConstrain();
        key.setOrderId(orderId);
        TblOrderBatchConstrain record = (TblOrderBatchConstrain) getSqlMapClientTemplate().queryForObject("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int deleteByExample(TblOrderBatchConstrainExample example) {
        int rows = getSqlMapClientTemplate().delete("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int deleteByPrimaryKey(String orderId) {
        TblOrderBatchConstrain key = new TblOrderBatchConstrain();
        key.setOrderId(orderId);
        int rows = getSqlMapClientTemplate().delete("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int countByExample(TblOrderBatchConstrainExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int updateByExampleSelective(TblOrderBatchConstrain record, TblOrderBatchConstrainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    public int updateByExample(TblOrderBatchConstrain record, TblOrderBatchConstrainExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TBL_ORDER_BATCH_CONSTRAIN.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TBL_ORDER_BATCH_CONSTRAIN
     *
     * @abatorgenerated Mon Jan 21 17:33:32 CST 2013
     */
    private static class UpdateByExampleParms extends TblOrderBatchConstrainExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblOrderBatchConstrainExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}