package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.ValidRuleDsp;
import com.huateng.framework.ibatis.model.ValidRuleDspExample;
import com.huateng.framework.ibatis.model.ValidRuleDspKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ValidRuleDspDAOImpl extends SqlMapClientDaoSupport implements
		ValidRuleDspDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public ValidRuleDspDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public void insert(ValidRuleDsp record) {
		getSqlMapClientTemplate().insert(
				"TB_VALID_RULE_DSP.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int updateByPrimaryKey(ValidRuleDsp record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_VALID_RULE_DSP.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int updateByPrimaryKeySelective(ValidRuleDsp record) {
		int rows = getSqlMapClientTemplate()
				.update(
						"TB_VALID_RULE_DSP.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	@SuppressWarnings("unchecked")
	public List<ValidRuleDsp> selectByExample(ValidRuleDspExample example) {
		List<ValidRuleDsp> list = (List<ValidRuleDsp>) getSqlMapClientTemplate()
				.queryForList(
						"TB_VALID_RULE_DSP.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public ValidRuleDsp selectByPrimaryKey(ValidRuleDspKey key) {
		ValidRuleDsp record = (ValidRuleDsp) getSqlMapClientTemplate()
				.queryForObject(
						"TB_VALID_RULE_DSP.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int deleteByExample(ValidRuleDspExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_VALID_RULE_DSP.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int deleteByPrimaryKey(ValidRuleDspKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_VALID_RULE_DSP.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int countByExample(ValidRuleDspExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_VALID_RULE_DSP.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int updateByExampleSelective(ValidRuleDsp record,
			ValidRuleDspExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VALID_RULE_DSP.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	public int updateByExample(ValidRuleDsp record, ValidRuleDspExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_VALID_RULE_DSP.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_VALID_RULE_DSP
	 * 
	 * @abatorgenerated Thu Feb 23 10:40:18 CST 2012
	 */
	private static class UpdateByExampleParms extends ValidRuleDspExample {
		private Object record;

		public UpdateByExampleParms(Object record, ValidRuleDspExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}