package com.suning.svc.ibatis.dao;

import com.suning.svc.ibatis.model.VirtualCard;
import com.suning.svc.ibatis.model.VirtualCardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VirtualCardDAOImpl extends SqlMapClientDaoSupport implements VirtualCardDAO {

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public VirtualCardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public void insert(VirtualCard record) {
        getSqlMapClientTemplate().insert("CP_VIRTUAL_CARD.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int updateByPrimaryKey(VirtualCard record) {
        int rows = getSqlMapClientTemplate().update("CP_VIRTUAL_CARD.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int updateByPrimaryKeySelective(VirtualCard record) {
        int rows = getSqlMapClientTemplate().update("CP_VIRTUAL_CARD.abatorgenerated_updateByPrimaryKeySelective",
                record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public List selectByExample(VirtualCardExample example) {
        List list = getSqlMapClientTemplate().queryForList("CP_VIRTUAL_CARD.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public VirtualCard selectByPrimaryKey(Long id) {
        VirtualCard key = new VirtualCard();
        key.setId(id);
        VirtualCard record = (VirtualCard) getSqlMapClientTemplate().queryForObject(
                "CP_VIRTUAL_CARD.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int deleteByExample(VirtualCardExample example) {
        int rows = getSqlMapClientTemplate().delete("CP_VIRTUAL_CARD.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int deleteByPrimaryKey(Long id) {
        VirtualCard key = new VirtualCard();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("CP_VIRTUAL_CARD.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int countByExample(VirtualCardExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
                "CP_VIRTUAL_CARD.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int updateByExampleSelective(VirtualCard record, VirtualCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CP_VIRTUAL_CARD.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS. This method corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    public int updateByExample(VirtualCard record, VirtualCardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CP_VIRTUAL_CARD.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS. This class corresponds to the database table CP_VIRTUAL_CARD
     * 
     * @abatorgenerated Tue Nov 05 22:32:09 CST 2013
     */
    private static class UpdateByExampleParms extends VirtualCardExample {
        private Object record;

        public UpdateByExampleParms(Object record, VirtualCardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}