package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.BatchDetail;
import com.huateng.framework.ibatis.model.BatchDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BatchDetailDAOImpl extends SqlMapClientDaoSupport implements BatchDetailDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public BatchDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public void insert(BatchDetail record) {
        getSqlMapClientTemplate().insert("TBL_ACC_BATCH_DETAIL.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int updateByPrimaryKey(BatchDetail record) {
        int rows = getSqlMapClientTemplate().update("TBL_ACC_BATCH_DETAIL.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int updateByPrimaryKeySelective(BatchDetail record) {
        int rows = getSqlMapClientTemplate().update("TBL_ACC_BATCH_DETAIL.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<BatchDetail> selectByExample(BatchDetailExample example) {
        List<BatchDetail> list = (List<BatchDetail>) getSqlMapClientTemplate().queryForList("TBL_ACC_BATCH_DETAIL.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public BatchDetail selectByPrimaryKey(String smltDate) {
        BatchDetail key = new BatchDetail();
        key.setSmltDate(smltDate);
        BatchDetail record = (BatchDetail) getSqlMapClientTemplate().queryForObject("TBL_ACC_BATCH_DETAIL.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int deleteByExample(BatchDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("TBL_ACC_BATCH_DETAIL.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int deleteByPrimaryKey(String smltDate) {
        BatchDetail key = new BatchDetail();
        key.setSmltDate(smltDate);
        int rows = getSqlMapClientTemplate().delete("TBL_ACC_BATCH_DETAIL.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int countByExample(BatchDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TBL_ACC_BATCH_DETAIL.abatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int updateByExampleSelective(BatchDetail record, BatchDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TBL_ACC_BATCH_DETAIL.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    public int updateByExample(BatchDetail record, BatchDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TBL_ACC_BATCH_DETAIL.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table TBL_ACC_BATCH_DETAIL
     *
     * @abatorgenerated Wed Oct 24 18:32:56 CST 2012
     */
    private static class UpdateByExampleParms extends BatchDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, BatchDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}