package com.huateng.framework.ibatis.dao;

import com.huateng.framework.ibatis.model.Product;
import com.huateng.framework.ibatis.model.ProductExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductDAOImpl extends SqlMapClientDaoSupport implements
		ProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public ProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public void insert(Product record) {
		getSqlMapClientTemplate().insert("TB_PRODUCT.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int updateByPrimaryKey(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_PRODUCT.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int updateByPrimaryKeySelective(Product record) {
		int rows = getSqlMapClientTemplate().update(
				"TB_PRODUCT.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	@SuppressWarnings("unchecked")
	public List<Product> selectByExample(ProductExample example) {
		List<Product> list = (List<Product>) getSqlMapClientTemplate()
				.queryForList("TB_PRODUCT.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public Product selectByPrimaryKey(String productId) {
		Product key = new Product();
		key.setProductId(productId);
		Product record = (Product) getSqlMapClientTemplate().queryForObject(
				"TB_PRODUCT.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int deleteByExample(ProductExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TB_PRODUCT.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int deleteByPrimaryKey(String productId) {
		Product key = new Product();
		key.setProductId(productId);
		int rows = getSqlMapClientTemplate().delete(
				"TB_PRODUCT.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int countByExample(ProductExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TB_PRODUCT.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int updateByExampleSelective(Product record, ProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_PRODUCT.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	public int updateByExample(Product record, ProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TB_PRODUCT.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table TB_PRODUCT
	 * 
	 * @abatorgenerated Wed Feb 15 10:28:20 CST 2012
	 */
	private static class UpdateByExampleParms extends ProductExample {
		private Object record;

		public UpdateByExampleParms(Object record, ProductExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}