eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: service-feign

server:
  port: 8902
  
feign:
  hystrix:
    enabled: true  #激活断路器